### ISSUE TITLE
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce2' in position 73: surrogates not allowed

### ISSUE THREAD

**Issue by devurandom** [getnikola/nikola#1346]
I get the following, when executing `nikola build` from a Mercurial changegroup hook, run by the webserver after `hg push`, I get:
```
Scanning posts....done!
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/doit/doit_cmd.py", line 120, in run
    return command.parse_execute(args)
  File "/usr/lib/python3.3/site-packages/doit/cmd_base.py", line 78, in parse_execute
    return self.execute(params, args)
  File "/usr/lib/python3.3/site-packages/doit/cmd_base.py", line 268, in execute
    return self._execute(**exec_params)
  File "/usr/lib/python3.3/site-packages/doit/cmd_run.py", line 212, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "/usr/lib/python3.3/site-packages/doit/runner.py", line 237, in run_all
    self.run_tasks(task_dispatcher)
  File "/usr/lib/python3.3/site-packages/doit/runner.py", line 200, in run_tasks
    if not self.select_task(node, task_dispatcher.tasks):
  File "/usr/lib/python3.3/site-packages/doit/runner.py", line 111, in select_task
    if node.ignored_deps or self.dep_manager.status_is_ignore(task):
  File "/usr/lib/python3.3/site-packages/doit/dependency.py", line 454, in status_is_ignore
    return self._get(task.name, "ignore:")
  File "/usr/lib/python3.3/site-packages/doit/dependency.py", line 239, in get
    task_data = self._dbm[task_id]
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce2' in position 73: surrogates not allowed
```

Please advise me how to debug this further. I assume the problem is with the `task_id`, but I do not know what it is generated from.

If I execute the command manually, there is no error message.

**Comment by Kwpolska** [comment]
No response for a year, closing.
