### ISSUE TITLE
error with nikola build

### ISSUE THREAD

**Issue by wcmckee** [getnikola/nikola#1597]
Hello. I installed Nikola on Debian Jessie and gettting the following error:
nikola build
[2015-01-21T09:50:38Z] WARNING: Nikola: Could not guess locale for language en, using locale C
[2015-01-21T09:50:41Z] WARNING: UserWarning: /home/wcmckee/ipython/IPython/nbformat/current.py:19: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

[2015-01-21T09:50:41Z] WARNING: Nikola: Cannot load theme "site-ipython", using 'bootstrap' instead.
Scanning posts....done!
.  render_posts:cache/posts/GetsDrawnDotCom.html
[2015-01-21T09:50:42Z] WARNING: UserWarning: /home/wcmckee/ipython/IPython/nbformat/current.py:75: reads_json is deprecated, use reads
########################################
TaskError - taskid:render_posts:cache/posts/GetsDrawnDotCom.html
PythonAction Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/doit/action.py", line 360, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/nikola/post.py", line 348, in compile
    self.is_two_file),
  File "/usr/lib/python2.7/dist-packages/nikola/plugins/compile/ipynb/__init__.py", line 63, in compile_html
    (body, resources) = exportHtml.from_notebook_node(nb_json)
  File "/home/wcmckee/ipython/IPython/nbconvert/exporters/html.py", line 57, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/wcmckee/ipython/IPython/nbconvert/exporters/templateexporter.py", line 208, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/wcmckee/ipython/IPython/nbconvert/exporters/exporter.py", line 125, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/wcmckee/ipython/IPython/nbconvert/exporters/exporter.py", line 278, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/wcmckee/ipython/IPython/nbconvert/preprocessors/coalescestreams.py", line 28, in wrappedfunc
    for index, cell in enumerate(nb.cells):
  File "/home/wcmckee/ipython/IPython/utils/ipstruct.py", line 149, in __getattr__
    raise AttributeError(key)
AttributeError: cells

[2015-01-21T09:50:42Z] WARNING: UserWarning: /home/wcmckee/ipython/IPython/nbformat/current.py:75: reads_json is deprecated, use reads

cheers,
wcmckee

**Comment by Kwpolska** [comment]
You are using IPython 3.x, ancient Nikola v7.1.0 from the repos, and outdated instructions (`site-ipython` instead of `ipython` which needs to be installed from `nikola install_theme ipython`).  Please upgrade to Nikola from GitHub master (issue fixed in #1582).

Please also check the correctness of your `.ipynb` file.

**Comment by wcmckee** [comment]
Sorted, thank you.
