### ISSUE TITLE
While running the wizard for a new site, there's an exception with the timezone

### ISSUE THREAD

**Issue by jruere** [getnikola/nikola#1599]
The timezone of my machine is correctly displayed as the default but when accepted, it fails.

```
Time zone [Argentina/Buenos_Aires]: 
    WARNING: Time zone not found.  Searching most common timezones for a match.
Traceback (most recent call last):
  File "/mnt/Unsafe/javier/tmp/virtualenvs/blog/lib/python3.4/site-packages/doit/doit_cmd.py", line 121, in run
    return command.parse_execute(args)
  File "/mnt/Unsafe/javier/tmp/virtualenvs/blog/lib/python3.4/site-packages/doit/cmd_base.py", line 79, in parse_execute
    return self.execute(params, args)
  File "/mnt/Unsafe/javier/tmp/virtualenvs/blog/lib/python3.4/site-packages/nikola/plugin_categories.py", line 105, in execute
    self._execute(options, args)
  File "/mnt/Unsafe/javier/tmp/virtualenvs/blog/lib/python3.4/site-packages/nikola/plugins/command/init.py", line 420, in _execute
    st = self.ask_questions(target=target)
  File "/mnt/Unsafe/javier/tmp/virtualenvs/blog/lib/python3.4/site-packages/nikola/plugins/command/init.py", line 397, in ask_questions
    query(default, toconf)
  File "/mnt/Unsafe/javier/tmp/virtualenvs/blog/lib/python3.4/site-packages/nikola/plugins/command/init.py", line 323, in tzhandler
    zonesfile = tarfile.TarFile.open(os.path.join(dateutil.zoneinfo.ZONEINFOFILE))
AttributeError: 'module' object has no attribute 'ZONEINFOFILE'
```

Software:
- Linux, Arch
- Python 3.4.2
- In a clean virtual environment:

    - blinker (1.3)
    - docutils (0.12)
    - doit (0.26.0)
    - Logbook (0.8.1)
    - lxml (3.4.1)
    - Mako (1.0.1)
    - MarkupSafe (0.23)
    - natsort (3.5.2)
    - Nikola (7.3.0)
    - Pillow (2.7.0)
    - pip (6.0.6)
    - Pygments (2.0.2)
    - pyinotify (0.9.5)
    - PyRSS2Gen (1.1)
    - python-dateutil (2.4.0)
    - setuptools (11.0)
    - six (1.9.0)
    - Unidecode (0.4.17)
    - Yapsy (1.10.423)

**Comment by jruere** [comment]
Look at this:

```
>>> import dateutil.zoneinfo
>>> dir(dateutil.zoneinfo)
['BytesIO', 'TarFile', 'ZoneInfoFile', '_CLASS_ZONE_INSTANCE', '_ZONEFILENAME', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_tar_open', 'check_call', 'closing', 'get_data', 'gettz', 'getzoneinfofile_stream', 'logging', 'os', 'rebuild', 'shutil', 'tempfile', 'tzfile', 'warnings']
>>> dateutil.zoneinfo._ZONEFILENAME
'dateutil-zoneinfo.tar.gz'
```

**Comment by Kwpolska** [comment]
Dateutil changed the API.  `getzoneinfofile_stream` is what we can use right now.

Here’s what would happen right now:

```
Time zone [Europe/Warsaw]: Argentina/Buenos_Aires
    WARNING: Time zone not found.  Searching list of time zones for a match.
    Picking 'America/Argentina/Buenos_Aires'.
    Current time in America/Argentina/Buenos_Aires: 06:42:00
```

While we’re at it, what is your system set to?  What does `ls -l /etc/localtime` say?  I think the detection is broken, too.

**Comment by Kwpolska** [comment]
c223700 should make it better, you should get the proper `America/Argentina/Buenos_Aires` entry now.
