### ISSUE TITLE
ValueError while using nikola

### ISSUE THREAD

**Issue by cemysf** [getnikola/nikola#1619]
Installed nikola with pip, initialized a website without problem, but it gives this error when I'm trying to use commands 

```
cya@n411z:~/dev_/site$ nikola build
ERROR:yapsy:Unable to import plugin: /usr/local/lib/python2.7/dist-packages/nikola/plugins/compile/ipynb
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yapsy/PluginManager.py", line 484, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/usr/local/lib/python2.7/dist-packages/nikola/plugins/compile/ipynb/__init__.py", line 34, in <module>
    from IPython.nbconvert.exporters import HTMLExporter
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/embed.py", line 35, in <module>
    from IPython.terminal.ipapp import load_default_config
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 150, in <module>
    classic_config.PromptManager.in_template = '>>> '
  File "/usr/local/lib/python2.7/dist-packages/IPython/config/loader.py", line 277, in __setattr__
    self.__setitem__(key, value)
  File "/usr/local/lib/python2.7/dist-packages/IPython/config/loader.py", line 262, in __setitem__
    'char must be Config instances: %r, %r' % (key, value))
ValueError: values whose keys begin with an uppercase char must be Config instances: 'in_template', '>>> '
Scanning posts....done!

```

**Comment by Kwpolska** [comment]
ipython version?  do you have any special ipython config?  that’s probably not our fault…

**Comment by Kwpolska** [comment]
also, show the output of

```
python -c "print('in_template'[0].upper(), 'in_template'[0])"

**Comment by cemysf** [comment]
i don't have a special config for ipython
```
cya@n411z:~$ pip show ipython
---
Name: ipython
Version: 2.4.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
cya@n411z:~$ pip install -U ipython
Requirement already up-to-date: ipython in /usr/local/lib/python2.7/dist-packages
```

```
cya@n411z:~$ python -c "print('in_template'[0].upper(), 'in_template'[0])"
('I', 'i')
```

**Comment by Kwpolska** [comment]
Can you reproduce with the following?

```
python -c 'from IPython.nbconvert.exporters import HTMLExporter'
```

If yes, report a bug to the ipython team, as we can’t really help you with this issue.

**Comment by cemysf** [comment]
it gives nothing
```
cya@n411z:~$ python -c 'from IPython.nbconvert.exporters import HTMLExporter'
cya@n411z:~$ 
```

**Comment by Kwpolska** [comment]
Can you reproduce with a clean virtualenv?

**Comment by cemysf** [comment]
```
(virt_env)cya@n411z:~$ python -c 'from IPython.nbconvert.exporters import HTMLExporter'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named IPython.nbconvert.exporters
```

**Comment by Kwpolska** [comment]
1. create a clean virtualenv
2. install nikola and ipython in it
3. run `nikola init -qd ntest; cd ntest; nikola build`

**Comment by cemysf** [comment]
```
(virt_env)cya@n411z:~/virt_env/bin$ nikola init -qd ntest; cd ntest; nikola build
[2015-02-08T19:34:41Z] WARNING: Nikola: In order to USE_BUNDLES, you must install the "webassets" Python package.
[2015-02-08T19:34:41Z] WARNING: bundles: Setting USE_BUNDLES to False.
[2015-02-08T19:34:41Z] INFO: init: A new site with example data has been created at ntest.
[2015-02-08T19:34:41Z] INFO: init: See README.txt in that folder for more information.
[2015-02-08T19:34:41Z] WARNING: Nikola: In order to USE_BUNDLES, you must install the "webassets" Python package.
[2015-02-08T19:34:41Z] WARNING: bundles: Setting USE_BUNDLES to False.
Scanning posts....done!
.  copy_files:output/favicon.ico
.  copy_files:output/images/nikola.png
.  render_listings:output/listings/index.html
.  render_listings:output/listings/hello.py.html
.  render_listings:output/listings/hello.py
.  render_archive:output/2012/index.html
.  render_archive:output/archive.html
.  render_sources:output/stories/a-study-in-scarlet.txt
.  render_sources:output/stories/charts.txt
.  render_sources:output/stories/upgrading-to-v6.txt
.  render_sources:output/stories/social_buttons.txt
.  render_sources:output/stories/slides-demo.rst
.  render_sources:output/stories/listings-demo.rst
.  render_sources:output/stories/internals.txt
.  render_sources:output/stories/extending.txt
.  render_sources:output/stories/about-nikola.rst
.  render_sources:output/stories/bootstrap-demo.rst
.  render_sources:output/stories/quickref.rst
.  render_sources:output/stories/quickstart.rst
.  render_sources:output/stories/handbook.rst
.  render_sources:output/posts/welcome-to-nikola.rst
.  render_sources:output/stories/creating-a-theme.rst
.  render_sources:output/stories/theming.rst
.  render_tags:output/categories/index.html
.  render_tags:output/assets/js/tag_cloud_data.json
.  copy_assets:output/assets/css/docs.css
.  copy_assets:output/assets/css/bootstrap-theme.css
.  copy_assets:output/assets/css/bootstrap.css
.  copy_assets:output/assets/css/bootstrap.css.map
.  copy_assets:output/assets/css/theme.css
.  copy_assets:output/assets/css/rst.css
.  copy_assets:output/assets/css/bootstrap-theme.min.css
.  copy_assets:output/assets/css/bootstrap-theme.css.map
.  copy_assets:output/assets/css/bootstrap.min.css
.  copy_assets:output/assets/css/images/ie6/borderTopLeft.png
.  copy_assets:output/assets/css/images/ie6/borderTopCenter.png
.  copy_assets:output/assets/css/images/ie6/borderMiddleLeft.png
.  copy_assets:output/assets/css/images/ie6/borderMiddleRight.png
.  copy_assets:output/assets/css/images/ie6/borderBottomRight.png
.  copy_assets:output/assets/css/images/ie6/borderBottomLeft.png
.  copy_assets:output/assets/css/images/ie6/borderTopRight.png
.  copy_assets:output/assets/css/images/ie6/borderBottomCenter.png
.  copy_assets:output/assets/js/bootstrap.js
.  copy_assets:output/assets/js/bootstrap.min.js
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.eot
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.ttf
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.woff
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.svg
.  copy_assets:output/assets/css/bootstrap-responsive.min.css
.  copy_assets:output/assets/css/bootstrap-responsive.css
.  copy_assets:output/assets/css/colorbox.css
.  copy_assets:output/assets/css/images/controls.png
.  copy_assets:output/assets/css/images/loading.gif
.  copy_assets:output/assets/js/jquery.min.js
.  copy_assets:output/assets/js/flowr.plugin.js
.  copy_assets:output/assets/js/jquery.colorbox.js
.  copy_assets:output/assets/js/jquery.min.map
.  copy_assets:output/assets/js/jquery.colorbox-min.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-cs.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-de.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-si.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-ro.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-fr.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-he.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-lv.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-ar.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-pl.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-tr.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-sr.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-nl.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-ru.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-fa.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-zh-CN.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-kr.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-pt-br.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-gr.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-id.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-my.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-hu.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-uk.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-it.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-es.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-fi.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-zh-TW.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-sv.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-gl.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-et.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-ca.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-ja.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-hr.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-da.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-no.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-bg.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-sk.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-lt.js
.  copy_assets:output/assets/img/glyphicons-halflings.png
.  copy_assets:output/assets/img/glyphicons-halflings-white.png
.  copy_assets:output/assets/js/html5.js
.  copy_assets:output/assets/js/moment-with-locales.min.js
.  copy_assets:output/assets/js/mathjax.js
.  copy_assets:output/assets/js/fancydates.js
.  copy_assets:output/assets/xml/rss.xsl
.  copy_assets:output/assets/css/code.css
.  render_galleries:output/galleries
.  render_galleries:output/galleries/demo
.  render_galleries:output/galleries/index.html
.  render_galleries:output/galleries/rss.xml
.  render_galleries:output/galleries/demo/tesla4_lg.thumbnail.jpg
.  render_galleries:output/galleries/demo/tesla4_lg.jpg
.  render_galleries:output/galleries/demo/tesla_conducts_lg.thumbnail.jpg
.  render_galleries:output/galleries/demo/tesla_conducts_lg.jpg
.  render_galleries:output/galleries/demo/tesla_lightning1_lg.thumbnail.jpg
.  render_galleries:output/galleries/demo/tesla_lightning1_lg.jpg
.  render_galleries:output/galleries/demo/tesla_lightning2_lg.thumbnail.jpg
.  render_galleries:output/galleries/demo/tesla_lightning2_lg.jpg
.  render_galleries:output/galleries/demo/tesla_tower1_lg.thumbnail.jpg
.  render_galleries:output/galleries/demo/tesla_tower1_lg.jpg
.  render_galleries:cache/galleries/demo/index.html
.  render_galleries:output/galleries/demo/index.html
.  render_galleries:output/galleries/demo/rss.xml
.  render_posts:cache/stories/a-study-in-scarlet.html
.  render_posts:cache/stories/charts.html
[2015-02-08T19:34:43Z] WARNING: Nikola: In order to use the Chart directive, you must install the "pygal" Python package.
.  render_posts:cache/stories/upgrading-to-v6.html
.  render_posts:cache/stories/social_buttons.html
.  render_posts:cache/stories/slides-demo.html
.  render_posts:cache/stories/listings-demo.html
.  render_posts:cache/stories/internals.html
.  render_posts:cache/stories/extending.html
.  render_posts:cache/stories/1.html
.  render_posts:cache/stories/bootstrap-demo.html
.  render_posts:cache/stories/quickref.html
.  render_posts:cache/stories/quickstart.html
.  render_posts:cache/stories/manual.html
.  render_posts:cache/posts/1.html
.  render_posts:cache/stories/creating-a-theme.html
.  render_posts:cache/stories/theming.html
.  render_tags:output/categories/blog.html
.  render_indexes:output/index.html
.  render_tags:output/categories/demo.html
.  render_tags:output/categories/nikola.html
.  render_tags:output/categories/cat_nikola.html
.  render_tags:output/categories/python.html
.  render_tags:output/categories/cat_nikola.xml
.  render_tags:output/categories/nikola.xml
.  render_pages:output/stories/a-study-in-scarlet.html
.  render_pages:output/stories/charts.html
.  render_pages:output/stories/upgrading-to-v6.html
.  render_pages:output/stories/social_buttons.html
.  render_tags:output/categories/blog.xml
.  render_pages:output/stories/slides-demo.html
.  render_pages:output/stories/listings-demo.html
.  render_pages:output/stories/internals.html
.  render_pages:output/stories/extending.html
.  render_pages:output/stories/about-nikola.html
.  render_pages:output/stories/bootstrap-demo.html
.  render_pages:output/stories/quickref.html
.  render_pages:output/stories/quickstart.html
.  generate_rss:output/rss.xml
.  render_pages:output/stories/handbook.html
.  render_pages:output/posts/welcome-to-nikola.html
.  render_pages:output/stories/creating-a-theme.html
.  render_pages:output/stories/theming.html
.  render_tags:output/categories/demo.xml
.  render_tags:output/categories/python.xml
.  sitemap:output/sitemap.xml
.  sitemap:output/sitemapindex.xml
.  robots_file:output/robots.txt
(virt_env)cya@n411z:~/virt_env/bin/ntest$ 
```

**Comment by Kwpolska** [comment]
That’s all good.  This means there is an issue with the software you have on your system.  Try uninstalling and re-installing ipython and nikola.  I really don’t know what’s wrong here; maybe the issue lies somewhere else, maybe it’s your Nikola site…

**Comment by cemysf** [comment]
ok, thanks for help
