### ISSUE TITLE
fails with MemoryError on Windows 7 using Python 3.4 (Anaconda dist)

### ISSUE THREAD

**Issue by jboynyc** [getnikola/nikola#1642]
I just installed Nikola on Windows 7 using the Anaconda distribution (Python 3.4).

Trying to run `nikola` from the command prompt I get this traceback:

    > nikola
    Traceback (most recent call last):
      File "C:\Users\jboy1\Applications\Anaconda\lib\runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "C:\Users\jboy1\Applications\Anaconda\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Users\jboy1\Applications\Anaconda\Scripts\nikola.exe\__main__.py", line 5, in <module>
      File "C:\Users\jboy1\Applications\Anaconda\lib\site-packages\nikola\__init__.py", line 33, in <module>
        from .nikola import Nikola  # NOQA
      File "C:\Users\jboy1\Applications\Anaconda\lib\site-packages\nikola\nikola.py", line 56, in <module>
        from .post import Post
      File "C:\Users\jboy1\Applications\Anaconda\lib\site-packages\nikola\post.py", line 40, in <module>
        from . import utils
      File "C:\Users\jboy1\Applications\Anaconda\lib\site-packages\nikola\utils.py", line 46, in <module>
        import logbook
      File "C:\Users\jboy1\Applications\Anaconda\lib\site-packages\logbook\__init__.py", line 14, in <module>
        from logbook.base import LogRecord, Logger, LoggerGroup, NestedSetup, \
      File "C:\Users\jboy1\Applications\Anaconda\lib\site-packages\logbook\base.py", line 23, in <module>
        from logbook._speedups import group_reflected_property, \
    MemoryError

I tried the same in a Python 2.7 environment of the same Anaconda distribution, and that works fine. I can work in the Python 2 environment for the time being, but it would be nice to figure out why Py3 fails with the `MemoryError`.

**Comment by Kwpolska** [comment]
It doesn’t seem to be our fault… you should report the bug to the people behind [logbook](https://github.com/mitsuhiko/logbook) instead.

**Comment by jboynyc** [comment]
OK, will do!
