### ISSUE TITLE
post-list directive fails on a new site or after `nikola clean`

### ISSUE THREAD

**Issue by hiliev** [getnikola/nikola#1646]
The `post-lists` directive fails on a new site or after `nikola clean`. Steps to reproduce:

    $ nikola init --demo demo
    $ cd demo
    $ nikola new_page
    Title: Test
    $ echo -e "\n.. post-list::" >> stories/test.rst
    $ nikola build
    ...
    .  render_listings:output/listings/hello.py.html
    .  render_listings:output/listings/hello.py
    .  render_posts:cache/stories/test.html
    Traceback (most recent call last):
      File "/Users/hristo/.virtualenvs/nikola/lib/python2.7/site-packages/doit/doit_cmd.py", line 121, in run
        return command.parse_execute(args)
      File "/Users/hristo/.virtualenvs/nikola/lib/python2.7/site-packages/doit/cmd_base.py", line 84, in parse_execute
        return self.execute(params, args)
      File "/Users/hristo/.virtualenvs/nikola/lib/python2.7/site-packages/doit/cmd_base.py", line 278, in execute
        return self._execute(**exec_params)
      File "/Users/hristo/.virtualenvs/nikola/lib/python2.7/site-packages/doit/cmd_run.py", line 215, in _execute
        return runner.run_all(self.control.task_dispatcher())
      File "/Users/hristo/.virtualenvs/nikola/lib/python2.7/site-packages/doit/runner.py", line 237, in run_all
        self.run_tasks(task_dispatcher)
      File "/Users/hristo/.virtualenvs/nikola/lib/python2.7/site-packages/doit/runner.py", line 204, in run_tasks
        self.process_task_result(node, catched_excp)
      File "/Users/hristo/.virtualenvs/nikola/lib/python2.7/site-packages/doit/runner.py", line 175, in process_task_result
        self.dep_manager.save_success(task)
      File "/Users/hristo/.virtualenvs/nikola/lib/python2.7/site-packages/doit/dependency.py", line 413, in save_success
        timestamp = os.path.getmtime(dep)
      File "/Users/hristo/.virtualenvs/nikola/lib/python2.7/genericpath.py", line 54, in getmtime
        return os.stat(filename).st_mtime
    OSError: [Errno 2] No such file or directory: 'cache/posts/1.html'

At that point, the HTML fragment in `cache/stories/test.html` seems to be correctly generated:

    <p>Write your page here.</p>
     
    
    <div id="post_list_a4133869758a47c89ddb07e0f84266d8" class="post-list">
        <ul class="post-list">
               <li class="post-list-item">
                    2012-03-30 23:00
                    &nbsp;
                    <a href="/posts/welcome-to-nikola.html">Welcome to Nikola</a>
               </li>
        </ul>
    </div>
    

Running `nikola build` a second time completes without an error.

`nikola` version 7.3.1
`doit` version 0.27.0

**Comment by Kwpolska** [comment]
It’s recommended to set a date far in the past for your post lists and using stories to avoid issues like this.  Fixed in aa74b09 and documented in 76f05e2.

**Comment by hiliev** [comment]
I suspected that it could possibly be connected to the date and actually touched the story file with a way older date but totally forgot to update the time in the metadata.
