### ISSUE TITLE
SyntaxError in utils.py using Python3

### ISSUE THREAD

**Issue by kmdouglass** [getnikola/nikola#1659]
Hi all,
I'm receiving an error when I try to run Nikola from the command line (and likewise when I try to import nikola in the Python interpreter).

I installed Python 3.2 and python3-dev on my Debian Wheezy system with

```sh
sudo apt-get install python3 python3-dev
```

Next, I created a virtualenv using the python3.2 interpreter and installed Nikola 7.3.1 and its dependencies with the following pip command:

```sh
pip install nikola
```

The installation proceeded without errors. However, I get the following error when I run the `niklola` command from within the virtualenv:

```sh
(nikola)kmdouglass@kmd-laptop1:~/src/kmdouglass.github.io$ nikola
Traceback (most recent call last):
  File "/home/kmdouglass/envs/nikola/bin/nikola", line 7, in <module>
    from nikola.__main__ import main
  File "/home/kmdouglass/envs/nikola/lib/python3.2/site-packages/nikola/__init__.py", line 33, in <module>
    from .nikola import Nikola  # NOQA
  File "/home/kmdouglass/envs/nikola/lib/python3.2/site-packages/nikola/nikola.py", line 56, in <module>
    from .post import Post
  File "/home/kmdouglass/envs/nikola/lib/python3.2/site-packages/nikola/post.py", line 40, in <module>
    from . import utils
  File "/home/kmdouglass/envs/nikola/lib/python3.2/site-packages/nikola/utils.py", line 115
    format_string=u'[{record.time:%Y-%m-%dT%H:%M:%SZ}] {record.level_name}: {record.channel}: {record.message}'
                                                                                                              ^
SyntaxError: invalid syntax
```

I don't immediately see what the syntax error is. Any ideas?

Here's my pip freeze output:

```sh
(nikola)kmdouglass@kmd-laptop1:~/src/kmdouglass.github.io$ pip freeze
blinker==1.3
docutils==0.12
doit==0.27.0
Logbook==0.9.0
lxml==3.4.3
Mako==1.0.1
natsort==3.5.6
Nikola==7.3.1
Pillow==2.8.1
Pygments==2.0.2
pyinotify==0.9.5
PyRSS2Gen==1.1
python-dateutil==2.4.1
six==1.9.0
Unidecode==0.4.17
Yapsy==1.11.23
```

Thanks!

**Comment by Kwpolska** [comment]
Nikola requires Python 3.3 or newer.

The SyntaxError comes from Python 3.2 not supporting the `u''` syntax for strings.
