### ISSUE TITLE
nikola new_post -f pandoc crashes

### ISSUE THREAD

**Issue by msx** [getnikola/nikola#1675]
Hi,
As per #1445 I tried to use pandoc (installed on my system, Fedora 21 up-to-date) but got this error trace:
```
~> nikola new_post -f pandoc
Traceback (most recent call last):
  File "/home/@msx/.virtualenvs/nikola2/lib/python2.7/site-packages/doit/doit_cmd.py", line 121, in run
    return command.parse_execute(args)
  File "/home/@msx/.virtualenvs/nikola2/lib/python2.7/site-packages/doit/cmd_base.py", line 84, in parse_execute
    return self.execute(params, args)
  File "/home/@msx/.virtualenvs/nikola2/lib/python2.7/site-packages/nikola/plugin_categories.py", line 105, in execute
    self._execute(options, args)
  File "/home/@msx/.virtualenvs/nikola2/lib/python2.7/site-packages/nikola/plugins/command/new_post.py", line 282, in _execute
    self.site.config['post_pages'])
  File "/home/@msx/.virtualenvs/nikola2/lib/python2.7/site-packages/nikola/plugins/command/new_post.py", line 56, in filter_post_pages
    raise Exception('Unknown format {0}'.format(compiler))
Exception: Unknown format pandoc
```

**Comment by Kwpolska** [comment]
how is your `POSTS` and `COMPILERS` set?

**Comment by msx** [comment]
Untouched:

```
POSTS = (
    ("posts/*.rst", "posts", "post.tmpl"),
    ("posts/*.txt", "posts", "post.tmpl"),
)
```
```
COMPILERS = {
    "rest": ('.rst', '.txt'),
    "markdown": ('.md', '.mdown', '.markdown'),
    "textile": ('.textile',),
    "txt2tags": ('.t2t',),
    "bbcode": ('.bb',),
    "wiki": ('.wiki',),
    "ipynb": ('.ipynb',),
    "html": ('.html', '.htm'),
    # PHP files are rendered the usual way (i.e. with the full templates).
    # The resulting files have .php extensions, making it possible to run
    # them without reconfiguring your server to recognize them
    "php": ('.php',),
    # Pandoc detects the input from the source filename
    # but is disabled by default as it would conflict
    # with many of the others
    # "pandoc": ('.rst', '.md', '.txt'),
}
```

**Comment by Kwpolska** [comment]
In order to use Pandoc for Markdown compiling, you must:

1. Add an entry to POSTS (you want it as the topmost entry): `("posts/*.md", "posts", "post.tmpl"),`
2. Comment the line with the `"markdown"` compiler
3. Uncomment the `"pandoc"` line and remove the reST extensions — make it `"pandoc": ('.md',),` (don’t forget the two commas!)
