### ISSUE TITLE
serve -a [::] (IPv6)

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1682]
nikola serve -a [::] or any other  IPv6 address

    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/doit/doit_cmd.py", line 165, in run
        return command.parse_execute(args)
      File "/usr/local/lib/python3.4/dist-packages/doit/cmd_base.py", line 122, in parse_execute
        return self.execute(params, args)
      File "/usr/local/lib/python3.4/dist-packages/nikola/plugin_categories.py", line 110, in execute
        self._execute(options, args)
      File "/usr/local/lib/python3.4/dist-packages/nikola/plugins/command/serve.py", line 85, in _execute
        OurHTTPRequestHandler)
      File "/usr/lib/python3.4/socketserver.py", line 430, in __init__
        self.server_bind()
      File "/usr/lib/python3.4/http/server.py", line 136, in server_bind
        socketserver.TCPServer.server_bind(self)
      File "/usr/lib/python3.4/socketserver.py", line 444, in server_bind
        self.socket.bind(self.server_address)
    socket.gaierror: [Errno -2] Name or service not known

Use case: was trying to bind to my public IPv6 address to show a friend something off from my laptop.

**Comment by ralsina** [comment]
I have no idea how to bind to IPv6 addresses there... -a just takes a string and passes it along :-)

**Comment by Kwpolska** [comment]
We would need to detect the desired address family and use a special class. https://gist.github.com/akorobov/7903307 says we can do it in 2 lines + family detection.

**Comment by Kwpolska** [comment]
done, we should also look if we can do something with auto

**Comment by Aeyoun** [comment]
Thanks. I’ll use this the next time I’m showing off an early draft built on my laptop. ;)
