### ISSUE TITLE
github_deploy failed

### ISSUE THREAD

**Issue by yakiang** [getnikola/nikola#1713]
Scanning posts....done!
    Traceback (most recent call last):
      File "/Users/yakiang/Code/nikola-blog/venv/lib/python2.7/site-packages/doit/doit_cmd.py", line 165, in run
        return command.parse_execute(args)
      File "/Users/yakiang/Code/nikola-blog/venv/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
        return self.execute(params, args)
      File "/Users/yakiang/Code/nikola-blog/venv/lib/python2.7/site-packages/nikola/plugin_categories.py", line 114, in execute
        self._execute(options, args)
      File "/Users/yakiang/Code/nikola-blog/venv/lib/python2.7/site-packages/nikola/plugins/command/github_deploy.py", line 87, in _execute
        only_on_output, _ = real_scan_files(self.site)
    TypeError: real_scan_files() takes exactly 2 arguments (1 given)

I created a blog and ran `git init` , `git remote add origin 'git@github.com:yakiang/yakiang.github.io.git'`, followed by `nikola github_deploy`, only to meet such errors :-(

**Comment by Kwpolska** [comment]
Sorry for the inconvenience, we introduced some backwards-incompatible changes in the code and we did not manage to find every call to that function.
