### ISSUE TITLE
[ INSTALLED: 7.4.1 (latest) ] Broken?

### ISSUE THREAD

**Issue by msx** [getnikola/nikola#1725]
Hello all, I just installed Nikola via pip using virtualfish to create a virtualenv, got this trace error:
```
nikola | /h/@/P/g/msx.github.io ‹master*›> nikola build; nikola deploy; nikola github_deploy                                                                                                                                                                        [5/98]
Scanning posts....done!
.  render_tags:output/en/categories/index.html
.  render_listings:output/listings/index.html
.  render_listings:output/listings/hello.py.html
.  copy_assets:output/assets/js/moment-with-locales.min.js
.  copy_assets:output/assets/js/html5.js
.  copy_assets:output/assets/js/fancydates.js
.  copy_assets:output/assets/js/mathjax.js
.  copy_assets:output/assets/xml/rss.xsl
.  copy_assets:output/assets/xml/atom.xsl
.  copy_assets:output/assets/css/rst.css
.  copy_assets:output/assets/css/theme.css
.  render_archive:output/en/2015/index.html
.  render_archive:output/en/archive.html
.  render_indexes:output/en/index.html
.  render_galleries:output/en/galleries/index.html
.  render_galleries:output/en/galleries/rss.xml
.  render_galleries:output/en/galleries/demo/index.html
.  render_galleries:output/en/galleries/demo/rss.xml
.  render_pages:output/en/stories/a-study-in-scarlet.html
.  render_pages:output/en/stories/quickstart.html
.  render_pages:output/en/stories/theming.html
.  render_pages:output/en/stories/charts.html
.  render_pages:output/en/stories/about-nikola.html
.  render_pages:output/en/stories/upgrading-to-v6.html
.  render_pages:output/en/stories/quickref.html
.  render_pages:output/en/stories/social_buttons.html
.  render_pages:output/en/stories/extending.html
.  render_pages:output/en/stories/slides-demo.html
.  render_pages:output/en/stories/creating-a-theme.html
.  render_pages:output/en/stories/listings-demo.html
.  render_pages:output/en/stories/internals.html
.  render_pages:output/en/stories/handbook.html
.  render_pages:output/en/posts/on-air.html
.  render_pages:output/en/stories/bootstrap-demo.html
.  sitemap:output/sitemap.xml
Traceback (most recent call last):
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/doit_cmd.py", line 165, in run
    return command.parse_execute(args)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/cmd_base.py", line 405, in execute
    return self._execute(**exec_params)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/cmd_run.py", line 239, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/runner.py", line 238, in run_all
    self.run_tasks(task_dispatcher)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/runner.py", line 205, in run_tasks
    self.process_task_result(node, catched_excp)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/runner.py", line 176, in process_task_result
    self.dep_manager.save_success(task)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/dependency.py", line 484, in save_success
    state = self.checker.get_state(dep, self._get(task.name, dep))
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/dependency.py", line 403, in get_state
    timestamp = os.path.getmtime(dep)
  File "/home/@msx/.virtualenvs/nikola/lib64/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: 'output/msx.github.com/en/stories/quickref.html'
Scanning posts....done!
[2015-05-16T06:56:26Z] INFO: deploy: => preset 'default'
[2015-05-16T06:56:26Z] INFO: deploy: Successful deployment
Scanning posts....done!
########################################
DependencyError - taskid:sitemap:output/sitemap.xml
ERROR: Task 'sitemap:output/sitemap.xml' checking dependencies
Traceback (most recent call last):
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/runner.py", line 125, in select_task
    node.run_status = self.dep_manager.get_status(task, tasks_dict)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/dependency.py", line 629, in get_status
    .format(dep))
DependencyException: Dependent file 'output/msx.github.com/en/stories/quickref.html' does not exist.


[2015-05-16T06:56:28Z] ERROR: github_deploy: Build failed, not deploying to GitHub
```
**doit** is already install through pip too.

**Comment by Kwpolska** [comment]
Post your conf.py?  It sounds as if you did not specify a protocol (`http` or `https`) in your SITE_URL.

**Comment by msx** [comment]
You _almost_ nailed it :D 
After adding **http:/** to SITE_URL I still have this:
```
nikola | /h/@/P/g/msx.github.io ‹master*›> nikola build; nikola deploy; nikola github_deploy
Scanning posts....done!
.  render_tags:output/en/categories/index.html
.  render_listings:output/listings/index.html
.  render_listings:output/listings/hello.py.html
.  render_archive:output/en/2015/index.html
.  render_archive:output/en/archive.html
.  render_indexes:output/en/index.html
.  render_galleries:output/en/galleries
.  render_galleries:output/en/galleries/demo
.  render_galleries:output/en/galleries/index.html
.  render_galleries:output/en/galleries/rss.xml
.  render_galleries:cache/galleries/demo/index.html
.  render_galleries:output/en/galleries/demo/index.html
.  render_galleries:output/en/galleries/demo/rss.xml
.  render_pages:output/en/posts/on-air.html
.  render_pages:output/en/stories/handbook.html
.  render_pages:output/en/stories/a-study-in-scarlet.html
.  render_pages:output/en/stories/extending.html
.  generate_rss:output/en/rss.xml
.  render_pages:output/en/stories/charts.html
.  render_pages:output/en/stories/quickstart.html
.  render_pages:output/en/stories/upgrading-to-v6.html
.  render_pages:output/en/stories/internals.html
.  render_pages:output/en/stories/social_buttons.html
.  render_pages:output/en/stories/quickref.html
.  render_pages:output/en/stories/slides-demo.html
.  render_pages:output/en/stories/bootstrap-demo.html
.  render_pages:output/en/stories/listings-demo.html
.  render_pages:output/en/stories/theming.html
.  render_pages:output/en/stories/creating-a-theme.html
.  render_pages:output/en/stories/about-nikola.html
.  sitemap:output/sitemap.xml
.  sitemap:output/sitemapindex.xml
.  robots_file:output/robots.txt
Scanning posts....done!
[2015-05-16T07:08:37Z] INFO: deploy: => preset 'default'
[2015-05-16T07:08:37Z] INFO: deploy: Successful deployment
Scanning posts....done!
Traceback (most recent call last):
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/doit_cmd.py", line 165, in run
    return command.parse_execute(args)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/nikola/plugin_categories.py", line 114, in execute
    self._execute(options, args)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/nikola/plugins/command/github_deploy.py", line 87, in _execute
    only_on_output, _ = real_scan_files(self.site)
TypeError: real_scan_files() takes exactly 2 arguments (1 given)
```
Check my conf.py here please: http://pastebin.com/z2mSn9PC

**Comment by Kwpolska** [comment]
At which point we get to issue #1713, which was fixed in commit https://github.com/getnikola/nikola/commit/e78294e7ee2afe2141f430552a8f67a7063a033b.  You can just edit your copy of Nikola with this little change and make it work.

**Comment by Kwpolska** [comment]
PS. 
> ```py
BLOG_EMAIL = "<archlinux.us: msx>"
```

you are creating invalid links right now.  Edit `CONTENT_FOOTER` and `CONTENT_FOOTER_FORMATS` not to show the address.

**Comment by msx** [comment]
Thank you!
