### ISSUE TITLE
Galleries are broken if no translation ends up in site root

### ISSUE THREAD

**Issue by msx** [getnikola/nikola#1726]
Yep, me again :P
Does this make sense to you?
```
nikola | /h/@/P/g/msx.github.io ‹master*›> nikola build; nikola deploy; nikola github_deploy
Scanning posts....done!
.  render_galleries:output/en/galleries/demo/index.html
########################################
TaskError - taskid:render_galleries:output/en/galleries/demo/index.html
PythonAction Error
Traceback (most recent call last):
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/action.py", line 372, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/nikola/plugins/task/galleries.py", line 533, in render_gallery_index
    im = Image.open(thumb)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/PIL/Image.py", line 2248, in open
    fp = builtins.open(fp, "rb")
IOError: [Errno 2] No such file or directory: u'output/galleries/demo/tesla4_lg.thumbnail.jpg'



Scanning posts....done!
[2015-05-16T07:25:21Z] INFO: deploy: => preset 'default'
[2015-05-16T07:25:21Z] INFO: deploy: Successful deployment
Scanning posts....done!
.  render_galleries:output/en/galleries/demo/index.html
########################################
TaskError - taskid:render_galleries:output/en/galleries/demo/index.html
PythonAction Error
Traceback (most recent call last):
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/doit/action.py", line 372, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/nikola/plugins/task/galleries.py", line 533, in render_gallery_index
    im = Image.open(thumb)
  File "/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/PIL/Image.py", line 2248, in open
    fp = builtins.open(fp, "rb")
IOError: [Errno 2] No such file or directory: u'output/galleries/demo/tesla4_lg.thumbnail.jpg'



[2015-05-16T07:25:23Z] ERROR: github_deploy: Build failed, not deploying to GitHub
```

Following your advice I edited _/home/@msx/.virtualenvs/nikola/lib/python2.7/site-packages/nikola/plugins/command/github_deploy.py_ to match the fix:
```
        # Clean non-target files
        # only_on_output, _ = real_scan_files(self.site)
        l = self._doitargs['cmds'].get_plugin('list')(config=self.config, **self._doitargs)
        only_on_output, _ = real_scan_files(l, self.site)
        for f in only_on_output:
            os.unlink(f)
```

**Comment by Kwpolska** [comment]
This is the problem:

```py
TRANSLATIONS = {
    DEFAULT_LANG: "en",
                   ^^
```

We expect at least one translation to end up in the site root — that is, an empty string as one of the values in `TRANSLATIONS`.  In order not to duplicate files, they end up in `DEFAULT_LANG`’s site; however, while resizing them, we don’t use `DEFAULT_LANG` to build the path.  Should not be hard to fix; in the meantime, you may want to make that an empty string — especially if you do not want any translations.

Also: why do you use `nikola deploy`?  It currently does nothing — you did not configure any `DEPLOY_COMMANDS`.

@ralsina, should we work further on making this scenario feasible or not?  There are probably other things that depend on this.  Some people might not want to pick a “default” language and instead put a language picker on the site root.

**Comment by msx** [comment]
Yes, I thought about ```DEFAULT_LANG``` and was about to post back but you did it first :)
About ```nikola deploy```, I'm just learning my way around Nikola, thanks for the heads up.
Cheers.
