### ISSUE TITLE
Latest Yapsy seems to break Nikola

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1730]
With Yapsy==1.11.023

```
(nikola)ralsina@yoga:~/Desktop/proyectos/nikola/master/foo$ nikola auto
Traceback (most recent call last):
  File "/home/ralsina/.virtualenvs/nikola/bin/nikola", line 9, in <module>
    load_entry_point('Nikola==7.4.1', 'console_scripts', 'nikola')()
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/__main__.py", line 152, in main
    site = Nikola(**config)
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/nikola.py", line 692, in __init__
    self.plugin_manager.collectPlugins()
  File "/home/ralsina/.virtualenvs/nikola/local/lib/python2.7/site-packages/yapsy/PluginManager.py", line 539, in collectPlugins
    self.locatePlugins()
  File "/home/ralsina/.virtualenvs/nikola/local/lib/python2.7/site-packages/yapsy/PluginManager.py", line 442, in locatePlugins
    self._candidates, npc = self.getPluginLocator().locatePlugins()
  File "/home/ralsina/.virtualenvs/nikola/local/lib/python2.7/site-packages/yapsy/PluginFileLocator.py", line 432, in locatePlugins
    plugin_info = self._getInfoForPluginFromAnalyzer(analyzer, dirpath, filename)
  File "/home/ralsina/.virtualenvs/nikola/local/lib/python2.7/site-packages/yapsy/PluginFileLocator.py", line 386, in _getInfoForPluginFromAnalyzer
    plugin_info_dict,config_parser = analyzer.getInfosDictFromPlugin(dirpath, filename)
  File "/home/ralsina/.virtualenvs/nikola/local/lib/python2.7/site-packages/yapsy/PluginFileLocator.py", line 266, in getInfosDictFromPlugin
    raise ValueError("Missing *name* of the plugin in extracted infos.")
ValueError: Missing *name* of the plugin in extracted infos.
```

**Comment by ralsina** [comment]
Seems to me the problem is that if the filename is unicode, things fail in Yapsy's ``_extractCorePluginInfo`` function.

**Comment by ralsina** [comment]
Reported in Yapsy as http://sourceforge.net/p/yapsy/bugs/31/ and ping @tibonihoo  :-)

**Comment by tibonihoo** [comment]
Hello,

I answered on sourceforge but I see the missing info is here (version of yapsy).

Actually this problem is already fixed in yapsy 1.11.123 where the faulty line in your stack reads isinstance(filename, basestring) instead of isinstance(filename,str).

**Comment by ralsina** [comment]
Ok, I'll update the requirements.

**Comment by ralsina** [comment]
Setting the requirement to 1.11.123 fails, setting it to 1.11.123b succeeds, but the internal version of the package is 1.11.123 (without the b) so it will try to upgrade every time.

**Comment by tibonihoo** [comment]
Oh my, there was a problem with pypi refusing me to replace the archive for 1.11.123 and I naively thought that chaning just the name of the archive file would be enough... apparently not...

**Comment by ralsina** [comment]
I had the same problem, it seems it's intentional because having the same version download different files at different times is "bad" :-)

**Comment by tibonihoo** [comment]
hmm great, so I have to do another minor release of yapsy to fix that

**Comment by Kwpolska** [comment]
PS. whenever you go for a next major release (v1.12), you should call it v1.12.0 and drop the `23` suffix (which also confuses pip a little)

**Comment by tibonihoo** [comment]
Sorry for the long wait  :/

**Comment by Kwpolska** [comment]
hey, at least it works now, no need to be sorry!
