### ISSUE TITLE
Nikola traceback

### ISSUE THREAD

**Issue by esc** [getnikola/nikola#1748]
I am running ``nikola build`` and I am expecting the site to be built. Instead, I receive the following traceback

```
Traceback (most recent call last):
  File "/home/blosc/py34/bin/nikola", line 11, in <module>
    sys.exit(main())
  File "/home/blosc/py34/lib/python3.4/site-packages/nikola/__main__.py", line 150, in main
    DN = DoitNikola(site, quiet)
  File "/home/blosc/py34/lib/python3.4/site-packages/nikola/__main__.py", line 268, in __init__
    super(DoitNikola, self).__init__()
  File "/home/blosc/py34/lib/python3.4/site-packages/doit/doit_cmd.py", line 45, in __init__
    self.task_loader = task_loader if task_loader else self.TASK_LOADER()
TypeError: __init__() missing 1 required positional argument: 'nikola'
```

**Comment by Kwpolska** [comment]
You must be running an ancient version of Nikola (`bin/nikola` does not look like that since April 2014).  Please upgrade to `Nikola==7.4.1`, that should fix it.

**Comment by esc** [comment]
```
$ pip show nikola
---
Name: Nikola
Version: 7.4.1
Location: /home/blosc/py34/lib/python3.4/site-packages
Requires: lxml, natsort, docutils, python-dateutil, blinker, Pillow, Pygments, PyRSS2Gen, yapsy, logbook, mako, doit, setuptools, unidecode
```

**Comment by felixfontein** [comment]
Can you do `pip show doit` as well?

**Comment by esc** [comment]
```
---
Name: doit
Version: 0.25.0
Location: /home/blosc/py34/lib/python3.4/site-packages
Requires: six, pyinotify
```

**Comment by felixfontein** [comment]
In that case, you have a modern Nikola version and an out-dated doit version :-) Nikola 7.4.1 requires doit 0.28.0, since there were some non-backwards-compatible changes from 0.27.x to 0.28.0.

**Comment by esc** [comment]
I upgraded ``doit`` now I get:

```
Scanning posts.Traceback (most recent call last):
  File "/home/blosc/py34/lib/python3.4/site-packages/doit/doit_cmd.py", line 165, in run
    return command.parse_execute(args)
  File "/home/blosc/py34/lib/python3.4/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/blosc/py34/lib/python3.4/site-packages/doit/cmd_base.py", line 380, in execute
    self, params, args)
  File "/home/blosc/py34/lib/python3.4/site-packages/nikola/__main__.py", line 254, in load_tasks
    self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
  File "/home/blosc/py34/lib/python3.4/site-packages/doit/loader.py", line 296, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/blosc/py34/lib/python3.4/site-packages/doit/loader.py", line 28, in flat_generator
    for item in gen:
  File "/home/blosc/py34/lib/python3.4/site-packages/nikola/nikola.py", line 1331, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/home/blosc/py34/lib/python3.4/site-packages/nikola/nikola.py", line 1325, in flatten
    for t in task:
  File "/home/blosc/py34/lib/python3.4/site-packages/nikola/plugins/task/sources.py", line 55, in gen_tasks
    self.site.scan_posts()
  File "/home/blosc/py34/lib/python3.4/site-packages/nikola/nikola.py", line 1421, in scan_posts
    self.get_compiler(base_path)
  File "/home/blosc/py34/lib/python3.4/site-packages/nikola/post.py", line 199, in __init__
    alg=natsort.ns.F | natsort.ns.IC)
AttributeError: 'module' object has no attribute 'ns'
```

**Comment by felixfontein** [comment]
Could you do `pip show natsort`? (Nikolas requirement, specified in `requirements.txt`, is at least 3.5.2, but then, for doit it also required 0.28.0 and that wasn't there...)

**Comment by esc** [comment]
Cool, thanks for your help by the way:

Now I get:

```
[2015-05-23T12:31:16Z] WARNING: Nikola: WRITE_TAG_CLOUD is not set in your config.  Defaulting to True (== writing tag_cloud_data.json).
[2015-05-23T12:31:16Z] WARNING: Nikola: Please explicitly add the setting to your conf.py with the desired value, as the setting will default to False in the future.
Scanning posts....done!
ERROR: Task generation 'render_site' has duplicated definition of 'render_sources:output/blog/compress-me-stupid.rst'
```

**Comment by felixfontein** [comment]
I've never had that error so far. Does your blog has more than one language?

**Comment by esc** [comment]
I don't think so.

**Comment by esc** [comment]
The repo for the blog is here, if you want to try for yourself:

https://github.com/Blosc/website

**Comment by felixfontein** [comment]
The slug for both `posts/compress-me-stupid.rst` and `posts/seeking-sponsorship.rst` is the same, namely `compress-me-stupid`. This causes the problem.
(And yes, the error message isn't really helping to find that.)

**Comment by esc** [comment]
Excellent! Thanks 1000x.
