### ISSUE TITLE
Trouble with nikola github_deploy

### ISSUE THREAD

**Issue by dataholiks** [getnikola/nikola#1793]
Hi I've been playing with Nikola all afternoon and it was fairly easy to set up! I am having trouble with github_deploy. I am using nikola v7.4.1

I initalized an empty repo dataholiks/dataholiks.github.io

The full conf.py file is in the repo.

I am familiar with the basics of git (git add, git commit etc...), but I must be doing something silly. After successfuly adding a README and the conf.py file to the repo, I know have a master branch. I then did the following

git checkout -b deploy # now on deploy branch
nikola github_deploy

I got the following error message

Scanning posts........done!
Traceback (most recent call last):
  File "/home/demba/Documents/blogging/nikola/lib/python2.7/site-packages/doit/doit_cmd.py", line 165, in run
    return command.parse_execute(args)
  File "/home/demba/Documents/blogging/nikola/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/demba/Documents/blogging/nikola/lib/python2.7/site-packages/nikola/plugin_categories.py", line 114, in execute
    self._execute(options, args)
  File "/home/demba/Documents/blogging/nikola/lib/python2.7/site-packages/nikola/plugins/command/github_deploy.py", line 87, in _execute
    only_on_output, _ = real_scan_files(self.site)
TypeError: real_scan_files() takes exactly 2 arguments (1 given)

Any help would be appreciate! Thanks.

**Comment by Kwpolska** [comment]
Known issue, sorry. Please upgrade to master branch or wait for v7.5.0.

**Comment by dataholiks** [comment]
Thx for the prompt reply.
