### ISSUE TITLE
Failed building Markdown Pages

### ISSUE THREAD

**Issue by ctoth** [getnikola/nikola#1799]
I created a new Python 2.7 Virtualenv on Windows 7 and installed Nikola.
I edited my conf.py, only changing one thing, the PAGES declaration, which now reads:
```python

PAGES = (
    ("stories/*.rst", "stories", "story.tmpl"),
    ("stories/*.md", "stories", "story.tmpl"),
    ("stories/*.txt", "stories", "story.tmpl"),
)
```

I created a new page:
nikola new_page -f markdown -e
Wrote some text, and then decided to glance at the generated output.
I issued nikola build
```

(env) C:\Users\Q\code\nvdaremote.com>nikola build
Scanning posts.....done!
.  render_posts:timeline_changes
.  render_posts:cache\stories\download.html
########################################
TaskError - taskid:render_posts:cache\stories\download.html
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\Q\code\nvdaremote.com\env\lib\site-packages\doit\action.py", line 372, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "C:\Users\Q\code\nvdaremote.com\env\lib\site-packages\nikola\post.py", line 468, in compile
    self.is_two_file),
  File "C:\Users\Q\code\nvdaremote.com\env\lib\site-packages\nikola\plugins\compile\markdown\__init__.py", line 80, in compile_html
    output = markdown(data, self.extensions)
  File "C:\Users\Q\code\nvdaremote.com\env\lib\site-packages\markdown\__init__.py", line 493, in markdown
    md = Markdown(*args, **kwargs)
  File "C:\Users\Q\code\nvdaremote.com\env\lib\site-packages\markdown\__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "C:\Users\Q\code\nvdaremote.com\env\lib\site-packages\markdown\__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "C:\Users\Q\code\nvdaremote.com\env\lib\site-packages\markdown\__init__.py", line 264, in build_extension
    module = importlib.import_module(module_name_old_style)
  File "c:\python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: Failed loading extension 'extras' from 'extras', 'markdown.extensions.extras' or 'mdx_extras'

```

**Comment by ctoth** [comment]
In the default conf.py, I see:
```
MARKDOWN_EXTENSIONS = ['fenced_code', 'codehilite', 'extras']
```
Though the comment just above this one says that Fenced Code and codehilite are the only ones enabled by default.

There does appear to be a markdown extension as part of the default Python Markdown package called extra. If I switch extras to extra in the MARKDOWN_EXTENSIONS list, all appears to work.

It appears as though this needs to be fixed in the default conf.py template.

**Comment by ralsina** [comment]
Actually, the default (if you comment out that line) **is** fenced_code and codehilite :-)

We will change the default in version 8, but we enabled (wrongly!) extra for new sites because it's 
more compatible with other software.
