### ISSUE TITLE
Python3 incompatibility

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1802]
Reported in IRC by barthalion. When using [his files](https://github.com/Barthalion/barthalion.github.com/tree/source/posts/556) with python3 I get this error:

```
TaskError - taskid:render_indexes:output/index.html
PythonAction Error
Traceback (most recent call last):
  File "/home/ralsina/.virtualenvs/nikola3/lib/python3.4/site-packages/doit-0.28.0-py3.4.egg/doit/action.py", line 372, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/nikola.py", line 983, in render_template
    doc.rewrite_links(lambda dst: self.url_replacer(src, dst, context['lang']))
  File "/home/ralsina/.virtualenvs/nikola3/lib/python3.4/site-packages/lxml-3.4.4-py3.4-linux-x86_64.egg/lxml/html/__init__.py", line 483, in rewrite_links
    new_link = link_repl_func(link.strip())
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/nikola.py", line 983, in <lambda>
    doc.rewrite_links(lambda dst: self.url_replacer(src, dst, context['lang']))
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/nikola.py", line 1034, in url_replacer
    dst_url.fragment))
  File "/usr/lib/python3.4/urllib/parse.py", line 393, in urlunsplit
    _coerce_args(*components))
  File "/usr/lib/python3.4/urllib/parse.py", line 109, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

**Comment by ralsina** [comment]
Closed in https://github.com/getnikola/nikola/commit/0cb13bbe2d9b328bfdc0b622c600a38055c37605
