### ISSUE TITLE
Something broke in base-jinja

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1813]
```
TaskError - taskid:render_archive:/home/ralsina/Desktop/proyectos/nikola/nikola-themes/output/v7/base-jinja/archive.html
PythonAction Error
Traceback (most recent call last):
  File "/home/ralsina/.virtualenvs/nikola/local/lib/python2.7/site-packages/doit-0.28.0-py2.7.egg/doit/action.py", line 372, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/nikola.py", line 968, in render_template
    template_name, None, local_context)
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/plugins/template/jinja.py", line 90, in render_template
    output = template.render(**context)
  File "/home/ralsina/.virtualenvs/nikola/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ralsina/.virtualenvs/nikola/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/base-jinja/templates/list.tmpl", line 2, in top-level template code
    {% extends 'base.tmpl' %}
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/base-jinja/templates/base.tmpl", line 16, in top-level template code
    {{ header.html_header() }}
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/base-jinja/templates/base_header.tmpl", line 8, in template
    {{ html_navigation_links() }}
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/data/themes/base-jinja/templates/base_header.tmpl", line 47, in template
    <li class="active"><a href="{{ permalink }}">{{ text }} <span class="sr-only">{{ messages("(active)", langname) }}</span></a></li>
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/utils.py", line 241, in __call__
    return self[lang][key]
KeyError: '(active)'
```

**Comment by Kwpolska** [comment]
I forgot to jinjify in c1d84a98e4821d228c2f8d0bf612e73bb03ab3a5, fixed
