### ISSUE TITLE
"nikola auto" breaks on Python 3 in 7.5.1 (was good in 7.5.0)

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#1830]
To reproduce, run nikola using Python 3:

    nikola auto

Visit http://localhost:8000, "A server error occurred.  Please contact the administrator." is displayed in browser, and the following message is displayed in the terminal:

    Traceback (most recent call last):
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
        self.result = application(self.environ, self.start_response)
      File "/home/user/.local/lib/python3.4/site-packages/nikola/plugins/command/auto/__init__.py", line 188, in __call__
        return parent.serve_static(environ, start_response)
      File "/home/user/.local/lib/python3.4/site-packages/nikola/plugins/command/auto/__init__.py", line 243, in serve_static
        start_response(b'200 OK', [(b'Content-type', mimetype)])
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 226, in start_response
        self.headers = self.headers_class(headers)
      File "/usr/lib/python3.4/wsgiref/headers.py", line 38, in __init__
        self._convert_string_type(k)
      File "/usr/lib/python3.4/wsgiref/headers.py", line 46, in _convert_string_type
        " of type str (got {0})".format(repr(value)))
    AssertionError: Header names/values must be of type str (got b'Content-type')
        
"auto" command works well in Python 2.

I've bisected the regression. The culprit is commit aec80b4522a33c63f58946a78692a022e60e8b22

**Comment by ralsina** [comment]
This looks like a bug in ws4py, I may have a workaround later today when I can spend some time debugging it.

**Comment by xuhdev** [comment]
any good news?

**Comment by ralsina** [comment]
@xuhdev not yet. This is a complicated bug, and I am having a rough month at work (as in: lots and lots of work). I am going to be at a sprint next week, so I *could* be antisocial and do some late night coding. We'll see :-)

**Comment by xuhdev** [comment]
No problem, no need to hurry :)

**Comment by xuhdev** [comment]
I don't think this is completely fixed, as it still sometimes prints the following message if you browse the website a bit

```
INFO:ws4py:Terminating websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:39226]
Traceback (most recent call last):
  File "/home/hong/.local/lib/python3.4/site-packages/ws4py/server/wsgirefserver.py", line 71, in finish_response
    SimpleHandler.finish_response(self)
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 181, in finish_response
    self.finish_content()
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 310, in finish_content
    self.send_headers()
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 453, in _write
    self.stdout.write(data)
  File "/usr/lib/python3.4/socket.py", line 391, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/hong/.local/lib/python3.4/site-packages/ws4py/server/wsgirefserver.py", line 74, in finish_response
    ws.close(1011, reason='Something broke')
  File "/home/hong/.local/lib/python3.4/site-packages/ws4py/websocket.py", line 176, in close
    self._write(self.stream.close(code=code, reason=reason).single(mask=self.stream.always_mask))
  File "/home/hong/.local/lib/python3.4/site-packages/ws4py/websocket.py", line 243, in _write
    self.sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by ralsina** [comment]
I *think* those are harmless. I could make them go silent, tho.

**Comment by ChillarAnand** [comment]
The main problem is, after the error happens, nikola won't detect/send new changes even if page is manually refreshed in browser. `nikola auto` has to restarted to make it work. This becomes annoying when error keeps occurring twice a minute.
