### ISSUE TITLE
"nikola auto" kicks up "no such file or directory" when files change

### ISSUE THREAD

**Issue by willkg** [getnikola/nikola#1852]
I'm using nikola v7.5.1 installed from pypi.

When I run "nikola auto":

```
<nikola> (M=ddeb6 posts/ fixpost.py) saturn2 ~/projects/blog2> nikola auto
[2015-07-01T19:13:22Z] WARNING: Nikola: In order to USE_BUNDLES, you must install the "webassets" Python package.
[2015-07-01T19:13:22Z] WARNING: bundles: Setting USE_BUNDLES to False.
[2015-07-01T19:13:23Z] WARNING: Nikola: In order to USE_BUNDLES, you must install the "webassets" Python package.
[2015-07-01T19:13:23Z] WARNING: bundles: Setting USE_BUNDLES to False.
Scanning posts....done!
.  render_sources:output/mozilla/ditching_elasticutils.rst
.  render_posts:timeline_changes
.  render_posts:cache/posts/mozilla/ditching_elasticutils.html
[2015-07-01T19:13:29Z] NOTICE: Nikola: posts/mozilla/ditching_elasticutils.rst is scheduled to be published in the future (2015-07-01 16:20:00-04:00)
.  render_pages:output/mozilla/ditching_elasticutils.html
INFO:ws4py:Using epoll
[2015-07-01T19:13:35Z] INFO: auto: Serving HTTP on 127.0.0.1 port 8000...
INFO:ws4py:Managing websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:51311]
[2015-07-01T19:13:36Z] INFO: auto: <--- {u'snipver': 1, u'ver': u'2.2.1', u'command': u'hello', u'protocols': [u'http://livereload.com/protocols/official-6', u'http://livereload.com/protocols/official-7']}
[2015-07-01T19:13:36Z] INFO: auto: ---> {"serverName": "nikola-livereload", "command": "hello", "protocols": ["http://livereload.com/protocols/official-7"]}
[2015-07-01T19:13:36Z] INFO: auto: <--- {u'url': u'http://0.0.0.0:8000/mozilla/ditching_elasticutils.html', u'command': u'info', u'plugins': {u'less': {u'disable': False, u'version': u'1.0'}}}
[2015-07-01T19:13:36Z] INFO: auto: ****** Browser connected: http://0.0.0.0:8000/mozilla/ditching_elasticutils.html
[2015-07-01T19:13:36Z] INFO: auto: ****** sending 0 pending messages
INFO:ws4py:Terminating websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:51311]
INFO:ws4py:Managing websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:51327]
[2015-07-01T19:14:59Z] INFO: auto: <--- {u'snipver': 1, u'ver': u'2.2.1', u'command': u'hello', u'protocols': [u'http://livereload.com/protocols/official-6', u'http://livereload.com/protocols/official-7']}
[2015-07-01T19:14:59Z] INFO: auto: ---> {"serverName": "nikola-livereload", "command": "hello", "protocols": ["http://livereload.com/protocols/official-7"]}
[2015-07-01T19:14:59Z] INFO: auto: <--- {u'url': u'http://0.0.0.0:8000/mozilla/ditching_elasticutils.html', u'command': u'info', u'plugins': {u'less': {u'disable': False, u'version': u'1.0'}}}
[2015-07-01T19:14:59Z] INFO: auto: ****** Browser connected: http://0.0.0.0:8000/mozilla/ditching_elasticutils.html
[2015-07-01T19:14:59Z] INFO: auto: ****** sending 0 pending messages

['build']
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/home/willkg/.virtualenvs/nikola/lib/python2.7/site-packages/pyinotify.py", line 1505, in run
    self.loop()
  File "/home/willkg/.virtualenvs/nikola/lib/python2.7/site-packages/pyinotify.py", line 1491, in loop
    self.process_events()
  File "/home/willkg/.virtualenvs/nikola/lib/python2.7/site-packages/pyinotify.py", line 1287, in process_events
    self._default_proc_fun(revent)
  File "/home/willkg/.virtualenvs/nikola/lib/python2.7/site-packages/nikola/plugins/command/auto/__init__.py", line 218, in do_rebuild
    p = subprocess.Popen(self.cmd_arguments, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Most of that output is fine, except the last bit. That happens when I go edit one of my blog posts.

I think it's a problem with this line:

https://github.com/getnikola/nikola/blob/master/nikola/plugins/command/auto/__init__.py#L221

where it should be something like this:
```
 p = subprocess.Popen(['nikola'] + self.cmd_arguments, stderr=subprocess.PIPE)
```

since `self.cmd_arguments` at this point is just `['build']`.

**Comment by willkg** [comment]
If the above is correct, I can put together a PR. Let me know.

**Comment by ralsina** [comment]
I *think* @Kwpolska  fixed it in master already... https://github.com/getnikola/nikola/blob/master/nikola/plugins/command/auto/__init__.py#L129

**Comment by willkg** [comment]
That looks very likely. I'll grab master tip and see if it's still not working.

**Comment by willkg** [comment]
That fixes that issue for me. Closing this out. Thank you!
