### ISSUE TITLE
Error in wordpress importer

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1857]
I am getting this in a VPS:

```
$ nikola --version
ERROR:yapsy:Unable to import plugin: /var/coil/local/lib/python2.7/site-packages/nikola/plugins/command/import_wordpress
Traceback (most recent call last):
  File "/var/coil/local/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/var/coil/local/lib/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 56, in <module>
    class CommandImportWordpress(Command, ImportMixin):
  File "/var/coil/local/lib/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 362, in CommandImportWordpress
    code_re1 = re.compile(r'\[code.* lang.*?="(.*?)?".*\](.*?)\[/code\]', re.DOTALL | re.MULTILINE)
  File "/var/coil/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/var/coil/lib/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
error: nothing to repeat
Nikola v7.6.0
```

That is with python 2.7.3, doesn't seem to happen with 2.7.9 (sigh)

**Comment by Kwpolska** [comment]
This is most likely a bug in 2.7.3’s regex parser that we can’t fix.

**Comment by ralsina** [comment]
Maybe it's possible to rewrite the regexp differently and avoid the bug. Or not.

**Comment by cbrown1** [comment]
I get this error with Python 2.7.5. It occurs when I try to install a plugin or a theme. EG:

$ nikola install_theme bootstrap3
ERROR:yapsy:Unable to import plugin: /usr/lib64/python2.7/site-packages/nikola/plugins/command/import_wordpress
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 56, in <module>
    class CommandImportWordpress(Command, ImportMixin):
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 329, in CommandImportWordpress
    code_re1 = re.compile(r'\[code.* lang.*?="(.*?)?".*\](.*?)\[/code\]', re.DOTALL | re.MULTILINE)
  File "/usr/lib64/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
error: nothing to repeat
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): themes.getnikola.com
[2015-07-03T15:14:29Z] WARNING: InsecurePlatformWarning: /usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/doit/doit_cmd.py", line 165, in run
    return command.parse_execute(args)
  File "/usr/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/usr/lib64/python2.7/site-packages/nikola/plugin_categories.py", line 125, in execute
    self._execute(options, args)
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/install_theme.py", line 117, in _execute
    data = requests.get(url).text
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
$

**Comment by Kwpolska** [comment]
Those are two separate issues, and the second is also caused by outdated Python.

Maybe we should recommend Python 3 more?

**Comment by cbrown1** [comment]
Yes, installing python3.4 fixed the problem.

**Comment by ralsina** [comment]
Closing as "not our problem"
