### ISSUE TITLE
[plugins][command][init] unrecognized character during creation procedure

### ISSUE THREAD

**Issue by Mec-iS** [getnikola/nikola#1901]
System:
Win 8.1 with Python 3.3.5

I have installed the package with:
       `pip install nikola requests markdown webassets ipython[notebook]`
Everything went right during installation.

When I tried to initialize with:
    `nikola init blogname`
I got this error:
```pytb
Site URL [https://example.com/]:
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\doit\doit_cmd.py", line 165, in run
    return command.parse_execute(args)
  File "C:\Python33\lib\site-packages\doit\cmd_base.py", line 122, in parse_exec
ute
    return self.execute(params, args)
  File "C:\Python33\lib\site-packages\nikola\plugin_categories.py", line 125, in
 execute
    return self._execute(options, args)
  File "C:\Python33\lib\site-packages\nikola\plugins\command\init.py", line 473,
 in _execute
    st = self.ask_questions(target=target)
  File "C:\Python33\lib\site-packages\nikola\plugins\command\init.py", line 446,
 in ask_questions
    query(default, toconf)
  File "C:\Python33\lib\site-packages\nikola\plugins\command\init.py", line 307,
 in prettyhandler
    SAMPLE_CONF['PRETTY_URLS'] = ask_yesno('Enable pretty URLs (/page/ instead o
f /page.html) that don\u2019t need web server configuration?', default=True)
  File "C:\Python33\lib\site-packages\nikola\utils.py", line 1285, in ask_yesno
    inp = raw_input("{query}{default_q} ".format(query=query, default_q=default_
q)).strip()
  File "C:\Python33\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position
58: character maps to <undefined>
```

I corrected the problem by substituting the incorrect char in `C:\Python33\lib\site-packages\nikola\plugins\command\init.py", line 307` with `\'` (escaped apos).

**Comment by Kwpolska** [comment]
Ahh, the joys of `cmd.exe`. I tried to be too fancy, but I didn’t think about Windows. Thanks for the report!
