### ISSUE TITLE
"nikola serve -d" assumes availability of os.fork(), fails with traceback in Windows

### ISSUE THREAD

**Issue by richieadler** [getnikola/nikola#1913]
Running on Windows 7
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32

nikola serve -d
Traceback (most recent call last):
  File "C:\Prog\Python27\lib\site-packages\doit\doit_cmd.py", line 165, in run
    return command.parse_execute(args)
  File "C:\Prog\Python27\lib\site-packages\doit\cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "C:\Prog\Python27\lib\site-packages\nikola\plugin_categories.py", line 125, in execute
    return self._execute(options, args)
  File "C:\Prog\Python27\lib\site-packages\nikola\plugins\command\serve.py", line 130, in _execute
    pid = os.fork()
AttributeError: 'module' object has no attribute 'fork'

**Comment by Kwpolska** [comment]
There is no easy way to make it work on Windows. Made it run in the foreground with a warning.
