### ISSUE TITLE
WordPress image import ValueErrors

### ISSUE THREAD

**Issue by abkfenris** [getnikola/nikola#1917]
When I try to import a WordPress site, it's throwing ValueErrors trying to coerce some of the image attributes to ints. 

For example, when it is trying to import
![Sheepscot-1](http://alexkerney.com/wp-content/uploads/2010/10/Sheepscot-1.jpg)
When it tries to convert the shutter speed of 0.0025 to an int it throws an error and stops.

```python
[2015-07-30T10:35:36Z] INFO: import_wordpress: Downloading http://alexkerney.com/wp-content/uploads/2010/10/Sheepscot-1.jpg => new_site/files/wp-content/uploads/2010/10/Sheepscot-1.jpg
[2015-07-30T10:35:36Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): alexkerney.com
Traceback (most recent call last):
  File "/Users/kerneya/virtualenvs/regular-nikola/lib/python3.4/site-packages/doit/doit_cmd.py", line 165, in run
    return command.parse_execute(args)
  File "/Users/kerneya/virtualenvs/regular-nikola/lib/python3.4/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/Users/kerneya/virtualenvs/regular-nikola/lib/python3.4/site-packages/nikola/plugin_categories.py", line 127, in execute
    return self._execute(options, args)
  File "/Users/kerneya/virtualenvs/regular-nikola/lib/python3.4/site-packages/nikola/plugins/command/import_wordpress.py", line 325, in _execute
    self.import_posts(channel)
  File "/Users/kerneya/virtualenvs/regular-nikola/lib/python3.4/site-packages/nikola/plugins/command/import_wordpress.py", line 968, in import_posts
    self.process_item_if_attachment(item)
  File "/Users/kerneya/virtualenvs/regular-nikola/lib/python3.4/site-packages/nikola/plugins/command/import_wordpress.py", line 931, in process_item_if_attachment
    data = self.import_attachment(item, wordpress_namespace)
  File "/Users/kerneya/virtualenvs/regular-nikola/lib/python3.4/site-packages/nikola/plugins/command/import_wordpress.py", line 533, in import_attachment
    add('shutter_speed', b'shutter_speed', is_int=True, ignore_zero=True)
  File "/Users/kerneya/virtualenvs/regular-nikola/lib/python3.4/site-packages/nikola/plugins/command/import_wordpress.py", line 516, in add
    value = int(value)
ValueError: invalid literal for int() with base 10: b'0.0025'
```

Here is the image_meta from the WordPress XML.

```php
s:10:"image_meta";a:10:{
s:8:"aperture";s:2:"13";
s:6:"credit";s:0:"";
s:6:"camera";s:9:"NIKON D90";
s:7:"caption";s:0:"";
s:17:"created_timestamp";s:10:"1281720288";
s:9:"copyright";s:0:"";
s:12:"focal_length";s:2:"18";
s:3:"iso";s:3:"200";
s:13:"shutter_speed";s:6:"0.0025";
s:5:"title";s:0:"";}
```

And the whole item.

```xml
	<item>
		<title>Sheepscot (1)</title>
		<link>http://alexkerney.com/2010/10/apple-juice/sheepscot-1/</link>
		<pubDate>Tue, 28 Dec 2010 17:45:48 +0000</pubDate>
		<dc:creator><![CDATA[kerneya]]></dc:creator>
		<guid isPermaLink="false">http://alexkerney.com/wp-content/uploads/2010/10/Sheepscot-1.jpg</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>107</wp:post_id>
		<wp:post_date>2010-12-28 17:45:48</wp:post_date>
		<wp:post_date_gmt>2010-12-28 17:45:48</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>open</wp:ping_status>
		<wp:post_name>sheepscot-1</wp:post_name>
		<wp:status>inherit</wp:status>
		<wp:post_parent>16</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>attachment</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:attachment_url>http://alexkerney.com/wp-content/uploads/2010/10/Sheepscot-1.jpg</wp:attachment_url>
		<wp:postmeta>
			<wp:meta_key>_wp_attached_file</wp:meta_key>
			<wp:meta_value><![CDATA[2010/10/Sheepscot-1.jpg]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_metadata</wp:meta_key>
			<wp:meta_value><![CDATA[a:6:{s:5:"width";s:3:"800";s:6:"height";s:3:"450";s:14:"hwstring_small";s:23:"height='72' width='128'";s:4:"file";s:23:"2010/10/Sheepscot-1.jpg";s:5:"sizes";a:6:{s:9:"thumbnail";a:3:{s:4:"file";s:23:"Sheepscot-1-188x188.jpg";s:5:"width";s:3:"188";s:6:"height";s:3:"188";}s:6:"medium";a:3:{s:4:"file";s:23:"Sheepscot-1-288x162.jpg";s:5:"width";s:3:"288";s:6:"height";s:3:"162";}s:5:"large";a:3:{s:4:"file";s:23:"Sheepscot-1-494x277.jpg";s:5:"width";s:3:"494";s:6:"height";s:3:"277";}s:14:"post-thumbnail";a:3:{s:4:"file";s:23:"Sheepscot-1-188x188.jpg";s:5:"width";s:3:"188";s:6:"height";s:3:"188";}s:17:"archive-thumbnail";a:3:{s:4:"file";s:23:"Sheepscot-1-188x188.jpg";s:5:"width";s:3:"188";s:6:"height";s:3:"188";}s:20:"front-page-thumbnail";a:3:{s:4:"file";s:23:"Sheepscot-1-800x300.jpg";s:5:"width";s:3:"800";s:6:"height";s:3:"300";}}s:10:"image_meta";a:10:{s:8:"aperture";s:2:"13";s:6:"credit";s:0:"";s:6:"camera";s:9:"NIKON D90";s:7:"caption";s:0:"";s:17:"created_timestamp";s:10:"1281720288";s:9:"copyright";s:0:"";s:12:"focal_length";s:2:"18";s:3:"iso";s:3:"200";s:13:"shutter_speed";s:6:"0.0025";s:5:"title";s:0:"";}}]]></wp:meta_value>
		</wp:postmeta>
	</item>
```

I'm also finding errors when trying to coerce aperture, focal, length, and iso values to int.

**Comment by ralsina** [comment]
@abkfenris Thanks for the detailed bug report, hope it will work now!

The change is really small, you could apply it to your copy of Nikola or just use github's master.

**Comment by ralsina** [comment]
Oops wrong fix, good one coming up.

**Comment by abkfenris** [comment]
It gets through my images if I also give aperture, focal_length, and iso `is_float=True`. 

Now to figure out what's going on thats causing my WordPress import to hang up at another spot.

**Comment by Kwpolska** [comment]
I made everything floats right now.
