### ISSUE TITLE
ws4py not include in pip install

### ISSUE THREAD

**Issue by phaustin** [getnikola/nikola#1941]
I just pip installed nikola v7.6.3 using anaconda python 3.4 on osx64 and hit the following:

(test)~ phil@rail% nikola --help
[2015-08-14T23:06:53Z] ERROR: yapsy: Unable to import plugin: /Users/phil/an2015/anaconda/envs/test/lib/python3.4/site-packages/nikola/plugins/command/auto
Traceback (most recent call last):
  File "/Users/phil/an2015/anaconda/envs/test/lib/python3.4/site-packages/yapsy/PluginManager.py", line 485, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/Users/phil/an2015/anaconda/envs/test/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/Users/phil/an2015/anaconda/envs/test/lib/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec

The failure is due to a missing install of ws4py, fix is:

pip install ws4py

**Comment by ralsina** [comment]
This is already fixed in master (see https://github.com/getnikola/nikola/pull/1935). I'll do a release on monday with the fix.
