### ISSUE TITLE
7.6.3 crashes with Unicode error

### ISSUE THREAD

**Issue by bnmnetp** [getnikola/nikola#1948]
Everything was building fine with 7.5.1 so I upgraded to 7.6.3 today.  Now I get the following:

```
TaskError - taskid:_scan_locs:sitemap
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/nikola/plugins/task/sitemap/__init__.py", line 257, in scan_locs_task
    scan_locs()
  File "/usr/local/lib/python3.4/dist-packages/nikola/plugins/task/sitemap/__init__.py", line 191, in scan_locs
    lowquothead = filehead.lower().decode('utf-8').replace('"', '').encode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 1023: unexpected end of data
```
Running under python 3.4.0 on Ubuntu 14.04

**Comment by Kwpolska** [comment]
Does commit 4d859e0 fix it for you?

**Comment by muxuezi** [comment]
Yes, [4d859e0](https://github.com/getnikola/nikola/commit/4d859e026597ae1deee64681b5160fefd6962add) is ok, there is no error of sitemap any more.
