### ISSUE TITLE
wordpress_import fails with UnicodeEncodeError every once in a while.

### ISSUE THREAD

**Issue by orsenthil** [getnikola/nikola#2006]
```
[2015-09-03T07:10:16Z] INFO: import_wordpress: Downloading https://xtoinf.files.wordpress.com/2015/05/wpid-img_20150525_1117522-jpg.jpeg => new_site/files/2015/05/wpid-img_20150525_1117522-jpg.jpeg
[2015-09-03T07:10:16Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): xtoinf.files.wordpress.com
Traceback (most recent call last):
  File "/Users/skumaran/.pyenv/versions/nikola/lib/python2.7/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/Users/skumaran/.pyenv/versions/nikola/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/Users/skumaran/.pyenv/versions/nikola/lib/python2.7/site-packages/nikola/plugin_categories.py", line 127, in execute
    return self._execute(options, args)
  File "/Users/skumaran/.pyenv/versions/nikola/lib/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 325, in _execute
    self.import_posts(channel)
  File "/Users/skumaran/.pyenv/versions/nikola/lib/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 975, in import_posts
    self.process_item_if_post_or_page(item)
  File "/Users/skumaran/.pyenv/versions/nikola/lib/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 956, in process_item_if_post_or_page
    out_folder_slug = self.import_postpage_item(item, wordpress_namespace, 'posts', attachments)
  File "/Users/skumaran/.pyenv/versions/nikola/lib/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 763, in import_postpage_item
    path = path.decode('utf8')
  File "/Users/skumaran/.pyenv/versions/nikola/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 47-49: ordinal not in range(128)
```

This is when downloading files. I do not see any non ascii encoding the file.

**Comment by jjconti** [comment]
I think this is fixed in master.

**Comment by orsenthil** [comment]
This is fixed in master. I verified it.

**Comment by ralsina** [comment]
Yay!
