### ISSUE TITLE
import_wordpress: UnicodeEncodeError when writing non-ASCII headers for comments

### ISSUE THREAD

**Issue by evgeni** [getnikola/nikola#2019]
Hi,

playing around with the new comments importer I stumbled over the following bug: my dump contains the following line:

    <wp:comment_author><![CDATA[Stéphane]]></wp:comment_author>

Running `nikola import_wordpress --export-comments` results in the following traceback:

    Traceback (most recent call last):
      File "/path/lib/python2.7/site-packages/doit/doit_cmd.py", line 168, in run
        return command.parse_execute(args)
      File "/path/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
        return self.execute(params, args)
      File "/path/lib/python2.7/site-packages/nikola/plugin_categories.py", line 127, in execute
        return self._execute(options, args)
      File "/path/lib/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 325, in _execute
        self.import_posts(channel)
      File "/path/lib/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 982, in import_posts
        self.process_item_if_post_or_page(item)
      File "/path/lib/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 963, in process_item_if_post_or_page
        out_folder_slug = self.import_postpage_item(item, wordpress_namespace, 'posts', attachments)
      File "/path/lib/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 916, in import_postpage_item
        self._write_comment(os.path.join(self.output_folder, out_folder, comment_filename), comment)
      File "/path/lib/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 722, in _write_comment
        write_header_line(fd, "author", comment["author"])
      File "/path/lib/python2.7/site-packages/nikola/plugins/command/import_wordpress.py", line 714, in write_header_line
        header_content = str(header_content).replace('\n', ' ')
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)

**Comment by Kwpolska** [comment]
Does the patch in #2020 fix this for you?

**Comment by evgeni** [comment]
Hi @Kwpolska,

yes, the patch solves the issue for me, thanks!
