### ISSUE TITLE
Nikola 7.7.1 crashes unable to import ipynb plugin

### ISSUE THREAD

**Issue by profedrini** [getnikola/nikola#2089]
Even checking the version (not building) causes a crash 

```bash
drini@hunabku ~ $ cd git/euler
drini@hunabku ~/git/euler $ source bin/activate
(euler)drini@hunabku ~/git/euler $ pip install --upgrade "Nikola[extras]"
Requirement already up-to-date: Nikola[extras] in ./lib/python3.4/site-packages
Requirement already up-to-date: blinker>=1.3 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: doit>=0.28.0 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: setuptools>=5.4.1 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: requests>=2.2.0 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: natsort>=3.5.2 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: PyRSS2Gen>=1.1 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: Pillow>=2.4.0 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: Pygments>=1.6 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: lxml>=3.3.5 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: python-dateutil==2.4.2 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: Yapsy>=1.11.223 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: docutils>=0.12 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: mako>=1.0.0 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: unidecode>=0.04.16 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: logbook>=0.7.0 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: husl>=4.0.2 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: phpserialize>=1.3 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: micawber>=0.3.0 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: Jinja2>=2.7.2 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: watchdog==0.8.3 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: ws4py==0.3.4 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: pyphen>=0.9.1 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: typogrify>=2.0.4 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: webassets>=0.10.1 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: Markdown>=2.4.0 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: pygal==2.0.6 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: ghp-import>=0.4.1 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: ipython[notebook]>=2.0.0 in ./lib/python3.4/site-packages (from Nikola[extras])
Requirement already up-to-date: six in ./lib/python3.4/site-packages (from doit>=0.28.0->Nikola[extras])
Requirement already up-to-date: cloudpickle in ./lib/python3.4/site-packages (from doit>=0.28.0->Nikola[extras])
Requirement already up-to-date: pyinotify in ./lib/python3.4/site-packages (from doit>=0.28.0->Nikola[extras])
Requirement already up-to-date: MarkupSafe>=0.9.2 in ./lib/python3.4/site-packages (from mako>=1.0.0->Nikola[extras])
Requirement already up-to-date: PyYAML>=3.10 in ./lib/python3.4/site-packages (from watchdog==0.8.3->Nikola[extras])
Requirement already up-to-date: argh>=0.24.1 in ./lib/python3.4/site-packages (from watchdog==0.8.3->Nikola[extras])
Requirement already up-to-date: pathtools>=0.1.1 in ./lib/python3.4/site-packages (from watchdog==0.8.3->Nikola[extras])
Requirement already up-to-date: smartypants>=1.8.3 in ./lib/python3.4/site-packages (from typogrify>=2.0.4->Nikola[extras])
Requirement already up-to-date: pickleshare in ./lib/python3.4/site-packages (from ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: pexpect in ./lib/python3.4/site-packages (from ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: simplegeneric>0.8 in ./lib/python3.4/site-packages (from ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: decorator in ./lib/python3.4/site-packages (from ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: traitlets in ./lib/python3.4/site-packages (from ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: notebook in ./lib/python3.4/site-packages (from ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: path.py in ./lib/python3.4/site-packages (from pickleshare->ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: ipython-genutils in ./lib/python3.4/site-packages (from traitlets->ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: nbconvert in ./lib/python3.4/site-packages (from notebook->ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: jupyter-client in ./lib/python3.4/site-packages (from notebook->ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: nbformat in ./lib/python3.4/site-packages (from notebook->ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: ipykernel in ./lib/python3.4/site-packages (from notebook->ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: terminado>=0.3.3 in ./lib/python3.4/site-packages (from notebook->ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: tornado>=4 in ./lib/python3.4/site-packages (from notebook->ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: jupyter-core in ./lib/python3.4/site-packages (from notebook->ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: mistune!=0.6 in ./lib/python3.4/site-packages (from nbconvert->notebook->ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: pyzmq>=13 in ./lib/python3.4/site-packages (from jupyter-client->notebook->ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: jsonschema!=2.5.0,>=2.0 in ./lib/python3.4/site-packages (from nbformat->notebook->ipython[notebook]>=2.0.0->Nikola[extras])
Requirement already up-to-date: ptyprocess in ./lib/python3.4/site-packages (from terminado>=0.3.3->notebook->ipython[notebook]>=2.0.0->Nikola[extras])


(euler)drini@hunabku ~/git/euler $ nikola --version
[2015-09-15T21:12:40Z] ERROR: yapsy: Unable to import plugin: /home/drini/git/euler/lib/python3.4/site-packages/nikola/plugins/compile/ipynb
Traceback (most recent call last):
  File "/home/drini/git/euler/lib/python3.4/site-packages/yapsy/PluginManager.py", line 485, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/home/drini/git/euler/lib64/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/home/drini/git/euler/lib64/python3.4/imp.py", line 210, in load_package
    raise ValueError('{!r} is not a package'.format(path))
ValueError: '/home/drini/git/euler/lib/python3.4/site-packages/nikola/plugins/compile/ipynb/__init__.py/__init__.pyc' is not a package
Nikola v7.7.1
```

**Comment by profedrini** [comment]
(euler)drini@hunabku ~/git/euler $ python --version
Python 3.4.1
(euler)drini@hunabku ~/git/euler $ jupyter --version
4.0.4

**Comment by Kwpolska** [comment]
Try removing

/home/drini/git/euler/lib/python3.4/site-packages/nikola/plugins/compile/ipynb

and try again. You might need to reinstall.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by profedrini** [comment]
No...  http://pastebin.com/k7u4NyUy

I even removed all nikola and reinstalled

The key seems to be here:
```
ValueError: '/home/drini/git/euler/lib/python3.4/site-packages/nikola/plugins/compile/ipynb/__init__.py/__init__.pyc' is not a package
```

that filename does not exist

**Comment by ralsina** [comment]
@profedrini what happened?

**Comment by profedrini** [comment]
Somehow the contents of  $VIRTUALENV/lib/python3.4/site-packages/nikola/plugins/compile/ipynb   was causing python to crash (python 3.4.1 here).  I deleted it as suggested, and the crash vanished
