### ISSUE TITLE
Translatable DATE_FORMAT breaks post-list directive

### ISSUE THREAD

**Issue by onnodb** [getnikola/nikola#2104]
The implementation of #2032 in Nikola 7.7.1 seems to break the `post-list` directive in RST pages.

If using a `post-list` in an RST page:

    .. post-list::
        :start: -5

a build fails with the following strack trace:

```
Traceback (most recent call last):
  File ".../nikola/lib/python2.7/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File ".../nikola/lib/python2.7/site-packages/nikola/post.py", line 485, in compile
    self.is_two_file),
[...]
  File ".../nikola/lib/python2.7/site-packages/nikola/post.py", line 330, in formatted_date
    return utils.LocaleBorg().formatted_date(date_format, date if date else self.date)
  File ".../nikola/lib/python2.7/site-packages/nikola/utils.py", line 1203, in formatted_date
    if date_format == 'webiso':
  File ".../nikola/lib/python2.7/site-packages/nikola/utils.py", line 436, in __eq__
    return self.values == other.values
AttributeError: 'unicode' object has no attribute 'values'
```

Line 1203 of `utils.py` seems to be the culprit, but I'm not sure how to fix this.

**Comment by onnodb** [comment]
The following diff fixes the problem, but I'm not quite sure if this is the right way to do it:

```
diff --git a/utils.py b/utils.py
index 6aa3151..36d5826 100644
--- a/utils.py
+++ b/utils.py
@@ -1200,12 +1200,12 @@ class LocaleBorg(object):
                     break
             # If no handler was able to format the date, ask Python
             if fmt_date is None:
-                if date_format == 'webiso':
+                if str(date_format) == 'webiso':
                     # Formatted after RFC 3339 (web ISO 8501 profile) with Zulu
                     # zone desgignator for times in UTC and no microsecond precision.
                     fmt_date = date.replace(microsecond=0).isoformat().replace('+00:00', 'Z')
                 else:
-                    fmt_date = date.strftime(date_format)
+                    fmt_date = date.strftime(str(date_format))

             # Issue #383, this changes from py2 to py3
             if isinstance(fmt_date, bytes_str):
```

**Comment by felixfontein** [comment]
Could you please show what `[...]` in the stack trace is? I think that's where the real bug is, because someone feeds a wrong `date_format` to `Post.formatted_date`.

**Comment by Kwpolska** [comment]
It is, and I think I got a fix.

**Comment by felixfontein** [comment]
The bug's here: https://github.com/getnikola/nikola/blob/master/nikola/plugins/compile/rest/post_list.py#L207

**Comment by onnodb** [comment]
That's blazingly fast, thanks a lot!

**Comment by Kwpolska** [comment]
(It was apparently added there because post-list runs outside of the global templating context.)
