### ISSUE TITLE
Nikola seems unable to load its config (OSX, anaconda)

### ISSUE THREAD

**Issue by jere19** [getnikola/nikola#2131]
I've been playing with nikola a bit, and I like it. I'm currently running v7.7.1 on python 2.7.10
However today i tried to add a new post and ran into a TypeError : 
```
Traceback (most recent call last):
  File "/Users/jlaforet/anaconda/bin/nikola", line 11, in <module>
    sys.exit(main())
  File "/Users/jlaforet/anaconda/lib/python2.7/site-packages/nikola/__main__.py", line 168, in main
    DN = DoitNikola(site, quiet)
  File "/Users/jlaforet/anaconda/lib/python2.7/site-packages/nikola/__main__.py", line 301, in __init__
    super(DoitNikola, self).__init__()
  File "/Users/jlaforet/anaconda/lib/python2.7/site-packages/doit/doit_cmd.py", line 59, in __init__
    ini_config = self.load_config_ini(config_filenames)
  File "/Users/jlaforet/anaconda/lib/python2.7/site-packages/doit/doit_cmd.py", line 72, in load_config_ini
    cfg_parser = ConfigParser(allow_no_value=True, delimiters=('=',))
TypeError: __init__() got an unexpected keyword argument 'delimiters'
```

It seems to be a Python2 vs Python3 issue: ConfigParser takes only `allow_no_value=` as keyword argument in Python2.7

**Comment by Kwpolska** [comment]
That’s not Nikola’s config, that’s doit’s.

Two solutions:

1. `pip install configparser` to use the backported veresion
2. Use Python 3.x to use Nikola, as Python 2.7 is DEPRECATED by us since last week (https://getnikola.com/blog/env-survey-results-and-the-future-of-python-27.html)
