### ISSUE TITLE
FreeBSD locale handling differs from linux locale handling

### ISSUE THREAD

**Issue by Wayneoween** [getnikola/nikola#2137]
When setting the language in `conf.py` on FreeBSD the locale is not extracted correctly and falls back to ascii from utf8 which breaks at least some plugin loading.

```python
[2015-10-07T18:13:19Z] WARNING: Nikola: Could not guess locale for language de, using locale C
[2015-10-07T18:13:20Z] ERROR: yapsy: Unable to import plugin: /usr/home/wayne/nikola/blog.cle.ar.it/plugins/ping/ping
Traceback (most recent call last):
  File "/usr/home/wayne/nikola/lib/python3.5/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/local/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/local/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "<frozen importlib._bootstrap_external>", line 763, in get_code
  File "/usr/local/lib/python3.5/imp.py", line 156, in get_data
    return file.read()
  File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 37: ordinal not in range(128)
```

The wrong behaviour can be seen here:

```python
Python 3.5.0 (default, Oct  3 2015, 10:40:38)
[GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
>>> import nikola
>>> import locale
>>> nikola.nikola.guess_locale_from_lang_posix('en')
>>> nikola.nikola.guess_locale_from_lang_posix('en_US.UTF-8')
'en_US.UTF-8'
>>> nikola.nikola.guess_locale_from_lang_posix('de_DE.UTF-8')
'de_DE.UTF-8'
>>> locale.normalize('de')
'de_DE.ISO8859-1'
````

A workaround is to explicitly set the locale in `conf.py` instead of letting nikola try to guess from the `lang`.
```python
# conf.py
LOCALE_DEFAULT = "en_US.UTF-8"
```

Thanks @Kwpolska and @ralsina for helping to debug.

Output of `locale.locale_alias`:
```python
>>> locale.locale_alias
{'gv_gb': 'gv_GB.ISO8859-1', 'yi': 'yi_US.CP1255', 'nso_za': 'nso_ZA.ISO8859-15', 'ny': 'ny_NO.ISO8859-1', 'is_is': 'is_IS.ISO8859-1', 'tr_cy': 'tr_CY.ISO8859-9', 'xh': 'xh_ZA.ISO8859-1', 'th': 'th_TH.ISO8859-11', 'vi_vn.tcvn': 'vi_VN.TCVN', 'en_ca': 'en_CA.ISO8859-1', 'ta': 'ta_IN.TSCII-0', 'tg_tj': 'tg_TJ.KOI8-C', 'mr_in': 'mr_IN.UTF-8', 'de_be': 'de_BE.ISO8859-1', 'slovak': 'sk_SK.ISO8859-2', 'italian': 'it_IT.ISO8859-1', 'nr': 'nr_ZA.ISO8859-1', 'kn_in': 'kn_IN.UTF-8', 'iso-8859-1': 'en_US.ISO8859-1', 'bokmal': 'nb_NO.ISO8859-1', 'iw': 'he_IL.ISO8859-8', 'en_us@euro@euro': 'en_US.ISO8859-15', 'sr_yu.iso88595@cyrillic': 'sr_CS.ISO8859-5', 'en_nz': 'en_NZ.ISO8859-1', 'iw_il.utf8': 'iw_IL.UTF-8', 'ar': 'ar_AA.ISO8859-6', 'fi': 'fi_FI.ISO8859-15', 'kok_in': 'kok_IN.UTF-8', 'in': 'id_ID.ISO8859-1', 'kw_gb': 'kw_GB.ISO8859-1', 'ti_et': 'ti_ET.UTF-8', 'ja_jp.euc': 'ja_JP.eucJP', 'eo_us.utf8': 'eo_US.UTF-8', 'spanish_spain': 'es_ES.ISO8859-1', 'cy': 'cy_GB.ISO8859-1', 'es_ni': 'es_NI.ISO8859-1', 'pap_an': 'pap_AN.UTF-8', 'pd': 'pd_US.ISO8859-1', 'english_united-states': 'en_US.ISO8859-1', 'posix': 'C', 'ka_ge.georgianps': 'ka_GE.GEORGIAN-PS', 'sk_sk': 'sk_SK.ISO8859-2', 'it': 'it_IT.ISO8859-1', 'spanish': 'es_ES.ISO8859-1', 'mai': 'mai_IN.UTF-8', 'ps_af': 'ps_AF.UTF-8', 'mni_in': 'mni_IN.UTF-8', 'st_za': 'st_ZA.ISO8859-1', 'ca_it': 'ca_IT.ISO8859-1', 'fa': 'fa_IR.UTF-8', 'ar_iq': 'ar_IQ.ISO8859-6', 'en_dl.utf8': 'en_DL.UTF-8', 'wal_et': 'wal_ET.UTF-8', 'pl': 'pl_PL.ISO8859-2', 'gu_in': 'gu_IN.UTF-8', 'sr_cs.iso88592@latn': 'sr_CS.ISO8859-2', 'br_fr': 'br_FR.ISO8859-1', 'ar_kw': 'ar_KW.ISO8859-6', 'ny_no': 'ny_NO.ISO8859-1', 'tk_tm': 'tk_TM.UTF-8', 'zh': 'zh_CN.eucCN', 'cz_cz': 'cs_CZ.ISO8859-2', 'en_ag': 'en_AG.UTF-8', 'tl_ph': 'tl_PH.ISO8859-1', 'nds_nl': 'nds_NL.UTF-8', 'universal.utf8@ucs4': 'en_US.UTF-8', 'tig_er': 'tig_ER.UTF-8', 'ko': 'ko_KR.eucKR', 'no_no.iso88591@nynorsk': 'no_NO.ISO8859-1', 'ka_ge.georgianrs': 'ka_GE.GEORGIAN-ACADEMY', 'as': 'as_IN.UTF-8', 'zu_za': 'zu_ZA.ISO8859-1', 'en_au': 'en_AU.ISO8859-1', 'es_es': 'es_ES.ISO8859-1', 'sp': 'sr_CS.ISO8859-5', 'be_by': 'be_BY.CP1251', 'mt_mt': 'mt_MT.ISO8859-3', 'croatian': 'hr_HR.ISO8859-2', 'en_in': 'en_IN.ISO8859-1', 'fo_fo': 'fo_FO.ISO8859-1', 'iso_8859_1': 'en_US.ISO8859-1', 'zh_sg': 'zh_SG.GB2312', 'iso-8859-15': 'en_US.ISO8859-15', 'iw_il': 'he_IL.ISO8859-8', 'en_bw': 'en_BW.ISO8859-1', 'sr_rs': 'sr_RS.UTF-8', 'posix-utf2': 'C', 'mg_mg': 'mg_MG.ISO8859-15', 'czech': 'cs_CZ.ISO8859-2', 'ik_ca': 'ik_CA.UTF-8', 'hu_hu': 'hu_HU.ISO8859-2', 'sr_sp': 'sr_CS.ISO8859-2', 'greek': 'el_GR.ISO8859-7', 'de_lu': 'de_LU.ISO8859-1', 'tg': 'tg_TJ.KOI8-C', 'lo_la.mulelao1': 'lo_LA.MULELAO-1', 'om_et': 'om_ET.UTF-8', 'es': 'es_ES.ISO8859-1', 'be_bg.utf8': 'bg_BG.UTF-8', 'bokmål': 'nb_NO.ISO8859-1', 'hi_in': 'hi_IN.ISCII-DEV', 'ber_dz': 'ber_DZ.UTF-8', 'c.iso88591': 'en_US.ISO8859-1', 'zh_hk.big5hk': 'zh_HK.big5hkscs', 'uk_ua': 'uk_UA.KOI8-U', 'c-french': 'fr_CA.ISO8859-1', 'ky_kg': 'ky_KG.UTF-8', 'c_c.c': 'C', 'chinese-t': 'zh_TW.eucTW', 'brx_in': 'brx_IN.UTF-8', 'dutch': 'nl_NL.ISO8859-1', 'sr_yu.microsoftcp1251@cyrillic': 'sr_CS.CP1251', 'lv': 'lv_LV.ISO8859-13', 'bs_ba': 'bs_BA.ISO8859-2', 've': 've_ZA.UTF-8', 'fr_fr': 'fr_FR.ISO8859-1', 'swedish': 'sv_SE.ISO8859-1', 'ha_ng': 'ha_NG.UTF-8', 'a3_az.koic': 'az_AZ.KOI8-C', 'iu_ca.nunacom8': 'iu_CA.NUNACOM-8', 'tt': 'tt_RU.TATAR-CYR', 'hrvatski': 'hr_HR.ISO8859-2', 'en_zm': 'en_ZM.UTF-8', 'nan_tw@latin': 'nan_TW.UTF-8@latin', 'te_in': 'te_IN.UTF-8', 'sk': 'sk_SK.ISO8859-2', 'pt_br': 'pt_BR.ISO8859-1', 'nb': 'nb_NO.ISO8859-1', 'iso8859-15': 'en_US.ISO8859-15', 'gd': 'gd_GB.ISO8859-1', 'tn': 'tn_ZA.ISO8859-15', 'eng_gb': 'en_GB.ISO8859-1', 'iso8859-1': 'en_US.ISO8859-1', 'zu': 'zu_ZA.ISO8859-1', 'vi_vn.viscii111': 'vi_VN.VISCII', 'he': 'he_IL.ISO8859-8', 'japanese': 'ja_JP.eucJP', 'fa_ir.isiri3342': 'fa_IR.ISIRI-3342', 'ia': 'ia.UTF-8', 'sr_me': 'sr_ME.UTF-8', 'ar_bh': 'ar_BH.ISO8859-6', 'ar_ma': 'ar_MA.ISO8859-6', 'nn': 'nn_NO.ISO8859-1', 'cs': 'cs_CZ.ISO8859-2', 'iso_8859_15': 'en_US.ISO8859-15', 'ar_qa': 'ar_QA.ISO8859-6', 'univ': 'en_US.utf', 'ar_sy': 'ar_SY.ISO8859-6', 'ts': 'ts_ZA.ISO8859-1', 'portuguese': 'pt_PT.ISO8859-1', 'el_gr': 'el_GR.ISO8859-7', 'es_cu': 'es_CU.UTF-8', 'en_gb': 'en_GB.ISO8859-1', 'tr': 'tr_TR.ISO8859-9', 'sinhala': 'si_LK.UTF-8', 'ru': 'ru_RU.UTF-8', 'am': 'am_ET.UTF-8', 'shs_ca': 'shs_CA.UTF-8', 'ss': 'ss_ZA.ISO8859-1', 'bo_in': 'bo_IN.UTF-8', 'pt_pt': 'pt_PT.ISO8859-1', 'aa_dj': 'aa_DJ.ISO8859-1', 'dutch.iso88591': 'nl_BE.ISO8859-1', 'es_uy': 'es_UY.ISO8859-1', 'gez_et': 'gez_ET.UTF-8', 'es_cr': 'es_CR.ISO8859-1', 'zh_cn.euc': 'zh_CN.eucCN', 'en_za': 'en_ZA.ISO8859-1', 'pp': 'pp_AN.ISO8859-1', 'bulgarian': 'bg_BG.CP1251', 'c.en': 'C', 'oc': 'oc_FR.ISO8859-1', 'sa_in': 'sa_IN.UTF-8', 'ee_ee': 'ee_EE.ISO8859-4', 'tt_ru': 'tt_RU.TATAR-CYR', 'ca': 'ca_ES.ISO8859-1', 'be@latin': 'be_BY.UTF-8@latin', 'so_dj': 'so_DJ.ISO8859-1', 'en': 'en_US.ISO8859-1', 'mn_mn': 'mn_MN.UTF-8', 'bo_cn': 'bo_CN.UTF-8', 'pl_pl': 'pl_PL.ISO8859-2', 'de_li.utf8': 'de_LI.UTF-8', 'jp_jp': 'ja_JP.eucJP', 'fr': 'fr_FR.ISO8859-1', 've_za': 've_ZA.UTF-8', 'ru_ru': 'ru_RU.UTF-8', 'portuguese_brazil': 'pt_BR.ISO8859-1', 'hu': 'hu_HU.ISO8859-2', 'catalan': 'ca_ES.ISO8859-1', 'ca_fr': 'ca_FR.ISO8859-1', 'bem_zm': 'bem_ZM.UTF-8', 'ne_np': 'ne_NP.UTF-8', 'en_us': 'en_US.ISO8859-1', 'eo': 'eo_XX.ISO8859-3', 'sd_pk': 'sd_PK.UTF-8', 'sd_in': 'sd_IN.UTF-8', 'kn': 'kn_IN.UTF-8', 'vi_vn': 'vi_VN.TCVN', 'eesti': 'et_EE.ISO8859-1', 'zh_tw.euctw': 'zh_TW.eucTW', 'da': 'da_DK.ISO8859-1', 'slovenian': 'sl_SI.ISO8859-2', 'mk_mk': 'mk_MK.ISO8859-5', 'et': 'et_EE.ISO8859-15', 'az_az.iso88599e': 'az_AZ.ISO8859-9E', 'af': 'af_ZA.ISO8859-1', 'hne': 'hne_IN.UTF-8', 'li_be': 'li_BE.UTF-8', 'ka_ge': 'ka_GE.GEORGIAN-ACADEMY', 'as_in': 'as_IN.UTF-8', 'eu_es': 'eu_ES.ISO8859-1', 'wo_sn': 'wo_SN.UTF-8', 'ar_dz': 'ar_DZ.ISO8859-6', 'ru_ua': 'ru_UA.KOI8-U', 'it_it': 'it_IT.ISO8859-1', 'lij_it': 'lij_IT.UTF-8', 'ts_za': 'ts_ZA.ISO8859-1', 'ig_ng': 'ig_NG.UTF-8', 'ja_jp.pck': 'ja_JP.SJIS', 'fo': 'fo_FO.ISO8859-1', 'english_united-states.437': 'C', 'uz_uz@cyrillic': 'uz_UZ.UTF-8', 'danish': 'da_DK.ISO8859-1', 'ta_lk': 'ta_LK.UTF-8', 'tt_ru@iqtelif': 'tt_RU.UTF-8@iqtelif', 'bn_in': 'bn_IN.UTF-8', 'pd_de': 'pd_DE.ISO8859-1', 'thai': 'th_TH.ISO8859-11', 'sr_yu.utf8@cyrillic': 'sr_RS.UTF-8', 'lb_lu': 'lb_LU.UTF-8', 'lo_la.ibmcp1133': 'lo_LA.IBM-CP1133', 'a3_az': 'az_AZ.KOI8-C', 'om_ke': 'om_KE.ISO8859-1', 'so_ke': 'so_KE.ISO8859-1', 'lo': 'lo_LA.MULELAO-1', 'af_za': 'af_ZA.ISO8859-1', 'hungarian': 'hu_HU.ISO8859-2', 'universal': 'en_US.utf', 'sh_sp': 'sr_CS.ISO8859-2', 'so_et': 'so_ET.UTF-8', 'es_ec': 'es_EC.ISO8859-1', 'be': 'be_BY.CP1251', 'es_pr': 'es_PR.ISO8859-1', 'ml': 'ml_IN.UTF-8', 'ph_ph': 'ph_PH.ISO8859-1', 'my_mm': 'my_MM.UTF-8', 'eu': 'eu_ES.ISO8859-1', 'nhn_mx': 'nhn_MX.UTF-8', 'th_th.tactis': 'th_TH.TIS620', 'fre_fr': 'fr_FR.ISO8859-1', 'japanese-euc': 'ja_JP.eucJP', 'sv_fi': 'sv_FI.ISO8859-1', 'fr_be': 'fr_BE.ISO8859-1', 'ff_sn': 'ff_SN.UTF-8', 'dv_mv': 'dv_MV.UTF-8', 'sr_yu': 'sr_RS.UTF-8@latin', 'es_mx': 'es_MX.ISO8859-1', 'es_py': 'es_PY.ISO8859-1', 'nr_za': 'nr_ZA.ISO8859-1', 'niu_nz': 'niu_NZ.UTF-8', 'es_ve': 'es_VE.ISO8859-1', 'nl_be': 'nl_BE.ISO8859-1', 'french': 'fr_FR.ISO8859-1', 'de': 'de_DE.ISO8859-1', 'turkish': 'tr_TR.ISO8859-9', 'sp_yu': 'sr_CS.ISO8859-5', 'sh_hr.iso88592': 'hr_HR.ISO8859-2', 'rw_rw': 'rw_RW.ISO8859-1', 'lv_lv': 'lv_LV.ISO8859-13', 'he_il': 'he_IL.ISO8859-8', 'sr_cs@latn': 'sr_CS.UTF-8@latin', 'mi_nz': 'mi_NZ.ISO8859-1', 'kl': 'kl_GL.ISO8859-1', 'japanese.euc': 'ja_JP.eucJP', 'bs': 'bs_BA.ISO8859-2', 'cextend': 'en_US.ISO8859-1', 'sr_cs': 'sr_CS.UTF-8', 'es_do': 'es_DO.ISO8859-1', 'bho_in': 'bho_IN.UTF-8', 'ro': 'ro_RO.ISO8859-2', 'vi_vn.tcvn5712': 'vi_VN.TCVN', 'en_be': 'en_BE.ISO8859-1', 'ga_ie': 'ga_IE.ISO8859-1', 'serbocroatian': 'sr_RS.UTF-8@latin', 'french_france': 'fr_FR.ISO8859-1', 'american': 'en_US.ISO8859-1', 'hebrew': 'he_IL.ISO8859-8', 'es_bo': 'es_BO.ISO8859-1', 'german.iso88591': 'de_CH.ISO8859-1', 'fy_nl': 'fy_NL.UTF-8', 'pd_us': 'pd_US.ISO8859-1', 'wae_ch': 'wae_CH.UTF-8', 'ia_fr': 'ia_FR.UTF-8', 'english_uk': 'en_GB.ISO8859-1', 'cs_cs': 'cs_CZ.ISO8859-2', 'en_sg': 'en_SG.ISO8859-1', 'el_gr@euro': 'el_GR.ISO8859-15', 'dz_bt': 'dz_BT.UTF-8', 'fa_ir': 'fa_IR.UTF-8', 'ph': 'ph_PH.ISO8859-1', 'sw_ke': 'sw_KE.UTF-8', 'pt': 'pt_PT.ISO8859-1', 'ss_za': 'ss_ZA.ISO8859-1', 'gez_er': 'gez_ER.UTF-8', 'hne_in': 'hne_IN.UTF-8', 'si': 'si_LK.UTF-8', 'eo_xx': 'eo_XX.ISO8859-3', 'mt': 'mt_MT.ISO8859-3', 'german_germany': 'de_DE.ISO8859-1', 'zh_cn.big5': 'zh_TW.big5', 'french.iso88591': 'fr_CH.ISO8859-1', 'gd_gb': 'gd_GB.ISO8859-1', 'tt_ru.tatarcyr': 'tt_RU.TATAR-CYR', 'ar_ly': 'ar_LY.ISO8859-6', 'ca_es': 'ca_ES.ISO8859-1', 'dansk': 'da_DK.ISO8859-1', 'lt': 'lt_LT.ISO8859-13', 'ka': 'ka_GE.GEORGIAN-ACADEMY', 'fur_it': 'fur_IT.UTF-8', 'in_id': 'id_ID.ISO8859-1', 'el': 'el_GR.ISO8859-7', 'estonian': 'et_EE.ISO8859-1', 'ja_jp': 'ja_JP.eucJP', 'mag_in': 'mag_IN.UTF-8', 'mr': 'mr_IN.UTF-8', 'si_lk': 'si_LK.UTF-8', 'mk': 'mk_MK.ISO8859-5', 'ar_aa': 'ar_AA.ISO8859-6', 'hy_am': 'hy_AM.UTF-8', 'fi_fi': 'fi_FI.ISO8859-15', 'ti_er': 'ti_ER.UTF-8', 'doi_in': 'doi_IN.UTF-8', 'pa': 'pa_IN.UTF-8', 'tn_za': 'tn_ZA.ISO8859-15', 'iu_ca': 'iu_CA.NUNACOM-8', 'or': 'or_IN.UTF-8', 'unm_us': 'unm_US.UTF-8', 'uz': 'uz_UZ.UTF-8', 'wa': 'wa_BE.ISO8859-1', 'zh_tw.euc': 'zh_TW.eucTW', 'mi': 'mi_NZ.ISO8859-1', 'ro_ro': 'ro_RO.ISO8859-2', 'az_az': 'az_AZ.ISO8859-9E', 'es_hn': 'es_HN.ISO8859-1', 'mhr_ru': 'mhr_RU.UTF-8', 'nds_de': 'nds_DE.UTF-8', 'chinese-s': 'zh_CN.eucCN', 'zh_hk': 'zh_HK.big5hkscs', 'japan': 'ja_JP.eucJP', 'sw_tz': 'sw_TZ.UTF-8', 'ar_ae': 'ar_AE.ISO8859-6', 'sl': 'sl_SI.ISO8859-2', 'cy_gb': 'cy_GB.ISO8859-1', 'en_zw.utf8': 'en_ZS.UTF-8', 'en_ie': 'en_IE.ISO8859-1', 'sh_hr': 'sh_HR.ISO8859-2', 'norwegian': 'no_NO.ISO8859-1', 'ca_es@valencia': 'ca_ES.ISO8859-15@valencia', 'sl_cs': 'sl_CS.ISO8859-2', 'sd_in@devanagari.utf8': 'sd_IN.UTF-8@devanagari', 'da_dk': 'da_DK.ISO8859-1', 'xh_za': 'xh_ZA.ISO8859-1', 'no_no.iso88591@bokmal': 'no_NO.ISO8859-1', 'ar_om': 'ar_OM.ISO8859-6', 'sat_in': 'sat_IN.UTF-8', 'no': 'no_NO.ISO8859-1', 'kl_gl': 'kl_GL.ISO8859-1', 'lithuanian': 'lt_LT.ISO8859-13', 'st': 'st_ZA.ISO8859-1', 'szl_pl': 'szl_PL.UTF-8', 'zh_cn': 'zh_CN.gb2312', 'kk_kz': 'kk_KZ.RK1048', 'es_gt': 'es_GT.ISO8859-1', 'nso': 'nso_ZA.ISO8859-15', 'cv_ru': 'cv_RU.UTF-8', 'de_ch': 'de_CH.ISO8859-1', 'sl_si': 'sl_SI.ISO8859-2', 'en_uk': 'en_GB.ISO8859-1', 'vi_vn.viscii': 'vi_VN.VISCII', 'ee': 'ee_EE.ISO8859-4', 'sq_mk': 'sq_MK.UTF-8', 'bn_bd': 'bn_BD.UTF-8', 'es_ar': 'es_AR.ISO8859-1', 'ar_sa': 'ar_SA.ISO8859-6', 'français': 'fr_FR.ISO8859-1', 'nl_aw': 'nl_AW.UTF-8', 'ku_tr': 'ku_TR.ISO8859-9', 'az': 'az_AZ.ISO8859-9E', 'sr_rs@latn': 'sr_RS.UTF-8@latin', 'es_us': 'es_US.ISO8859-1', 'iu': 'iu_CA.NUNACOM-8', 'gl': 'gl_ES.ISO8859-1', 'tl': 'tl_PH.ISO8859-1', 'et_ee': 'et_EE.ISO8859-15', 'de_at': 'de_AT.ISO8859-1', 'no@nynorsk': 'ny_NO.ISO8859-1', 'cz': 'cs_CZ.ISO8859-2', 'c.utf8': 'en_US.UTF-8', 'ber_ma': 'ber_MA.UTF-8', 'english': 'en_EN.ISO8859-1', 'galego': 'gl_ES.ISO8859-1', 'russian': 'ru_RU.ISO8859-5', 'sr_yu.cp1251@cyrillic': 'sr_CS.CP1251', 'es_sv': 'es_SV.ISO8859-1', 'os_ru': 'os_RU.UTF-8', 'ks_in': 'ks_IN.UTF-8', 'hr_hr': 'hr_HR.ISO8859-2', 'ks_in@devanagari.utf8': 'ks_IN.UTF-8@devanagari', 'c': 'C', 'yo_ng': 'yo_NG.UTF-8', 'pa_pk': 'pa_PK.UTF-8', 'is': 'is_IS.ISO8859-1', 'es_pe': 'es_PE.ISO8859-1', 'bg_bg': 'bg_BG.CP1251', 'crh_ua': 'crh_UA.UTF-8', 'ht_ht': 'ht_HT.UTF-8', 'am_et': 'am_ET.UTF-8', 'polish': 'pl_PL.ISO8859-2', 'ks': 'ks_IN.UTF-8', 'gl_es': 'gl_ES.ISO8859-1', 'sq_al': 'sq_AL.ISO8859-2', 'eo.utf8': 'eo.UTF-8', 'es_cl': 'es_CL.ISO8859-1', 'nb_no': 'nb_NO.ISO8859-1', 'en_ph': 'en_PH.ISO8859-1', 'so_so': 'so_SO.ISO8859-1', 'kw': 'kw_GB.ISO8859-1', 'sid_et': 'sid_ET.UTF-8', 'en_zw': 'en_ZW.ISO8859-1', 'nl': 'nl_NL.ISO8859-1', 'finnish': 'fi_FI.ISO8859-1', 'zh_tw': 'zh_TW.big5', 'ar_jo': 'ar_JO.ISO8859-6', 'byn_er': 'byn_ER.UTF-8', 'ta_in.tscii0': 'ta_IN.TSCII-0', 'lo_la.cp1133': 'lo_LA.IBM-CP1133', 'sr_yu.iso88595': 'sr_CS.ISO8859-5', 'ur_in': 'ur_IN.UTF-8', 'ar_tn': 'ar_TN.ISO8859-6', 'sh': 'sr_RS.UTF-8@latin', 'korean': 'ko_KR.eucKR', 'sc_it': 'sc_IT.UTF-8', 'fy_de': 'fy_DE.UTF-8', 'ga': 'ga_IE.ISO8859-1', 'niu_nu': 'niu_NU.UTF-8', 'sh_ba.iso88592@bosnia': 'sr_CS.ISO8859-2', 'id_id': 'id_ID.ISO8859-1', 'ta_in.tscii': 'ta_IN.TSCII-0', 'eo_eo': 'eo_EO.ISO8859-3', 'oc_fr': 'oc_FR.ISO8859-1', 'ka_ge.georgianacademy': 'ka_GE.GEORGIAN-ACADEMY', 'sv': 'sv_SE.ISO8859-1', 'eu_fr': 'eu_FR.ISO8859-1', 'lt_lt': 'lt_LT.ISO8859-13', 'zh_sg.gbk': 'zh_SG.GBK', 'ar_lb': 'ar_LB.ISO8859-6', 'hr': 'hr_HR.ISO8859-2', 'sr@latn': 'sr_CS.UTF-8@latin', 'hi': 'hi_IN.ISCII-DEV', 'c.ascii': 'C', 'en_dk': 'en_DK.ISO8859-1', 'aa_er': 'aa_ER.UTF-8', 'hi_in.isciidev': 'hi_IN.ISCII-DEV', 'fr_ch': 'fr_CH.ISO8859-1', 'vi': 'vi_VN.TCVN', 'ug_cn': 'ug_CN.UTF-8', 'no_no': 'no_NO.ISO8859-1', 'ms_my': 'ms_MY.ISO8859-1', 'sr_yu@cyrillic': 'sr_RS.UTF-8', 'ayc_pe': 'ayc_PE.UTF-8', 'el_cy': 'el_CY.ISO8859-7', 'ko_kr': 'ko_KR.eucKR', 'nn_no': 'nn_NO.ISO8859-1', 'be_by@latin': 'be_BY.UTF-8@latin', 'a3': 'az_AZ.KOI8-C', 'pp_an': 'pp_AN.ISO8859-1', 'nl_nl': 'nl_NL.ISO8859-1', 'bg': 'bg_BG.CP1251', 'ta_in': 'ta_IN.TSCII-0', 'tr_tr': 'tr_TR.ISO8859-9', 'ml_in': 'ml_IN.UTF-8', 'te': 'te_IN.UTF-8', 'ko_kr.euc': 'ko_KR.eucKR', 'gv': 'gv_GB.ISO8859-1', 'ja_jp.mscode': 'ja_JP.SJIS', 'c_c': 'C', 'id': 'id_ID.ISO8859-1', 'sr@cyrillic': 'sr_RS.UTF-8', 'lo_la': 'lo_LA.MULELAO-1', 'ar_sd': 'ar_SD.ISO8859-6', 'fr_ca': 'fr_CA.ISO8859-1', 'an_es': 'an_ES.ISO8859-15', 'deutsch': 'de_DE.ISO8859-1', 'pa_in': 'pa_IN.UTF-8', 'ger_de': 'de_DE.ISO8859-1', 'uz_uz': 'uz_UZ.UTF-8', 'br': 'br_FR.ISO8859-1', 'sq': 'sq_AL.ISO8859-2', 'slovene': 'sl_SI.ISO8859-2', 'mai_in': 'mai_IN.UTF-8', 'th_th.tis620': 'th_TH.TIS620', 'it_ch': 'it_CH.ISO8859-1', 'se_no': 'se_NO.UTF-8', 'es_pa': 'es_PA.ISO8859-1', 'ja': 'ja_JP.eucJP', 'ar_ye': 'ar_YE.ISO8859-6', 'sv_se': 'sv_SE.ISO8859-1', 'hy_am.armscii8': 'hy_AM.ARMSCII_8', 'or_in': 'or_IN.UTF-8', 'sr_yu.iso88592': 'sr_CS.ISO8859-2', 'sr_yu.utf8': 'sr_RS.UTF-8', 'ast_es': 'ast_ES.ISO8859-15', 'ur_pk': 'ur_PK.CP1256', 'romanian': 'ro_RO.ISO8859-2', 'de_de': 'de_DE.ISO8859-1', 'km_kh': 'km_KH.UTF-8', 'german': 'de_DE.ISO8859-1', 'lg_ug': 'lg_UG.ISO8859-10', 'en_ng': 'en_NG.UTF-8', 'fr_lu': 'fr_LU.ISO8859-1', 'ur': 'ur_PK.CP1256', 'wa_be': 'wa_BE.ISO8859-1', 'en_hk': 'en_HK.ISO8859-1', 'ms': 'ms_MY.ISO8859-1', 'galician': 'gl_ES.ISO8859-1', 'arabic': 'ar_AA.ISO8859-6', 'english_us': 'en_US.ISO8859-1', 'es_co': 'es_CO.ISO8859-1', 'sd': 'sd_IN.UTF-8', 'ar_in': 'ar_IN.UTF-8', 'uk': 'uk_UA.KOI8-U', 'icelandic': 'is_IS.ISO8859-1', 'nynorsk': 'nn_NO.ISO8859-1', 'yi_us': 'yi_US.CP1255', 'csb_pl': 'csb_PL.UTF-8', 'cs_cz': 'cs_CZ.ISO8859-2', 'li_nl': 'li_NL.UTF-8', 'sr': 'sr_RS.UTF-8', 'fil_ph': 'fil_PH.UTF-8', 'hsb_de': 'hsb_DE.ISO8859-2', 'korean.euc': 'ko_KR.eucKR', 'sh_yu': 'sr_RS.UTF-8@latin', 'rumanian': 'ro_RO.ISO8859-2', 'aa_et': 'aa_ET.UTF-8', 'th_th': 'th_TH.ISO8859-11', 'yue_hk': 'yue_HK.UTF-8', 'rw': 'rw_RW.ISO8859-1', 'ar_eg': 'ar_EG.ISO8859-6', 'ca_ad': 'ca_AD.ISO8859-1', 'ky': 'ky_KG.UTF-8'}
```

**Comment by Kwpolska** [comment]
https://atlas.hashicorp.com/freebsd/boxes/FreeBSD-10.2-RELEASE

**Comment by Kwpolska** [comment]
Commit 9545ee3 should fix it. @Wayneoween, would you mind testing on your end?

**Comment by Wayneoween** [comment]
Yes that fixes it :smiley:  :+1:

**Comment by Wayneoween** [comment]
Yes, that fixes this issue :smile: :+1: 
Thanks!
