### ISSUE TITLE
SyntaxError: Nikola

### ISSUE THREAD

**Issue by vivekiitkgp** [getnikola/nikola#2168]
Running `nikola` throws the following error:

```
Traceback (most recent call last):
  File "/home/vivekrai/.miniconda/envs/py34/bin/nikola", line 7, in <module>
    from nikola.__main__ import main
  File "/home/vivekrai/.miniconda/envs/py34/lib/python3.4/site-packages/nikola/__init__.py", line 35, in <module>
    from .nikola import Nikola  # NOQA
  File "/home/vivekrai/.miniconda/envs/py34/lib/python3.4/site-packages/nikola/nikola.py", line 59, in <module>
    from .post import Post  # NOQA
  File "/home/vivekrai/.miniconda/envs/py34/lib/python3.4/site-packages/nikola/post.py", line 44, in <module>
    from . import utils
  File "/home/vivekrai/.miniconda/envs/py34/lib/python3.4/site-packages/nikola/utils.py", line 47, in <module>
    import logbook
  File "/home/vivekrai/.miniconda/envs/py34/lib/python3.4/site-packages/logbook/__init__.py", line 14, in <module>
    from .base import LogRecord, Logger, LoggerGroup, NestedSetup, \
  File "/home/vivekrai/.miniconda/envs/py34/lib/python3.4/site-packages/logbook/base.py", line 18, in <module>
    from logbook.concurrency import thread_get_name, thread_get_ident, greenlet_get_ident
  File "/home/vivekrai/.miniconda/envs/py34/lib/python3.4/site-packages/logbook/concurrency.py", line 4, in <module>
    import gevent
  File "/home/vivekrai/.miniconda/envs/py34/lib/python3.4/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/home/vivekrai/.miniconda/envs/py34/lib/python3.4/site-packages/gevent/hub.py", line 289
    except Exception, ex:
                    ^
SyntaxError: invalid syntax
```

Installed all latest packages using `pip`. On Ubuntu `15.04`.

**Comment by vivekiitkgp** [comment]
Removing `gevent` fixes the issue. Please close as you you see fit.

**Comment by Kwpolska** [comment]
Closing as `gevent` is not installed by Nikola and our stack by default (it was probably leftover from something else, and logbook tried to use it)
