### ISSUE TITLE
NameError: name 'WebSocketWSGIHandler' is not defined

### ISSUE THREAD

**Issue by devurandom** [getnikola/nikola#2173]
It appears that Nikola nowadays needs some websocket module. Is that intentional?

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/yapsy/PluginManager.py", line 485, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/usr/lib64/python2.7/site-packages/nikola/plugins/command/auto/__init__.py", line 443, in <module>
    f = WebSocketWSGIHandler.finish_response
NameError: name 'WebSocketWSGIHandler' is not defined
```

**Comment by Kwpolska** [comment]
Are you running an up-to-date version of Nikola? This doesn’t happen in v7.7.3, and is protected against.

**Comment by devurandom** [comment]
When run with Python 3.4, I also get an error:
```
[2015-11-15T18:44:35Z] ERROR: yapsy: Unable to import plugin: /usr/lib64/python3.4/site-packages/nikola/plugins/command/auto
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/yapsy/PluginManager.py", line 485, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/usr/lib64/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib64/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/lib64/python3.4/site-packages/nikola/plugins/command/auto/__init__.py", line 443, in <module>
    f = WebSocketWSGIHandler.finish_response
NameError: name 'WebSocketWSGIHandler' is not defined
```

**Comment by devurandom** [comment]
When run with Python 3.4, I also get an error:
```
[2015-11-15T18:44:35Z] ERROR: yapsy: Unable to import plugin: /usr/lib64/python3.4/site-packages/nikola/plugins/command/auto
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/yapsy/PluginManager.py", line 485, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/usr/lib64/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib64/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/lib64/python3.4/site-packages/nikola/plugins/command/auto/__init__.py", line 443, in <module>
    f = WebSocketWSGIHandler.finish_response
NameError: name 'WebSocketWSGIHandler' is not defined
```

**Comment by devurandom** [comment]
When run with Python 3.4, I also get an error:
```
[2015-11-15T18:44:35Z] ERROR: yapsy: Unable to import plugin: /usr/lib64/python3.4/site-packages/nikola/plugins/command/auto
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/yapsy/PluginManager.py", line 485, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/usr/lib64/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib64/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/lib64/python3.4/site-packages/nikola/plugins/command/auto/__init__.py", line 443, in <module>
    f = WebSocketWSGIHandler.finish_response
NameError: name 'WebSocketWSGIHandler' is not defined
```

**Comment by devurandom** [comment]
No, I'm running 7.6.3 ATM.
