### ISSUE TITLE
Exception raised while nesting multiple levels of menus.

### ISSUE THREAD

**Issue by KelSolaar** [getnikola/nikola#2182]
Hi,

I get an exception when trying to nest multiple levels of menus:

This works fine:
```python
NAVIGATION_LINKS = {
    DEFAULT_LANG: (
        ('/a', 'a'),
        (
            (
                ('/c', 'c'),
                ('/d', 'd'),
                ('/e', 'e'),
            ),
            'b'
        ),
    )
}
```

This raises an exception:
```python
NAVIGATION_LINKS = {
    DEFAULT_LANG: (
        ('/a', 'a'),
        (
            (
                ('/c', 'c'),
                ('/d', 'd'),
                ('/e', 'e'),
                (
                    (
                        ('/g', 'h'),
                        ('/i', 'i'),
                        ('/j', 'j'),
                    ),
                    'f'
                )
            ),
            'b'
        ),
    )
}
```

Traceback:
```python
Traceback (most recent call last):
  File "/home/vagrant/anaconda/envs/colour-nikola/lib/python3.5/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/vagrant/anaconda/envs/colour-nikola/lib/python3.5/site-packages/nikola/plugins/task/galleries.py", line 583, in render_gallery_index
    self.site.render_template(template_name, output_name, context)
  File "/home/vagrant/anaconda/envs/colour-nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1143, in render_template
    template_name, None, local_context)
  File "/home/vagrant/anaconda/envs/colour-nikola/lib/python3.5/site-packages/nikola/plugins/template/jinja.py", line 91, in render_template
    output = template.render(**context)
  File "/home/vagrant/anaconda/envs/colour-nikola/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/vagrant/anaconda/envs/colour-nikola/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/anaconda/envs/colour-nikola/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/vagrant/anaconda/envs/colour-nikola/lib/python3.5/site-packages/nikola/data/themes/bootstrap3-jinja/templates/gallery.tmpl", line 4, in top-level template code
    {% import 'crumbs.tmpl' as ui with context %}
  File "/home/vagrant/anaconda/envs/colour-nikola/lib/python3.5/site-packages/nikola/data/themes/bootstrap3-jinja/templates/base.tmpl", line 37, in top-level template code
    {{ base.html_navigation_links() }}
  File "themes/ipython/templates/base_helper.tmpl", line 134, in template
    {% if rel_link(permalink, suburl) == "#" %}
  File "/home/vagrant/anaconda/envs/colour-nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1519, in rel_link
    dst = urljoin(src, dst)
  File "/home/vagrant/anaconda/envs/colour-nikola/lib/python3.5/urllib/parse.py", line 415, in urljoin
    base, url, _coerce_result = _coerce_args(base, url)
  File "/home/vagrant/anaconda/envs/colour-nikola/lib/python3.5/urllib/parse.py", line 111, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

**Comment by Kwpolska** [comment]
1. Please do not use the ipython theme, all its changes were merged into `master`.  I’ll take the theme down from our website.
2. Either way, Nikola (and the Bootstrap framework) support only one level of nesting for menus.  Please come up with a different menu structure.  Closing as wontfix.

**Comment by KelSolaar** [comment]
1. Good to know! Means that all the themes will natively support IPython Notebooks? If it is the case [zen-ipython](https://themes.getnikola.com/#zen-ipython) should probably be culled too.
2. Makes sense, we have sub-menus on our current site but I just noticed we actually did them in CSS, I though they were natively supported. Some context: https://github.com/twbs/bootstrap/issues/424

**Comment by Kwpolska** [comment]
Zen has custom templates which do not implement ipython support (as of now)

-- 
Chris Warrick <https://chriswarrick.com/>
