### ISSUE TITLE
nikola auto --conf=myconf.py does not work

### ISSUE THREAD

**Issue by SpotlightKid** [getnikola/nikola#2192]
But I expected it to, in line with `nikola build` and `nikola deploy`.

I get this error:

```
$ nikola auto --conf=conf-dev.py
[2015-12-22T03:50:10Z] INFO: Nikola: Using config file 'conf-dev.py'
Traceback (most recent call last):
  File "/home/chris/lib/virtualenvs/adsr.online/lib/python3.5/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/home/chris/lib/virtualenvs/adsr.online/lib/python3.5/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/chris/lib/virtualenvs/adsr.online/lib/python3.5/site-packages/nikola/plugin_categories.py", line 124, in execute
    return self._execute(options, args)
  File "/home/chris/lib/virtualenvs/adsr.online/lib/python3.5/site-packages/nikola/plugins/command/auto/__init__.py", line 149, in _execute
    subprocess.call(self.cmd_arguments)
  File "/usr/lib64/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '--conf=conf-dev.py'
```

**Comment by Kwpolska** [comment]
I got the command line arguments order wrong, sorry. Fixed.
