### ISSUE TITLE
pygments.util.ClassNotFound: no lexer for alias None found

### ISSUE THREAD

**Issue by entron** [getnikola/nikola#2228]
I found that if my post contains a code block without declaring the language then it will give this error:

```
pygments.util.ClassNotFound: no lexer for alias None found
```

**Comment by Kwpolska** [comment]
full traceback?

**Comment by entron** [comment]
Here it is. I am using macbook and python 3

```
Scanning posts......done!
.  render_posts:timeline_changes
.  render_posts:cache/posts/test-markdown.html
########################################
TaskError - taskid:render_posts:cache/posts/test-markdown.html
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/markdown/extensions/codehilite.py", line 108, in hilite
    lexer = get_lexer_by_name(self.lang)
  File "/usr/local/lib/python3.4/site-packages/pygments/lexers/__init__.py", line 81, in get_lexer_by_name
    raise ClassNotFound('no lexer for alias %r found' % _alias)
pygments.util.ClassNotFound: no lexer for alias None found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/nikola/post.py", line 485, in compile
    self.is_two_file),
  File "/usr/local/lib/python3.4/site-packages/nikola/plugins/compile/markdown/__init__.py", line 77, in compile_html
    output = markdown(data, self.extensions)
  File "/usr/local/lib/python3.4/site-packages/markdown/__init__.py", line 494, in markdown
    return md.convert(text)
  File "/usr/local/lib/python3.4/site-packages/markdown/__init__.py", line 368, in convert
    self.lines = prep.run(self.lines)
  File "/usr/local/lib/python3.4/site-packages/markdown/extensions/fenced_code.py", line 89, in run
    code = highliter.hilite()
  File "/usr/local/lib/python3.4/site-packages/markdown/extensions/codehilite.py", line 112, in hilite
    lexer = guess_lexer(self.src)
  File "/usr/local/lib/python3.4/site-packages/pygments/lexers/__init__.py", line 245, in guess_lexer
    for lexer in _iter_lexerclasses():
  File "/usr/local/lib/python3.4/site-packages/pygments/lexers/__init__.py", line 177, in _iter_lexerclasses
    for lexer in find_plugin_lexers():
  File "/usr/local/lib/python3.4/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2379, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2396, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (ptyprocess 0.4 (/usr/local/lib/python3.4/site-packages), Requirement.parse('ptyprocess>=0.5'), {'pexpect'})
```

**Comment by Kwpolska** [comment]
This is a bug in python-markdown, not Nikola. Please report it there.

(You might also want to upgrade `ptyprocess`)

**Comment by entron** [comment]
Thanks! After I upgraded `ptyprocess ` this problem is solved!
