### ISSUE TITLE
🕶 (DARK SUNGLASSES, U+ 1F576) didn't appear

### ISSUE THREAD

**Issue by minhoryang** [getnikola/nikola#2230]
Expected: show 🕶 at the post.rst or post.md

Happened: Whole post's content is missing.

Environment: Python 3.5.0, OS X 10.11.2 and Chrome
```
argh==0.26.1
blinker==1.4
cffi==1.4.2
cloudpickle==0.1.1
docutils==0.12
doit==0.29.0
houdini==0.0.1
husl==4.0.3
Jinja2==2.8
livereload==2.4.0
Logbook==0.12.3
lxml==3.5.0
MacFSEvents==0.6
Mako==1.0.3
MarkupSafe==0.23
misaka==2.0.0
natsort==4.0.4
Nikola==7.7.3
pathtools==0.1.2
Pillow==3.0.0
pycparser==2.14
Pygments==2.0.2
PyRSS2Gen==1.1
python-dateutil==2.4.2
PyYAML==3.11
requests==2.8.1
six==1.10.0
tornado==4.3
Unidecode==0.4.18
watchdog==0.8.3
webassets==0.11.1
ws4py==0.3.4
Yapsy==1.11.223
```

**Comment by minhoryang** [comment]
[post.md](https://github.com/minhoryang/minhoryang.github.io/blame/source/posts/unicode-emoji.en.md) compiles [blank contents](https://minhoryang.github.io/en/posts/unicode-emoji-wasnt-handled-at-nikola/)

[post.rst](https://github.com/minhoryang/minhoryang.github.io/blame/source/posts/emojitest.en.rst) compiles ["Write your post here."only](https://minhoryang.github.io/en/posts/emojitest/)

**Comment by ralsina** [comment]
Works here with rst at least
![tw14](https://cloud.githubusercontent.com/assets/1579/12586217/2f11c110-c42e-11e5-8d8a-6a119e459b49.png)

**Comment by Kwpolska** [comment]
I can’t reproduce here either, but you seem to be on OS X. I’m not really sure how to debug…

* does this happen with `rst2html` or `nikola rst2html`?
* does this happen with the default theme?

**Comment by minhoryang** [comment]
@ralsina Oh! thanks for helping me!
Which environment are you using? In my case, I use OS X.

@Kwpolska the result of `nikola rst2html posts/emojitest.en.rst | pbcopy`
```
<!DOCTYPE html>
<html><body><p>!   D   O   C   T   Y   P   E       h   t   m   l   &gt;   
   </p></body></html>
```
is that. (with current theme and without THEME= @ conf.py)

**Comment by Kwpolska** [comment]
What about `rst2html` (the default reST renderer command)?

**Comment by minhoryang** [comment]
@Kwpolska 
the result of `rst2html.py < emojitest.en.rst | pbcopy`
```html
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Docutils 0.12: http://docutils.sourceforge.net/" />
<title></title>
<style type="text/css">

/*
:Author: David Goodger (goodger@python.org)
:Id: $Id: html4css1.css 7614 2013-02-21 15:55:51Z milde $
:Copyright: This stylesheet has been placed in the public domain.

Default cascading style sheet for the HTML output of Docutils.

See http://docutils.sf.net/docs/howto/html-stylesheets.html for how to
customize this style sheet.
*/

/* used to remove borders from tables and images */
.borderless, table.borderless td, table.borderless th {
  border: 0 }

table.borderless td, table.borderless th {
  /* Override padding for "table.docutils td" with "! important".
     The right padding separates the table cells. */
  padding: 0 0.5em 0 0 ! important }

.first {
  /* Override more specific margin styles with "! important". */
  margin-top: 0 ! important }

.last, .with-subtitle {
  margin-bottom: 0 ! important }

.hidden {
  display: none }

a.toc-backref {
  text-decoration: none ;
  color: black }

blockquote.epigraph {
  margin: 2em 5em ; }

dl.docutils dd {
  margin-bottom: 0.5em }

object[type="image/svg+xml"], object[type="application/x-shockwave-flash"] {
  overflow: hidden;
}

/* Uncomment (and remove this text!) to get bold-faced definition list terms
dl.docutils dt {
  font-weight: bold }
*/

div.abstract {
  margin: 2em 5em }

div.abstract p.topic-title {
  font-weight: bold ;
  text-align: center }

div.admonition, div.attention, div.caution, div.danger, div.error,
div.hint, div.important, div.note, div.tip, div.warning {
  margin: 2em ;
  border: medium outset ;
  padding: 1em }

div.admonition p.admonition-title, div.hint p.admonition-title,
div.important p.admonition-title, div.note p.admonition-title,
div.tip p.admonition-title {
  font-weight: bold ;
  font-family: sans-serif }

div.attention p.admonition-title, div.caution p.admonition-title,
div.danger p.admonition-title, div.error p.admonition-title,
div.warning p.admonition-title, .code .error {
  color: red ;
  font-weight: bold ;
  font-family: sans-serif }

/* Uncomment (and remove this text!) to get reduced vertical space in
   compound paragraphs.
div.compound .compound-first, div.compound .compound-middle {
  margin-bottom: 0.5em }

div.compound .compound-last, div.compound .compound-middle {
  margin-top: 0.5em }
*/

div.dedication {
  margin: 2em 5em ;
  text-align: center ;
  font-style: italic }

div.dedication p.topic-title {
  font-weight: bold ;
  font-style: normal }

div.figure {
  margin-left: 2em ;
  margin-right: 2em }

div.footer, div.header {
  clear: both;
  font-size: smaller }

div.line-block {
  display: block ;
  margin-top: 1em ;
  margin-bottom: 1em }

div.line-block div.line-block {
  margin-top: 0 ;
  margin-bottom: 0 ;
  margin-left: 1.5em }

div.sidebar {
  margin: 0 0 0.5em 1em ;
  border: medium outset ;
  padding: 1em ;
  background-color: #ffffee ;
  width: 40% ;
  float: right ;
  clear: right }

div.sidebar p.rubric {
  font-family: sans-serif ;
  font-size: medium }

div.system-messages {
  margin: 5em }

div.system-messages h1 {
  color: red }

div.system-message {
  border: medium outset ;
  padding: 1em }

div.system-message p.system-message-title {
  color: red ;
  font-weight: bold }

div.topic {
  margin: 2em }

h1.section-subtitle, h2.section-subtitle, h3.section-subtitle,
h4.section-subtitle, h5.section-subtitle, h6.section-subtitle {
  margin-top: 0.4em }

h1.title {
  text-align: center }

h2.subtitle {
  text-align: center }

hr.docutils {
  width: 75% }

img.align-left, .figure.align-left, object.align-left {
  clear: left ;
  float: left ;
  margin-right: 1em }

img.align-right, .figure.align-right, object.align-right {
  clear: right ;
  float: right ;
  margin-left: 1em }

img.align-center, .figure.align-center, object.align-center {
  display: block;
  margin-left: auto;
  margin-right: auto;
}

.align-left {
  text-align: left }

.align-center {
  clear: both ;
  text-align: center }

.align-right {
  text-align: right }

/* reset inner alignment in figures */
div.align-right {
  text-align: inherit }

/* div.align-center * { */
/*   text-align: left } */

ol.simple, ul.simple {
  margin-bottom: 1em }

ol.arabic {
  list-style: decimal }

ol.loweralpha {
  list-style: lower-alpha }

ol.upperalpha {
  list-style: upper-alpha }

ol.lowerroman {
  list-style: lower-roman }

ol.upperroman {
  list-style: upper-roman }

p.attribution {
  text-align: right ;
  margin-left: 50% }

p.caption {
  font-style: italic }

p.credits {
  font-style: italic ;
  font-size: smaller }

p.label {
  white-space: nowrap }

p.rubric {
  font-weight: bold ;
  font-size: larger ;
  color: maroon ;
  text-align: center }

p.sidebar-title {
  font-family: sans-serif ;
  font-weight: bold ;
  font-size: larger }

p.sidebar-subtitle {
  font-family: sans-serif ;
  font-weight: bold }

p.topic-title {
  font-weight: bold }

pre.address {
  margin-bottom: 0 ;
  margin-top: 0 ;
  font: inherit }

pre.literal-block, pre.doctest-block, pre.math, pre.code {
  margin-left: 2em ;
  margin-right: 2em }

pre.code .ln { color: grey; } /* line numbers */
pre.code, code { background-color: #eeeeee }
pre.code .comment, code .comment { color: #5C6576 }
pre.code .keyword, code .keyword { color: #3B0D06; font-weight: bold }
pre.code .literal.string, code .literal.string { color: #0C5404 }
pre.code .name.builtin, code .name.builtin { color: #352B84 }
pre.code .deleted, code .deleted { background-color: #DEB0A1}
pre.code .inserted, code .inserted { background-color: #A3D289}

span.classifier {
  font-family: sans-serif ;
  font-style: oblique }

span.classifier-delimiter {
  font-family: sans-serif ;
  font-weight: bold }

span.interpreted {
  font-family: sans-serif }

span.option {
  white-space: nowrap }

span.pre {
  white-space: pre }

span.problematic {
  color: red }

span.section-subtitle {
  /* font-size relative to parent (h1..h6 element) */
  font-size: 80% }

table.citation {
  border-left: solid 1px gray;
  margin-left: 1px }

table.docinfo {
  margin: 2em 4em }

table.docutils {
  margin-top: 0.5em ;
  margin-bottom: 0.5em }

table.footnote {
  border-left: solid 1px black;
  margin-left: 1px }

table.docutils td, table.docutils th,
table.docinfo td, table.docinfo th {
  padding-left: 0.5em ;
  padding-right: 0.5em ;
  vertical-align: top }

table.docutils th.field-name, table.docinfo th.docinfo-name {
  font-weight: bold ;
  text-align: left ;
  white-space: nowrap ;
  padding-left: 0 }

/* "booktabs" style (no vertical lines) */
table.docutils.booktabs {
  border: 0px;
  border-top: 2px solid;
  border-bottom: 2px solid;
  border-collapse: collapse;
}
table.docutils.booktabs * {
  border: 0px;
}
table.docutils.booktabs th {
  border-bottom: thin solid;
  text-align: left;
}

h1 tt.docutils, h2 tt.docutils, h3 tt.docutils,
h4 tt.docutils, h5 tt.docutils, h6 tt.docutils {
  font-size: 100% }

ul.auto-toc {
  list-style-type: none }

</style>
</head>
<body>
<div class="document">


<!-- title: EmojiTest -->
<!-- slug: emojitest -->
<!-- date: 2016-01-27 00:51:19 UTC+09:00 -->
<!-- tags: -->
<!-- category: -->
<!-- link: -->
<!-- description: -->
<!-- type: text -->
<p>Below this line, there should be a letter of DARK SUNGLASSES, U+1F576.
🕶
But didn't.</p>
</div>
</body>
</html>
```

**Comment by ralsina** [comment]
@minhoryang yes, it' s there (see attached image)
![tw15](https://cloud.githubusercontent.com/assets/1579/12586950/1f5f8812-c431-11e5-9d3d-9ef79004adb1.png)
. You are maybe using a font that has no emoji glyphs?

**Comment by Kwpolska** [comment]
I guess lxml is broken. Please run this Python script and compare the output.

```py
#!/usr/bin/env python3
import lxml.html, lxml.etree
uni = "<p>Unicode! \U0001F576 Sunglasses!</p>"
t = lxml.html.fragment_fromstring(uni)
print("B", lxml.etree.tostring(t))
print("U", lxml.etree.tostring(t, encoding='unicode'))
```

On my system, it outputs:

```xml
B b'<p>Unicode! &#128374; Sunglasses!</p>'
U <p>Unicode! 🕶 Sunglasses!</p>
```

---

@ralsina It’s in rst2html output, but not in nikola rst2html output.

**Comment by ralsina** [comment]
As a workaround you can use the emoji plugin: https://plugins.getnikola.com/#emoji

**Comment by minhoryang** [comment]
@Kwpolska 
```python
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    t = lxml.html.fragment_fromstring(uni)
  File "/Users/minhoryang/.pyenv/versions/3.5.0-blog/lib/python3.5/site-packages/lxml/html/__init__.py", line 825, in fragment_fromstring
    base_url=base_url, **kw)
  File "/Users/minhoryang/.pyenv/versions/3.5.0-blog/lib/python3.5/site-packages/lxml/html/__init__.py", line 786, in fragments_fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Users/minhoryang/.pyenv/versions/3.5.0-blog/lib/python3.5/site-packages/lxml/html/__init__.py", line 755, in document_fromstring
    "Document is empty")
lxml.etree.ParserError: Document is empty
```

**Comment by Kwpolska** [comment]
Well, that’s a huge lxml bug. I’m afraid we can’t help here. Ask for help on the [lxml mailing list](https://mailman-mail5.webfaction.com/listinfo/lxml) or on [their bug tracker](https://bugs.launchpad.net/lxml)…

**Comment by minhoryang** [comment]
Haha! thanks for helping me!!
FYI, just for a curious, which environment do you use now? Why didn't happen to your system?

**Comment by Kwpolska** [comment]
We’re both on Linux.

**Comment by minhoryang** [comment]
Oh.... +1 reason for moving on to Linux.
Do I need to close this?

**Comment by Kwpolska** [comment]
We can’t do much better, let’s close it.
