### ISSUE TITLE
nikola build fails with ipynb files

### ISSUE THREAD

**Issue by ulf1** [getnikola/nikola#2252]
assumptions:
- I added everything into conf.py (i.e. COMPILER, POSTS, PAGES) regard ipynb. 
- python 3.5.0 with a virtualenv

(1) activate virtualenv

(2) cd into the nikola website

(3) i created a empty "this-is-a-jupyter-test-file.ipynb" file with nikola
`nikola new_post -f ipynb`

(4) build website
`nikola build`

and the error messages comes

<pre>
TaskError - taskid:render_posts:cache/posts/this-is-a-jupyter-test-file.html
PythonAction Error
Traceback (most recent call last):
  File "/home/boris/cfs/venv-3.5.0_nb-blog/lib/python3.5/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/boris/cfs/venv-3.5.0_nb-blog/lib/python3.5/site-packages/nikola/post.py", line 492, in compile
    self.is_two_file),
  File "/home/boris/cfs/venv-3.5.0_nb-blog/lib/python3.5/site-packages/nikola/plugins/compile/ipynb.py", line 99, in compile_html
    out_file.write()
TypeError: write() takes exactly one argument (0 given)
</pre>

seems that the file path got lost somewhere.

Update:
i tried it with python 3.4.4 but get the same errror

**Comment by Kwpolska** [comment]
Known bug that we’ll fix with an emergency bugfix release (see #2248).
