### ISSUE TITLE
No module named _bsddb when nikola build

### ISSUE THREAD

**Issue by hbprotoss** [getnikola/nikola#2313]
I have python package bsddb3 installed. When executing `nikola build`, exception raised.

On OSX 10.11.4, python 2.7.11

```
Scanning posts....done!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/usr/local/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/usr/local/lib/python2.7/site-packages/doit/cmd_base.py", line 393, in execute
    self.dep_manager = Dependency(db_class, params['dep_file'], checker_cls)
  File "/usr/local/lib/python2.7/site-packages/doit/dependency.py", line 498, in __init__
    self.backend = db_class(backend_name)
  File "/usr/local/lib/python2.7/site-packages/doit/dependency.py", line 161, in __init__
    self._dbm = ddbm.open(self.name, 'c')
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/dbhash.py", line 7, in <module>
    import bsddb
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bsddb/__init__.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb
```

**Comment by tritium21** [comment]
This very much looks like someone else's bug... Can you attempt to install in a virtualenv without the third party bsddb3 module?

**Comment by hbprotoss** [comment]
@tritium21 I created a new virtualenv without site packages to test, still the same problem. Here are the commands:

```
mkvirtualenv nikola --no-site-packages
workon nikola
pip install --upgrade "Nikola[extras]"
cd blog
nikola build
```

**Comment by tritium21** [comment]
I am still pretty sure that this is not a nikola bug (nikola doesn't even directly use any dbm module, I believe doit does.)  But either way the bsddb c extension was not built by the looks of it.

**Comment by hbprotoss** [comment]
problem solved by referring to [https://github.com/Homebrew/legacy-homebrew/issues/41875#issuecomment-122613926](https://github.com/Homebrew/legacy-homebrew/issues/41875#issuecomment-122613926)

**Comment by Kwpolska** [comment]
So, not our bug.

Thank you for bringing it to our attention though.
