### ISSUE TITLE
Importing a Wordpress.com site from xml file

### ISSUE THREAD

**Issue by darkomen** [getnikola/nikola#2340]
Hi, I downloaded a xml file from my wordpress.com site.
I executed the following command:
$ nikola import_wordpress homedarkomen.wordpress.2016-05-09.001.xml 
It's start to import the site, but I get the following error:
```
Traceback (most recent call last):
  File "/Users/darkomen/anaconda/lib/python3.5/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/Users/darkomen/anaconda/lib/python3.5/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/Users/darkomen/anaconda/lib/python3.5/site-packages/nikola/plugin_categories.py", line 124, in execute
    return self._execute(options, args)
  File "/Users/darkomen/anaconda/lib/python3.5/site-packages/nikola/plugins/command/import_wordpress.py", line 355, in _execute
    self.import_posts(channel)
  File "/Users/darkomen/anaconda/lib/python3.5/site-packages/nikola/plugins/command/import_wordpress.py", line 1057, in import_posts
    self.process_item_if_attachment(item)
  File "/Users/darkomen/anaconda/lib/python3.5/site-packages/nikola/plugins/command/import_wordpress.py", line 1020, in process_item_if_attachment
    data = self.import_attachment(item, wordpress_namespace)
  File "/Users/darkomen/anaconda/lib/python3.5/site-packages/nikola/plugins/command/import_wordpress.py", line 563, in import_attachment
    add('aperture', b'aperture', is_float=True, ignore_zero=True)
  File "/Users/darkomen/anaconda/lib/python3.5/site-packages/nikola/plugins/command/import_wordpress.py", line 547, in add
    if wp_key in image_meta:
TypeError: argument of type 'bool' is not utterable
```
And it stopped the importation.
How can I solve this problem?

**Comment by ralsina** [comment]
If this happened with latest Nikola version, we probably can't debug this without a copy of your dump.

**Comment by darkomen** [comment]
I have Nikola v7.7.8
I think that my problem came from my own blog. I have exported a xml file with three months and the exportation is ok.
Maybe in some post I have some error.

I'm going to close the issue due it's a user problem.

Sorry

**Comment by ralsina** [comment]
Not necessarily! The wordpress XML format is a strange beast, and we are probably doing Something Wrong (tm) with one of your posts. If you figure out which one it is, feel free to post at least that XML fragment here and reopen?

**Comment by darkomen** [comment]
ook! I upload files.zip with two files:
-xml: xml reduced file
-error: error dump

I executed:

> $ nikola import_wordpress febrero.xml

and I get the content in error.txt

I hope it will be useful

regards.

[files.zip](https://github.com/getnikola/nikola/files/256047/files.zip)

**Comment by ralsina** [comment]
Using nikola from github master, febrero.xml imports fine. Doesn't build because of conflicting tag names tho:

```
[2016-05-30T16:07:21Z] ERROR: Nikola: You have tags that are too similar: programacion and /Programación
[2016-05-30T16:07:21Z] ERROR: Nikola: Tag programacion is used in: posts/2012/06/27/programando-una-libreria-para-arduino.md
[2016-05-30T16:07:21Z] ERROR: Nikola: Tag /Programación is used in: posts/2012/06/27/programando-una-libreria-para-arduino.md
[2016-05-30T16:07:21Z] ERROR: Nikola: You have tags that are too similar: clone wars and /Clone wars
[2016-05-30T16:07:21Z] ERROR: Nikola: Tag clone wars is used in: posts/2012/02/05/clonewars-montaje-de-eje-x-en-iteracion2.md
[2016-05-30T16:07:21Z] ERROR: Nikola: Tag /Clone wars is used in: posts/2012/10/12/como-trabajar-con-un-fork-en-github.md, posts/2012/01/20/potato-nuevo-proyecto.md, posts/2012/02/05/clonewars-montaje-de-eje-x-en-iteracion2.md
[2016-05-30T16:07:21Z] ERROR: Nikola: You have tags that are too similar: electronica and Electrónica
[2016-05-30T16:07:21Z] ERROR: Nikola: Tag electronica is used in: posts/2012/02/25/processing-controlando-servos-desde-processing.md
[2016-05-30T16:07:21Z] ERROR: Nikola: Tag Electrónica is used in: posts/2012/06/27/programando-una-libreria-para-arduino.md, posts/2012/01/28/wiki-anadido-tutorial-trucar-servos.md, posts/2012/01/29/comunicaciones-entre-arduino-y-skymega.md, posts/2012/02/05/clonewars-montaje-de-eje-x-en-iteracion2.md
[2016-05-30T16:07:21Z] ERROR: Nikola: You have tags that are too similar: processing and /Processing
[2016-05-30T16:07:21Z] ERROR: Nikola: Tag processing is used in: posts/2012/02/25/processing-controlando-servos-desde-processing.md
[2016-05-30T16:07:21Z] ERROR: Nikola: Tag /Processing is used in: posts/2012/02/25/processing.md, posts/2012/02/25/processing-controlando-servos-desde-processing.md
[2016-05-30T16:07:21Z] ERROR: Nikola: You have tags that are too similar: manuales and /Manuales
[2016-05-30T16:07:21Z] ERROR: Nikola: Tag manuales is used in: posts/2012/02/18/tutorial-como-cambiar-hd-y-ram-en-un-macbookpro-unibody.md
[2016-05-30T16:07:21Z] ERROR: Nikola: Tag /Manuales is used in: posts/2012/06/27/programando-una-libreria-para-arduino.md, posts/2012/10/12/como-trabajar-con-un-fork-en-github.md, posts/2012/01/28/wiki-anadido-tutorial-trucar-servos.md, posts/2012/01/29/comunicaciones-entre-arduino-y-skymega.md
[2016-05-30T16:07:21Z] ERROR: Nikola: You have tags that are too similar: android and /Android
[2016-05-30T16:07:21Z] ERROR: Nikola: Tag android is used in: posts/2011/08/13/subir-fotos-desde-android-a-google.md
[2016-05-30T16:07:21Z] ERROR: Nikola: Tag /Android is used in: posts/2011/08/13/subir-fotos-desde-android-a-google.md
```

**Comment by felixfontein** [comment]
With Python 3.5, I get the same stack trace. Changing lines 542 to 544 in `import_wordpress.py` from
```
                    if meta_key in metadata:
                        image_meta = metadata[meta_key]
                        dst_meta = {}
```
to
```
                    if meta_key in metadata:
                        image_meta = metadata[meta_key]
                        if not image_meta:
                            continue
                        dst_meta = {}
```
fixes the problem. (`metadata` is `{b'hwstring_small': b"height='96' width='128'", b'width': 800, b'thumb': b'p1000749.miniatura.jpg', b'height': 600, b'image_meta': False, b'file': b'/home/wpcom/public_html/wp-content/blogs.dir/359/12536/files/2007/02/p1000749.jpg'}` for one image.)

About the collisions: part of the problem seems to be that in some cases, tags and categories are very similar (up to case, or special characters such as '/'). Since the import plugin converts categories to tags by default, this leads to the above errors. Specifying `--export-categories-as-categories` partially helps, as multiple categories per post are used. It's probably best to export it with conflicting tags and then to massage the output by hand. (Since these are text files, this isn't too hard with a bit of scripting / text editor magic.)

**Comment by ralsina** [comment]
@felixfontein thanks, I'll apply that change and close the issue.
