### ISSUE TITLE
Error while running `nikola build`

### ISSUE THREAD

**Issue by therealkbhat** [getnikola/nikola#2342]
Running `nikola build` gives me the following trace:
```text
Scanning posts...Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/usr/local/lib/python2.7/dist-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/usr/local/lib/python2.7/dist-packages/doit/cmd_base.py", line 380, in execute
    self, params, args)
  File "/usr/local/lib/python2.7/dist-packages/nikola/__main__.py", line 279, in load_tasks
    self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
  File "/usr/local/lib/python2.7/dist-packages/doit/loader.py", line 314, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/usr/local/lib/python2.7/dist-packages/doit/loader.py", line 28, in flat_generator
    for item in gen:
  File "/usr/local/lib/python2.7/dist-packages/nikola/nikola.py", line 1621, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/usr/local/lib/python2.7/dist-packages/nikola/nikola.py", line 1615, in flatten
    for t in task:
  File "/usr/local/lib/python2.7/dist-packages/nikola/plugins/task/indexes.py", line 73, in gen_tasks
    self.site.scan_posts()
  File "/usr/local/lib/python2.7/dist-packages/nikola/nikola.py", line 1719, in scan_posts
    timeline = p.plugin_object.scan()
  File "/usr/local/lib/python2.7/dist-packages/nikola/plugins/misc/scan_posts.py", line 97, in scan
    self.site.get_compiler(base_path)
  File "/usr/local/lib/python2.7/dist-packages/nikola/post.py", line 171, in __init__
    self.date = to_datetime(self.meta[self.default_lang]['date'], tzinfo)
  File "/usr/local/lib/python2.7/dist-packages/nikola/utils.py", line 855, in to_datetime
    raise ValueError('Unrecognized date/time: {0!r}'.format(value))
ValueError: Unrecognized date/time: u''
```

I did find out that `doit` only supports Python 3 now; however, despite using a Python 3 virtual environment and pip3 to install Nikola, package lookup is still taking place in the Python 2.7 location.

What am I doing wrong?

**Comment by Kwpolska** [comment]
This is not doit’s fault at all.

1. You’re not running inside the virtualenv. Recreate the virtualenv from scratch using Python 3 and make sure it’s always activated.
2. This is caused by an empty `date` field in a blog post. Please check your posts for any errors like those.

**Comment by therealkbhat** [comment]
@Kwpolska thanks! This helped. :)
