### ISSUE TITLE
Hit upon a incompatible libxml2.2.dylib issue

### ISSUE THREAD

**Issue by orsenthil** [getnikola/nikola#2392]
```
(py36venv) bellman-2:xtoinfinity.com senthil$ nikola new_post
Traceback (most recent call last):
  File "/Users/senthil/python3.6/py36venv/bin/nikola", line 7, in <module>
    from nikola.__main__ import main
  File "/Users/senthil/python3.6/py36venv/lib/python3.6/site-packages/nikola/__init__.py", line 35, in <module>
    from .nikola import Nikola  # NOQA
  File "/Users/senthil/python3.6/py36venv/lib/python3.6/site-packages/nikola/nikola.py", line 54, in <module>
    import lxml.etree
ImportError: dlopen(/Users/senthil/python3.6/py36venv/lib/python3.6/site-packages/lxml/etree.cpython-36dm-darwin.so, 2): Library not loaded: libxml2.2.dylib
  Referenced from: /Users/senthil/python3.6/py36venv/lib/python3.6/site-packages/lxml/etree.cpython-36dm-darwin.so
  Reason: Incompatible library version: etree.cpython-36dm-darwin.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
```

* This is on OSX El-capitan
* Python3.6
* Nikola installed using `pip`

Let me know if you need more information.

**Comment by orsenthil** [comment]
I was able to solve it with this.

http://stackoverflow.com/questions/23172384/lxml-runtime-error-reason-incompatible-library-version-etree-so-requires-vers

```
brew install libxml2
brew install libxslt
brew link libxml2 --force
brew link libxslt --force
```

Sorry, not a nikola problem.

**Comment by Kwpolska** [comment]
(It’s okay.)

**Comment by An3bi** [comment]
I had exactly the same issue. Thank you @orsenthil for posting the resolution as well.

**Comment by Kwpolska** [comment]
On a side note, I don’t have either of the two packages installed, and yet Nikola works (on Sierra).
