### ISSUE TITLE
post-list shortcode not working very well

### ISSUE THREAD

**Issue by fuzzy76** [getnikola/nikola#2408]
```{{% post-list slugs='one' all %}}```
results in:
```
TaskError - taskid:render_posts:cache/stories/one.html
PythonAction Error
Traceback (most recent call last):
  File "/Users/fuzzy76/repos/nikola/lib/python3.5/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/fuzzy76/repos/nikola/lib/python3.5/site-packages/nikola/post.py", line 493, in compile
    self.is_two_file),
  File "/Users/fuzzy76/repos/nikola/lib/python3.5/site-packages/nikola/plugins/compile/markdown/__init__.py", line 79, in compile_html
    output = apply_shortcodes(output, self.site.shortcode_registry, self.site, source)
  File "/Users/fuzzy76/repos/nikola/lib/python3.5/site-packages/nikola/shortcodes.py", line 313, in apply_shortcodes
    res = registry[name](*args, **kw)
  File "/Users/fuzzy76/repos/nikola/lib/python3.5/site-packages/nikola/plugins/compile/rest/post_list.py", line 234, in _do_post_list
    for post in filtered_timeline[start:stop:step]:
TypeError: slice indices must be integers or None or have an __index__ method
```
while
```{{% post-list start=0 stop=2 slugs='one' all %}}```
results in:
```
TaskError - taskid:render_posts:cache/stories/one.html
PythonAction Error
Traceback (most recent call last):
  File "/Users/fuzzy76/repos/nikola/lib/python3.5/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/fuzzy76/repos/nikola/lib/python3.5/site-packages/nikola/post.py", line 493, in compile
    self.is_two_file),
  File "/Users/fuzzy76/repos/nikola/lib/python3.5/site-packages/nikola/plugins/compile/markdown/__init__.py", line 79, in compile_html
    output = apply_shortcodes(output, self.site.shortcode_registry, self.site, source)
  File "/Users/fuzzy76/repos/nikola/lib/python3.5/site-packages/nikola/shortcodes.py", line 313, in apply_shortcodes
    res = registry[name](*args, **kw)
TypeError: _do_post_list() got multiple values for argument 'start'
```

**Comment by fuzzy76** [comment]
I guess #1707 isn't quite done yet, but thought you'd like a separate issue for this.

**Comment by Kwpolska** [comment]
It also seems that we’d need to move the logic (eg. for categories and sections) out of PostList.run() and into `_do_post_list()`

**Comment by ralsina** [comment]
@Kwpolska yep. I am not that familiar with post-list, so feel free to take over, I have not looked at it much yet.

**Comment by Kwpolska** [comment]
1. Invalid syntax, try this:
       {{% post-list slugs='one' all=True %}}
2. `start`/`stop` didn’t make sure it was integers, fixed
3. `all` was internally called `show_all`, fixed
4. `all` is deprecated, use `type: all` instead

(`post-list-shortcode-redux` will become a PR soon-ish)

**Comment by Kwpolska** [comment]
The directive seems to work, but it doesn’t do dependencies right now. Opened #2412 for the dependencies part and #2413 as a PR with all the changes.
