### ISSUE TITLE
Race condition with post scanning and galleries?

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2419]
This happens **randomly** with the recent changes (#2417):

```pytb
Traceback (most recent call last):
  File "/home/kwpolska/virtualenvs/nikola-py3/lib/python3.5/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/home/kwpolska/virtualenvs/nikola-py3/lib/python3.5/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/kwpolska/virtualenvs/nikola-py3/lib/python3.5/site-packages/doit/cmd_base.py", line 380, in execute
    self, params, args)
  File "/home/kwpolska/git/nikola/nikola/__main__.py", line 279, in load_tasks
    self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
  File "/home/kwpolska/virtualenvs/nikola-py3/lib/python3.5/site-packages/doit/loader.py", line 314, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/kwpolska/virtualenvs/nikola-py3/lib/python3.5/site-packages/doit/loader.py", line 28, in flat_generator
    for item in gen:
  File "/home/kwpolska/git/nikola/nikola/nikola.py", line 1714, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/home/kwpolska/git/nikola/nikola/nikola.py", line 1708, in flatten
    for t in task:
  File "/home/kwpolska/git/nikola/nikola/plugins/task/galleries.py", line 251, in gen_tasks
    fpost = self.parse_index(path, input_folder, output_folder)
  File "/home/kwpolska/git/nikola/nikola/plugins/task/galleries.py", line 420, in parse_index
    self.site.post_per_input_file[index_path] = post
AttributeError: 'Nikola' object has no attribute 'post_per_input_file'
```

@ralsina, what could be causing that? Why might `scan_posts` be done before or after `galleries` randomly?

**Comment by ralsina** [comment]
Well, order is not deterministic, unless there is a dependency. If
galleries needs scan_posts, it should require it.
