### ISSUE TITLE
Nikola 7.8.0: post-list directive generates a PythonAction error

### ISSUE THREAD

**Issue by richieadler** [getnikola/nikola#2489]
After updating to 7.8.0, I get the following error in pages with the post-list directive:
````python
PythonAction Error
Traceback (most recent call last):
  File "c:\prog\python35\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "c:\prog\python35\lib\site-packages\nikola\post.py", line 520, in compile
    self.is_two_file)
  File "c:\prog\python35\lib\site-packages\nikola\plugins\compile\rest\__init__.py", line 104, in compile_html
    output, error_level, deps = self.compile_html_string(data, source, is_two_file)
  File "c:\prog\python35\lib\site-packages\nikola\plugins\compile\rest\__init__.py", line 86, in compile_html_string
    no_title_transform=self.site.config.get('NO_DOCUTILS_TITLE_TRANSFORM', False))
  File "c:\prog\python35\lib\site-packages\nikola\plugins\compile\rest\__init__.py", line 295, in rst2html
    pub.publish(enable_exit_status=enable_exit_status)
  File "c:\prog\python35\lib\site-packages\docutils\core.py", line 217, in publish
    self.settings)
  File "c:\prog\python35\lib\site-packages\docutils\readers\__init__.py", line 72, in read
    self.parse()
  File "c:\prog\python35\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\__init__.py", line 189, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    input_source=document['source'])
  File "c:\prog\python35\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\prog\python35\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 2743, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\prog\python35\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\prog\python35\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 1255, in bullet
    blank_finish=blank_finish)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 318, in nested_list_parse
    node=node, match_titles=match_titles)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\prog\python35\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\prog\python35\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 2496, in bullet
    listitem, blank_finish = self.list_item(match.end())
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 1271, in list_item
    node=listitem)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\prog\python35\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\prog\python35\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 1248, in bullet
    i, blank_finish = self.list_item(match.end())
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 1271, in list_item
    node=listitem)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\prog\python35\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\prog\python35\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 1248, in bullet
    i, blank_finish = self.list_item(match.end())
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 1271, in list_item
    node=listitem)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\prog\python35\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\prog\python35\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 2316, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 2328, in explicit_construct
    return method(self, expmatch)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 2071, in directive
    directive_class, match, type_name, option_presets)
  File "c:\prog\python35\lib\site-packages\docutils\parsers\rst\states.py", line 2120, in run_directive
    result = directive_instance.run()
  File "c:\prog\python35\lib\site-packages\nikola\plugins\compile\rest\post_list.py", line 176, in run
    all, lang, template, sort, state=self.state, site=self.site, date=date)
ValueError: not enough values to unpack (expected 2, got 0)
````

**Comment by Kwpolska** [comment]
Hm, I can’t reproduce on OS X. Perhaps this is Windows-specific?

But first, please paste a post that causes this crash, and make sure you have an up-to-date version of docutils (just in case).

**Comment by Kwpolska** [comment]
Can’t reproduce on Windows either. I’m using the simplest possible list:

```rst
.. post-list::
   :stop: 5
```

**Comment by richieadler** [comment]
Docutils complies with the requirement ``docutils>=0.12`` according to pip.

All the ``post-list`` directives are in the form

````rest
  .. post-list::
     :tags: CA000
     :sort: title
     :template: post_list_bullet.tmpl
     :all:
````
I added the file generating the error and, just in case, the partial template used for the post-list.

[lista.txt](https://github.com/getnikola/nikola/files/447126/lista.txt)
[post_list_bullet.tmpl.zip](https://github.com/getnikola/nikola/files/447129/post_list_bullet.tmpl.zip)

**Comment by Kwpolska** [comment]
A little typo and empty lists meant a crash. Fixed in master, but can be trivially backported to your install.

**Comment by richieadler** [comment]
Backported the change, it solved the issue. Thanks!
