### ISSUE TITLE
boolean is not iterable while trying to run nikola build

### ISSUE THREAD

**Issue by ericcotelnu** [getnikola/nikola#2500]
Between today and yesterday I suddenly can't build (see below). I've added some metadata to some posts, a .. section: and now it bugs out.

I try to run it on the demo site, and it's OK. I add my current posts to it, it's also OK except it buggers out on generating the author. I suspect some 3rd party plugins I installed.

```
Scanning posts.........done!
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/usr/local/lib/python3.5/dist-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/usr/local/lib/python3.5/dist-packages/doit/cmd_base.py", line 380, in execute
    self, params, args)
  File "/usr/local/lib/python3.5/dist-packages/nikola/__main__.py", line 279, in load_tasks
    self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
  File "/usr/local/lib/python3.5/dist-packages/doit/loader.py", line 314, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/usr/local/lib/python3.5/dist-packages/doit/loader.py", line 28, in flat_generator
    for item in gen:
  File "/usr/local/lib/python3.5/dist-packages/nikola/nikola.py", line 1795, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/usr/local/lib/python3.5/dist-packages/nikola/nikola.py", line 1790, in flatten
    for ft in flatten(t):
  File "/usr/local/lib/python3.5/dist-packages/nikola/nikola.py", line 1789, in flatten
    for t in task:
  File "/usr/local/lib/python3.5/dist-packages/nikola/nikola.py", line 2339, in generic_index_renderer
    num_pages, False)
  File "/usr/local/lib/python3.5/dist-packages/nikola/plugins/task/indexes.py", line 102, in page_link
    lang, self.site, force_addition, extension)
  File "/usr/local/lib/python3.5/dist-packages/nikola/utils.py", line 1655, in adjust_name_for_index_link
    link = adjust_name_for_index_path_list(name.split('/'), i, displayed_i, lang, site, force_addition, extension)
  File "/usr/local/lib/python3.5/dist-packages/nikola/utils.py", line 1626, in adjust_name_for_index_path_list
    for entry in path_schema:
TypeError: 'bool' object is not iterable
```

**Comment by ericcotelnu** [comment]
I tried removing all plugins I installed, still same error.

**Comment by ericcotelnu** [comment]
OK, figured it out, first I commented out all the 'INDEXES' settings, then disabled the NAVIGATION_LINKS, it then worked. In fact I did have that enabled, as well. It wasn't choking on it before, until I was working on the nav links.

**Comment by ericcotelnu** [comment]
Thank you BTW, for your patience. I know I can be annoying to some people. I try not to be :).

**Comment by ericcotelnu** [comment]
I'd like to suggest catching that index thing and spitting out a clearer msg like: "Check your INDEX settings you silly person! :P". -- albeit in an a lot more professional way, of course.

**Comment by Kwpolska** [comment]
We can’t make any better message. We can’t check *every* setting just because someone might comment too much.

There might be some bad default value though. If you can find which setting was missing, that could be fixed. Otherwise, no.
