### ISSUE TITLE
Improve verbose output for build process

### ISSUE THREAD

**Issue by ncouture** [getnikola/nikola#2505]
Here is an example where verbosity fails to help me resolve an issue when it most-likely could:
```
$ nikola check -v -f
Scanning posts...Traceback (most recent call last):
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/utils.py", line 871, in to_datetime
    value = dateutil.parser.parse(value)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/dateutil/parser.py", line 1164, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/dateutil/parser.py", line 558, in parse
    raise ValueError("String does not contain a date.")
ValueError: String does not contain a date.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/plugin_categories.py", line 129, in execute
    return self._execute(options, args)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/plugins/command/check.py", line 175, in _execute
    failure |= self.scan_files()
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/plugins/command/check.py", line 392, in scan_files
    only_on_output, only_on_input = real_scan_files(self.site, self.cache)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/plugins/command/check.py", line 76, in real_scan_files
    for fname in _call_nikola_list(site, cache)[0]:
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/plugins/command/check.py", line 56, in _call_nikola_list
    for task in generate_tasks('render_site', site.gen_tasks('render_site', "Task", '')):
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/doit/loader.py", line 314, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/doit/loader.py", line 28, in flat_generator
    for item in gen:
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/nikola.py", line 1795, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/nikola.py", line 1789, in flatten
    for t in task:
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/plugins/task/sources.py", line 49, in gen_tasks
    self.site.scan_posts()
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/nikola.py", line 1894, in scan_posts
    timeline = p.plugin_object.scan()
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/plugins/misc/scan_posts.py", line 97, in scan
    self.site.get_compiler(base_path)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/post.py", line 179, in __init__
    self.date = to_datetime(self.meta[self.default_lang]['date'], tzinfo)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/utils.py", line 876, in to_datetime
    raise ValueError('Unrecognized date/time: {0!r}'.format(value))
ValueError: Unrecognized date/time: ''
```
Ideally the verbose ouput of the build process would print the file it is processing to that its user can identify which one results in error(s).

**Comment by ralsina** [comment]
Fixed, now, before all the backtrace, you will see

```
Scanning posts.[2016-09-24T22:54:42Z] ERROR: scan_posts: Error reading post posts/foo.rst
```

in red.
