### ISSUE TITLE
Should remove site dir from PYTHONPATH.

### ISSUE THREAD

**Issue by kayhayen** [getnikola/nikola#2520]
This is with latest version from PyPI. I automatically update, I think this started a while a go:

```
Traceback (most recent call last):
  File "/home/nuitka-buildslave/nikola-sandbox/bin/nikola", line 11, in <module>
    sys.exit(main())
  File "/home/nuitka-buildslave/nikola-sandbox/lib/python3.4/site-packages/nikola/__main__.py", line 167, in main
    site = Nikola(**config)
  File "/home/nuitka-buildslave/nikola-sandbox/lib/python3.4/site-packages/nikola/nikola.py", line 901, in __init__
    self._set_global_context_from_data()
  File "/home/nuitka-buildslave/nikola-sandbox/lib/python3.4/site-packages/nikola/nikola.py", line 1141, in _set_global_context_from_data
    data = utils.load_data(fname)
  File "/home/nuitka-buildslave/nikola-sandbox/lib/python3.4/site-packages/nikola/utils.py", line 1933, in load_data
    with io.open(path, 'r', encoding='utf8') as inf:
IsADirectoryError: [Errno 21] Is a directory: 'data/2.7'
Traceback (most recent call last):
  File "./update.py", line 754, in <module>
    runNikolaCommand("build")

```

In the site directory, there is a data with well, data from my stuff. The code name "load_data" makes me assume, that Nikola is confused into thinking, it is its own "data", which won't be true. As you read "conf.py" from the directory, I think you need to drop it afterwards, so as to not be confused.

Yours,
Kay

**Comment by Kwpolska** [comment]
Nikola now uses the data/ directory. You'd have to rename yours, or we
could add a feature to disable the data file feature. (It adds the contents
of json etc. files in data/ to global context)

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by kayhayen** [comment]
Renaming it will be OK for me.
