### ISSUE TITLE
Cleanup CLI behaviour

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2539]
It's pretty easy to make Nikola crash in random ways.

For example:

```
$ mkdir foo
$ cd foo
$ touch conf.py
$ echo foobar > plugins
$ nikola
Traceback (most recent call last):
  File "/home/ralsina/.virtualenvs/nikola/bin/nikola", line 9, in <module>
    load_entry_point('Nikola', 'console_scripts', 'nikola')()
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/__main__.py", line 159, in main
    with open('plugins/__init__.py', 'w') as fh:
NotADirectoryError: [Errno 20] Not a directory: 'plugins/__init__.py'
```

We could make it more robust, and make it less crazy when it does crash.

**Comment by Kwpolska** [comment]
That issue is pretty vague, I hope you have a list of things that can break — and I hope you aren’t *too* protective of PEBKAC errors.

**Comment by ralsina** [comment]
Closing, let's fix these when they pop up.
