### ISSUE TITLE
Weird crash with AUTHOR_PAGES_ARE_INDEXES = True and commas in names

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2600]
Reported by charlesay on IRC. To reproduce: set `AUTHOR_PAGES_ARE_INDEXES = True` and create two posts with dfiferent authors.

```pytb
TaskError - taskid:render_taxonomies:output/authors/foo-baz-foo-barbaz.html
PythonAction Error
Traceback (most recent call last):
  File "/Users/kwpolska/virtualenvs/nikola/lib/python3.5/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/kwpolska/git/nikola/nikola/nikola.py", line 1376, in render_template
    template_name, None, local_context)
  File "/Users/kwpolska/git/nikola/nikola/plugins/template/mako.py", line 117, in render_template
    data = template.render_unicode(**context)
  File "/Users/kwpolska/virtualenvs/nikola/lib/python3.5/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/kwpolska/virtualenvs/nikola/lib/python3.5/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/kwpolska/virtualenvs/nikola/lib/python3.5/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/kwpolska/virtualenvs/nikola/lib/python3.5/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/Volumes/RAMDisk/n/cache/.mako.tmp/base.tmpl.py", line 76, in render_body
    context['self'].extra_head(**pageargs)
  File "/Volumes/RAMDisk/n/cache/.mako.tmp/authorindex.tmpl.py", line 72, in render_extra_head
    if len(tranlations) > 1 and generate_atom:
TypeError: object of type 'Undefined' has no len()
```

WTF?!

**Comment by Kwpolska** [comment]
Oh, wait. There was a typo in `tranSlations`; fixed in master.

The funniest part is, **this never worked**.

**Comment by felixfontein** [comment]
...and I first thought that this was caused by the taxonomy PR when I glanced over the issue's description...

**Comment by Kwpolska** [comment]
I was going *WTF?!* for about 15 minutes before I noticed that typo.
