### ISSUE TITLE
Nikola auto causes exception, but still runs(?)

### ISSUE THREAD

**Issue by stefanos82** [getnikola/nikola#2633]
I run `nikola auto` and edited `conf.py` to change the navigation menu order according to my needs.

I waited for a couple of seconds to see my browser getting auto-refreshed and couldn't see anything.

I switched back to my terminal and saw this error message.

I haven't done anything to it.

Is this normal? Please advice, cheers.

```
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/stefanos/.virtualenvs/nikolaenv/lib/python3.5/site-packages/ws4py/manager.py", line 310, in run
    if not ws.once():
  File "/home/stefanos/.virtualenvs/nikolaenv/lib/python3.5/site-packages/ws4py/websocket.py", line 388, in once
    if not self.process(b):
  File "/home/stefanos/.virtualenvs/nikolaenv/lib/python3.5/site-packages/ws4py/websocket.py", line 445, in process
    self.close(s.closing.code, s.closing.reason)
  File "/home/stefanos/.virtualenvs/nikolaenv/lib/python3.5/site-packages/ws4py/websocket.py", line 189, in close
    self._write(self.stream.close(code=code, reason=reason).single(mask=self.stream.always_mask))
  File "/home/stefanos/.virtualenvs/nikolaenv/lib/python3.5/site-packages/ws4py/websocket.py", line 279, in _write
    self.sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

[2017-01-13T07:40:33Z] INFO: ws4py: Managing websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:43780]


```

**Comment by Kwpolska** [comment]
`nikola auto` can be unstable sometimes. If you get an exception, or it stops working, please restart it. I’m sorry, but this is beyond our control — ws4py sometimes acts weird.
