### ISSUE TITLE
Error in filters for html5lib_xmllike

### ISSUE THREAD

**Issue by ericcotelnu** [getnikola/nikola#2648]
If one put something like this:

```
FILTERS = {
  ".html": [filters.html5lib_xmllike],
```

in their conf.py, this happens:

in filters.py, line 221, slight change in dependency:

```
Scanning posts...............done!
[2017-01-25T04:39:19Z] INFO: deploy: => preset 'build'
[2017-01-25T04:39:19Z] INFO: deploy: ==> nikola build --backend=sqlite3
Scanning posts...............done!
.  render_listings:/[SNIP]/listings/index.html
########################################
                                          strip_whitespace=True,
TaskError - taskid:render_listings:[SNIP]/listings/index.html
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/doit/action.py", line 403, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/nikola/utils.py", line 940, in unlessLink
    action(target)
  File "/usr/local/lib/python3.5/dist-packages/nikola/filters.py", line 77, in f_in_file
    data = f(data)
  File "/usr/local/lib/python3.5/dist-packages/nikola/filters.py", line 225, in html5lib_xmllike
    escape_lt_in_attrs=True)
  File "/usr/lib/python3/dist-packages/html5lib/serializer.py", line 78, in serialize
    return s.render(walker(input), encoding)
  File "/usr/lib/python3/dist-packages/html5lib/serializer.py", line 323, in render
    return "".join(list(self.serialize(treewalker)))
  File "/usr/lib/python3/dist-packages/html5lib/serializer.py", line 263, in serialize
    raise ValueError("quote_attr_values must be one of: "
ValueError: quote_attr_values must be one of: 'always', 'spec', or 'legacy'
```

Personally I put 'always', but maybe this project should put 'spec'? Regardless, it says True currently in the code.

**Comment by ralsina** [comment]
This is because there was a change in html5lib 0.99999999/1.0b9:

```
Fix #11, avoiding the XSS bug potentially caused by serializer allowing attribute values to be escaped out of in old browser versions, changing the quote_attr_values option on serializer to take one of three values, “always” (the old True value), “legacy” (the new option, and the new default), and “spec” (the old False value, and the old default).
```

So, I guess to keep previous behaviour it should be always.
