### ISSUE TITLE
CATEGORY_ALLOW_HIERARCHIES does not work

### ISSUE THREAD

**Issue by dvzubarev** [getnikola/nikola#2681]
### Environment (if reporting a bug)

**Python Version:**
3.5.2

**Nikola Version:**
7.8.3 and master

**Operating System:**
Ubuntu 16.04

### Description:

I installed nikola in virtualenv from pip.
Then I set CATEGORY_ALLOW_HIERARCHIES to True in conf.py.
I created new post and edit category to be ".. category: code/python"
The error when building site:
```
TaskError - taskid:render_taxonomies:output/categories/cat_code/index.html
PythonAction Error
Traceback (most recent call last):
  File "/home/denin/Workspace/nikola/nikola3/lib/python3.5/site-packages/doit/action.py", line 403, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/denin/Workspace/nikola/nikola3/lib/python3.5/site-packages/nikola/nikola.py", line 1396, in render_template
    template_name, None, local_context)
  File "/home/denin/Workspace/nikola/nikola3/lib/python3.5/site-packages/nikola/plugins/template/mako.py", line 117, in render_template
    data = template.render_unicode(**context)
  File "/home/denin/Workspace/nikola/nikola3/lib/python3.5/site-packages/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/home/denin/Workspace/nikola/nikola3/lib/python3.5/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/denin/Workspace/nikola/nikola3/lib/python3.5/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/denin/Workspace/nikola/nikola3/lib/python3.5/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/denin/Workspace/nikola/nikola3/my_first_site/cache/.mako.tmp/base.tmpl.py", line 127, in render_body
    context['self'].content(**pageargs)
  File "/home/denin/Workspace/nikola/nikola3/my_first_site/cache/.mako.tmp/tag.tmpl.py", line 137, in render_content
    for name, link in subcategories:
ValueError: too many values to unpack (expected 2)
```

**Comment by Kwpolska** [comment]
Are you using a custom theme, or `bootstrap3`?

**Comment by dvzubarev** [comment]
I used the default one. THEME = "bootstrap3"
BTW, it works in 7.8.1
