### ISSUE TITLE
Problem with post-list and markdown when using date with <, >, <=, ...

### ISSUE THREAD

**Issue by gkabbe** [getnikola/nikola#2690]
### Environment (if reporting a bug)

**Python Version: 3.5.3**

**Nikola Version: Nikola v7.8.3**

**Operating System: Debian Jessie**

### Description:

When I try to use a post-list in markdown like this:

```
{{% post-list sections=vorlesungen sort=date template=postlistdir.tmpl date="day<now" %}}{{% /post-list %}}
```

nikola build fails with the following error:

```
TaskError - taskid:render_posts:cache/pages/index.html
PythonAction Error
Traceback (most recent call last):
  File "/scratch/user/programs/anaconda3/envs/nikola/lib/python3.5/site-packages/doit-0.30.3-py3.5.egg/doit/action.py", line 403, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/user/Downloads/nikola/nikola/post.py", line 554, in compile
    lang)
  File "/home/user/Downloads/nikola/nikola/plugins/compile/markdown/__init__.py", line 106, in compile
    output, shortcode_deps = self.compile_string(data, source, is_two_file, post)
  File "/home/user/Downloads/nikola/nikola/plugins/compile/markdown/__init__.py", line 95, in compile_string
    output, shortcode_deps = self.site.apply_shortcodes(output, filename=source_path, with_dependencies=True, extra_context={'post': post})
  File "/home/user/Downloads/nikola/nikola/nikola.py", line 1657, in apply_shortcodes
    return shortcodes.apply_shortcodes(data, self.shortcode_registry, self, filename, lang=lang, with_dependencies=with_dependencies, extra_context=extra_context)
  File "/home/user/Downloads/nikola/nikola/shortcodes.py", line 320, in apply_shortcodes
    res = f(*args, **kw)
  File "/home/user/Downloads/nikola/nikola/plugins/compile/rest/post_list.py", line 277, in _do_post_list
    filtered_timeline = [p for p in filtered_timeline if date_in_range(date, p.date, now=_now)]
  File "/home/user/Downloads/nikola/nikola/plugins/compile/rest/post_list.py", line 277, in <listcomp>
    filtered_timeline = [p for p in filtered_timeline if date_in_range(date, p.date, now=_now)]
  File "/home/user/Downloads/nikola/nikola/packages/datecond/__init__.py", line 75, in date_in_range
    item.strip()).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

I think the problem is that the function date_in_range does not get the "raw" date_range parameter (which in this case should be day<now), but instead the special character gets escaped before, so it looks like "day\&lt;now".)
The quickest fix would probably be to add "\&gt;", "\&lt;" and so on to CLAUSE and OPERATORS in nikola/packages/datecond/\_\_init\_\_.py, but it is probably a bit hackish...

**Comment by Kwpolska** [comment]
We could change it in the post list code itself, or perhaps globally for all shortcodes, as part of the parser — would the latter work well? (@felixfontein @ralsina)

**Comment by felixfontein** [comment]
The only solution which works well with all kinds of compilers would be to first replace shortcodes by unique random identifiers, then to run the compiler, and finally to replace the identifiers with the evaluated shortcodes. Everything else is just a hacky mess.
(Except if you make the compiler shortcode-aware. But that doesn't work for most of them.)

**Comment by ralsina** [comment]
No idea, I don't understand the shortcodes implementation nowadays.

**Comment by Kwpolska** [comment]
I‘d say to special-case post lists. Other shortcodes may be better suited by lt/gt and may be unaware of any API changes…
