### ISSUE TITLE
Bug in taxonomy link handler

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2726]
Steps to reproduce:

* checkout from master
* nikola init -q foo
* cd foo
* nikola new_post foo

Change navigation_links to contain

        ("link://category", "Tags"),

And voilá:

```
TaskError - taskid:render_taxonomies:output/index.html
PythonAction Error
Traceback (most recent call last):
  File "/home/ralsina/.virtualenvs/nikola/lib/python3.5/site-packages/doit/action.py", line 403, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/ralsina/.virtualenvs/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1426, in render_template
    self.rewrite_links(doc, src, context['lang'], url_type)
  File "/home/ralsina/.virtualenvs/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1440, in rewrite_links
    doc.rewrite_links(lambda dst: self.url_replacer(src, dst, lang, url_type), resolve_base_href=False)
  File "/home/ralsina/.virtualenvs/nikola/lib/python3.5/site-packages/lxml/html/__init__.py", line 622, in rewrite_links
    new_link = link_repl_func(link.strip())
  File "/home/ralsina/.virtualenvs/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1440, in <lambda>
    doc.rewrite_links(lambda dst: self.url_replacer(src, dst, lang, url_type), resolve_base_href=False)
  File "/home/ralsina/.virtualenvs/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1489, in url_replacer
    dst = self.link(dst_url.netloc, dst_url.path.lstrip('/'), lang, **link_kwargs)
  File "/home/ralsina/.virtualenvs/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1879, in link
    url = self.path(*args, is_link=True, **kwargs)
  File "/home/ralsina/.virtualenvs/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1798, in path
    path = self.path_handlers[kind](name, lang, **kwargs)
  File "/home/ralsina/.virtualenvs/nikola/lib/python3.5/site-packages/nikola/plugins/misc/taxonomies_classifier.py", line 282, in _taxonomy_path
    result = taxonomy.get_path(taxonomy.extract_hierarchy(name), lang, dest_type=dest_type)
  File "/home/ralsina/.virtualenvs/nikola/lib/python3.5/site-packages/nikola/plugins/task/categories.py", line 132, in get_path
    return [_f for _f in [self.site.config['CATEGORY_PATH'](lang)] if _f] + self.slugify_category_name(classification, lang), 'auto'
  File "/home/ralsina/.virtualenvs/nikola/lib/python3.5/site-packages/nikola/plugins/task/categories.py", line 125, in slugify_category_name
    result[0] = self.site.config['CATEGORY_PREFIX'] + result[0]
IndexError: list index out of range
```

**Comment by ralsina** [comment]
So, the problem seems to be that the categories taxonomy doesn't support "link://category" but I should use "link://category_index".

In any case the way it flames out is pretty impressive, so adding a small error handler there.

**Comment by felixfontein** [comment]
Did `link://category` ever work?

And yes, a small error handler would be nice. Do you want to do that, or should I add it?

**Comment by felixfontein** [comment]
Ah, I didn't see you already worked on this in #2727.

**Comment by ralsina** [comment]
@felixfontein perhaps it could be handled generically in the taxonomy plugin?

As in: "whenever called without  a path use the _index handler" ... not sure how it could be done tho, taxonomy code is a bit over my head currently :-)

**Comment by felixfontein** [comment]
Depending on the taxonomy, no path == empty path == totally valid input. For most hierarchical taxonomies this is the case. Also, for the `indexes` taxonomy, no path means the default page of the main index. Adding proper support for this would potentially break user-defined taxonomies, so I'd prefer if we improve error handling over adding shortcuts.
