### ISSUE TITLE
Unable to use Jupyter Notebook compiler

### ISSUE THREAD

**Issue by sebelk** [getnikola/nikola#2733]
### Environment (if reporting a bug)

**Python Version: Python 3.5.3**

**Nikola Version: Nikola v7.8.4**

**Operating System: Fedora 25 x86_64**

### Description:

I cannot enable Jupyter notebook compiler, this is the output of `nikola -V`  
```

[2017-04-23T16:38:22Z] ERROR: yapsy: Unable to import plugin: /usr/lib/python3.5/site-packages/nikola/plugins/compile/ipynb
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib64/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3.5/site-packages/nikola/plugins/compile/ipynb.py", line 36, in <module>
    from nbconvert.exporters import HTMLExporter
  File "/usr/lib/python3.5/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/usr/lib/python3.5/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
    from .base import (export, get_exporter,
  File "/usr/lib/python3.5/site-packages/nbconvert/exporters/base.py", line 16, in <module>
    from .exporter import Exporter
  File "/usr/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 47, in <module>
    class Exporter(LoggingConfigurable):
  File "/usr/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 55, in Exporter
    help="Extension of the file that should be written to disk"
AttributeError: 'FilenameExtension' object has no attribute 'tag'
Nikola v7.8.4
```
Please: could you help me? I can't use .ipynb files :(

Thanks in advance!

**Comment by Kwpolska** [comment]
Did you install Jupyter from dnf? What does `jupyter --version` say?

**Comment by sebelk** [comment]
Thanks @Kwpolska yup, I had installed jupyter from dnf. So, I've removed and now ipynb compiler works.
Greetings

**Comment by Kwpolska** [comment]
Perhaps we could make things clearer here? We have some support code for older versions, but at the same time, requirements.txt says >=4.0.

**Comment by ralsina** [comment]
@Kwpolska you mean a doc fix? Is there anything left to do in this issue?

**Comment by Kwpolska** [comment]
We should drop code that provides support for older ipynb/jupyter versions from ipynb.py.
