### ISSUE TITLE
Installation instructions don't work on ubuntu 14.04 (without minor mods)

### ISSUE THREAD

**Issue by cheshirekow** [getnikola/nikola#2754]
### Environment (if reporting a bug)

**Python Version:** 3.4.3
**Nikola Version:** 7.8.4
**Operating System:** Ubuntu 14.04

### Description:

I followed the instructions for installing `nikola` from https://getnikola.com/getting-started.html and the installation failed. I'm not sure if it's the `nikola` package or one of it's dependencies but there seems to be a dependency problem. I had to manually install the `appdirs packaging six` pip packages in order for it to work. My installation recipe is:

```
sudo apt-get install libxml2-dev libxslt1-dev zlib1g-dev
sudo apt-get build-dep python3-lxml python3-pil
virtualenv -p /usr/bin/python3 nikola
cd nikola
source bin/activate
pip install appdirs six packaging
pip install "Nikola[extras]"
```

**Comment by Kwpolska** [comment]
“The installation failed” is unclear. Please post the *error output*.

**Comment by cheshirekow** [comment]
```
$ pip install "Nikola[extras]"
Downloading/unpacking Nikola[extras]
  Downloading Nikola-7.8.4-py2.py3-none-any.whl (2.4MB): 2.4MB downloaded
Downloading/unpacking natsort>=3.5.2 (from Nikola[extras])
  Downloading natsort-5.0.3-py2.py3-none-any.whl
Downloading/unpacking Yapsy>=1.11.223 (from Nikola[extras])
  Downloading Yapsy-1.11.223.tar.gz (80kB): 80kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/Yapsy/setup.py) egg_info for package Yapsy
    
    no previously-included directories found matching 'doc/_build'
Downloading/unpacking python-dateutil>=2.4.0 (from Nikola[extras])
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB): 194kB downloaded
Downloading/unpacking blinker>=1.3 (from Nikola[extras])
  Downloading blinker-1.4.tar.gz (111kB): 111kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/blinker/setup.py) egg_info for package blinker
    
Downloading/unpacking setuptools>=20.3 (from Nikola[extras])
  Downloading setuptools-35.0.2-py2.py3-none-any.whl (390kB): 390kB downloaded
Downloading/unpacking mako>=1.0.0 (from Nikola[extras])
  Downloading Mako-1.0.6.tar.gz (575kB): 575kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/mako/setup.py) egg_info for package mako
    
    warning: no files found matching '*.xml' under directory 'examples'
    warning: no files found matching '*.mako' under directory 'examples'
    warning: no files found matching 'distribute_setup.py'
    warning: no files found matching 'ez_setup.py'
    no previously-included directories found matching 'doc/build/output'
Downloading/unpacking unidecode>=0.04.16 (from Nikola[extras])
  Downloading Unidecode-0.04.20-py2.py3-none-any.whl (228kB): 228kB downloaded
Downloading/unpacking doit>=0.28.0 (from Nikola[extras])
  Downloading doit-0.30.3.tar.gz (235kB): 235kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/doit/setup.py) egg_info for package doit
    
Downloading/unpacking PyRSS2Gen>=1.1 (from Nikola[extras])
  Downloading PyRSS2Gen-1.1.tar.gz
  Running setup.py (path:/home/josh/Codes/nikola2/build/PyRSS2Gen/setup.py) egg_info for package PyRSS2Gen
    
Downloading/unpacking Pillow>=2.4.0 (from Nikola[extras])
  Downloading Pillow-4.1.1.tar.gz (11.3MB): 11.3MB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/Pillow/setup.py) egg_info for package Pillow
    
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
Downloading/unpacking docutils>=0.12 (from Nikola[extras])
  Downloading docutils-0.13.1-py3-none-any.whl (536kB): 536kB downloaded
Downloading/unpacking Pygments>=1.6 (from Nikola[extras])
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB): 841kB downloaded
Downloading/unpacking piexif>=1.0.3 (from Nikola[extras])
  Downloading piexif-1.0.12-py2.py3-none-any.whl
Downloading/unpacking requests>=2.2.0 (from Nikola[extras])
  Downloading requests-2.14.2-py2.py3-none-any.whl (560kB): 560kB downloaded
Downloading/unpacking logbook>=0.7.0 (from Nikola[extras])
  Downloading Logbook-1.0.0.tar.gz (178kB): 178kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/logbook/setup.py) egg_info for package logbook
    
Downloading/unpacking lxml>=3.3.5 (from Nikola[extras])
  Downloading lxml-3.7.3.tar.gz (3.8MB): 3.8MB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/lxml/setup.py) egg_info for package lxml
    Building lxml version 3.7.3.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    
    warning: no previously-included files found matching '*.py'
Downloading/unpacking husl>=4.0.2 (from Nikola[extras])
  Downloading husl-4.0.3.tar.gz
  Running setup.py (path:/home/josh/Codes/nikola2/build/husl/setup.py) egg_info for package husl
    
    warning: no files found matching 'LICENSE'
Downloading/unpacking ws4py==0.4.0 (from Nikola[extras])
  Downloading ws4py-0.4.0.tar.gz (40kB): 40kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/ws4py/setup.py) egg_info for package ws4py
    
Downloading/unpacking ghp-import2>=1.0.0 (from Nikola[extras])
  Downloading ghp_import2-1.0.1-py2.py3-none-any.whl
Downloading/unpacking Markdown>=2.4.0 (from Nikola[extras])
  Downloading Markdown-2.6.8.tar.gz (307kB): 307kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/Markdown/setup.py) egg_info for package Markdown
    
Downloading/unpacking phpserialize>=1.3 (from Nikola[extras])
  Downloading phpserialize-1.3.tar.gz
  Running setup.py (path:/home/josh/Codes/nikola2/build/phpserialize/setup.py) egg_info for package phpserialize
    
Downloading/unpacking typogrify>=2.0.4 (from Nikola[extras])
  Downloading typogrify-2.0.7.tar.gz
  Running setup.py (path:/home/josh/Codes/nikola2/build/typogrify/setup.py) egg_info for package typogrify
    
Downloading/unpacking notebook>=4.0.0 (from Nikola[extras])
  Downloading notebook-5.0.0-py2.py3-none-any.whl (6.9MB): 6.9MB downloaded
Downloading/unpacking micawber>=0.3.0 (from Nikola[extras])
  Downloading micawber-0.3.4.tar.gz
  Running setup.py (path:/home/josh/Codes/nikola2/build/micawber/setup.py) egg_info for package micawber
    
Downloading/unpacking Jinja2>=2.7.2 (from Nikola[extras])
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB): 340kB downloaded
Downloading/unpacking ipykernel>=4.0.0 (from Nikola[extras])
  Downloading ipykernel-4.6.1-py3-none-any.whl (104kB): 104kB downloaded
Downloading/unpacking watchdog==0.8.3 (from Nikola[extras])
  Downloading watchdog-0.8.3.tar.gz (83kB): 83kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/watchdog/setup.py) egg_info for package watchdog
    
    warning: no files found matching '*.h' under directory 'src'
Downloading/unpacking pygal>=2.0.0 (from Nikola[extras])
  Downloading pygal-2.3.1-py2.py3-none-any.whl (126kB): 126kB downloaded
Downloading/unpacking pyphen>=0.9.1 (from Nikola[extras])
  Downloading Pyphen-0.9.4-py2.py3-none-any.whl (1.9MB): 1.9MB downloaded
Downloading/unpacking webassets>=0.10.1 (from Nikola[extras])
  Downloading webassets-0.12.1.tar.gz (179kB): 179kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/webassets/setup.py) egg_info for package webassets
    
    warning: no files found matching 'run_tests.py'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching 'out.css' found under directory 'examples'
    warning: no previously-included files matching 'out.js' found under directory 'examples'
    no previously-included directories found matching 'examples/appengine-sdk'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.gitignore' found anywhere in distribution
    warning: no previously-included files matching '*.orig' found anywhere in distribution
    warning: no previously-included files matching 'webassets-cache/*' found anywhere in distribution
    warning: no previously-included files matching '.sass-cache/*' found anywhere in distribution
Downloading/unpacking six>=1.5 (from python-dateutil>=2.4.0->Nikola[extras])
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking packaging>=16.8 (from setuptools>=20.3->Nikola[extras])
  Downloading packaging-16.8-py2.py3-none-any.whl
Downloading/unpacking appdirs>=1.4.0 (from setuptools>=20.3->Nikola[extras])
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Downloading/unpacking MarkupSafe>=0.9.2 (from mako>=1.0.0->Nikola[extras])
  Downloading MarkupSafe-1.0.tar.gz
  Running setup.py (path:/home/josh/Codes/nikola2/build/MarkupSafe/setup.py) egg_info for package MarkupSafe
    
Downloading/unpacking cloudpickle (from doit>=0.28.0->Nikola[extras])
  Downloading cloudpickle-0.2.2-py2.py3-none-any.whl
Downloading/unpacking pyinotify (from doit>=0.28.0->Nikola[extras])
  Downloading pyinotify-0.9.6.tar.gz (60kB): 60kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/pyinotify/setup.py) egg_info for package pyinotify
    
Downloading/unpacking olefile (from Pillow>=2.4.0->Nikola[extras])
  Downloading olefile-0.44.zip (74kB): 74kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/olefile/setup.py) egg_info for package olefile
    
Downloading/unpacking smartypants>=1.8.3 (from typogrify>=2.0.4->Nikola[extras])
  Downloading smartypants-2.0.0-py2.py3-none-any.whl
Downloading/unpacking nbformat (from notebook>=4.0.0->Nikola[extras])
  Downloading nbformat-4.3.0-py2.py3-none-any.whl (154kB): 154kB downloaded
Downloading/unpacking traitlets>=4.2.1 (from notebook>=4.0.0->Nikola[extras])
  Downloading traitlets-4.3.2-py2.py3-none-any.whl (74kB): 74kB downloaded
Downloading/unpacking ipython-genutils (from notebook>=4.0.0->Nikola[extras])
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl
Downloading/unpacking jupyter-core (from notebook>=4.0.0->Nikola[extras])
  Downloading jupyter_core-4.3.0-py2.py3-none-any.whl (76kB): 76kB downloaded
Downloading/unpacking tornado>=4 (from notebook>=4.0.0->Nikola[extras])
  Downloading tornado-4.5.1.tar.gz (483kB): 483kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/tornado/setup.py) egg_info for package tornado
    
    no previously-included directories found matching 'docs/build'
    warning: no files found matching 'tornado/test/README'
Downloading/unpacking nbconvert (from notebook>=4.0.0->Nikola[extras])
  Downloading nbconvert-5.1.1-py2.py3-none-any.whl (372kB): 372kB downloaded
Downloading/unpacking jupyter-client (from notebook>=4.0.0->Nikola[extras])
  Downloading jupyter_client-5.0.1-py2.py3-none-any.whl (83kB): 83kB downloaded
Downloading/unpacking terminado>=0.3.3 (from notebook>=4.0.0->Nikola[extras])
  Downloading terminado-0.6.tar.gz
  Running setup.py (path:/home/josh/Codes/nikola2/build/terminado/setup.py) egg_info for package terminado
    
Downloading/unpacking ipython>=4.0.0 (from ipykernel>=4.0.0->Nikola[extras])
  Downloading ipython-6.0.0-py3-none-any.whl (736kB): 736kB downloaded
Downloading/unpacking PyYAML>=3.10 (from watchdog==0.8.3->Nikola[extras])
  Downloading PyYAML-3.12.tar.gz (253kB): 253kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/PyYAML/setup.py) egg_info for package PyYAML
    
Downloading/unpacking argh>=0.24.1 (from watchdog==0.8.3->Nikola[extras])
  Downloading argh-0.26.2-py2.py3-none-any.whl
Downloading/unpacking pathtools>=0.1.1 (from watchdog==0.8.3->Nikola[extras])
  Downloading pathtools-0.1.2.tar.gz
  Running setup.py (path:/home/josh/Codes/nikola2/build/pathtools/setup.py) egg_info for package pathtools
    
Downloading/unpacking pyparsing (from packaging>=16.8->setuptools>=20.3->Nikola[extras])
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB): 56kB downloaded
Downloading/unpacking jsonschema>=2.4,!=2.5.0 (from nbformat->notebook>=4.0.0->Nikola[extras])
  Downloading jsonschema-2.6.0-py2.py3-none-any.whl
Downloading/unpacking decorator (from traitlets>=4.2.1->notebook>=4.0.0->Nikola[extras])
  Downloading decorator-4.0.11-py2.py3-none-any.whl
Downloading/unpacking backports-abc>=0.4 (from tornado>=4->notebook>=4.0.0->Nikola[extras])
  Downloading backports_abc-0.5-py2.py3-none-any.whl
Downloading/unpacking entrypoints>=0.2.2 (from nbconvert->notebook>=4.0.0->Nikola[extras])
  Downloading entrypoints-0.2.2-py2.py3-none-any.whl
Downloading/unpacking mistune!=0.6 (from nbconvert->notebook>=4.0.0->Nikola[extras])
  Downloading mistune-0.7.4-py2.py3-none-any.whl
Downloading/unpacking pandocfilters>=1.4.1 (from nbconvert->notebook>=4.0.0->Nikola[extras])
  Downloading pandocfilters-1.4.1.tar.gz
  Running setup.py (path:/home/josh/Codes/nikola2/build/pandocfilters/setup.py) egg_info for package pandocfilters
    
Downloading/unpacking bleach (from nbconvert->notebook>=4.0.0->Nikola[extras])
  Downloading bleach-2.0.0-py2.py3-none-any.whl
Downloading/unpacking testpath (from nbconvert->notebook>=4.0.0->Nikola[extras])
  Downloading testpath-0.3-py2.py3-none-any.whl (82kB): 82kB downloaded
Downloading/unpacking pyzmq>=13 (from jupyter-client->notebook>=4.0.0->Nikola[extras])
  Downloading pyzmq-16.0.2.tar.gz (1.0MB): 1.0MB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/pyzmq/setup.py) egg_info for package pyzmq
    
    Generating grammar tables from /usr/lib/python3.4/lib2to3/Grammar.txt
    Generating grammar tables from /usr/lib/python3.4/lib2to3/PatternGrammar.txt
    warning: no files found matching 'tox.ini'
    no previously-included directories found matching 'docs/build'
    no previously-included directories found matching 'docs/gh-pages'
    warning: no previously-included files found matching 'bundled/zeromq/src/Makefile*'
    warning: no previously-included files found matching 'bundled/zeromq/src/platform.hpp'
    warning: no previously-included files found matching 'setup.cfg'
    warning: no previously-included files found matching 'zmq/libzmq*'
    warning: no previously-included files matching '.deps/*' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '.mailmap' found anywhere in distribution
    warning: no previously-included files matching 'Makefile.am' found anywhere in distribution
    warning: no previously-included files matching 'Makefile.in' found anywhere in distribution
Downloading/unpacking ptyprocess (from terminado>=0.3.3->notebook>=4.0.0->Nikola[extras])
  Downloading ptyprocess-0.5.1-py2.py3-none-any.whl
Downloading/unpacking prompt-toolkit>=1.0.4,<2.0.0 (from ipython>=4.0.0->ipykernel>=4.0.0->Nikola[extras])
  Downloading prompt_toolkit-1.0.14-py3-none-any.whl (248kB): 248kB downloaded
Downloading/unpacking pickleshare (from ipython>=4.0.0->ipykernel>=4.0.0->Nikola[extras])
  Downloading pickleshare-0.7.4-py2.py3-none-any.whl
Downloading/unpacking jedi>=0.10 (from ipython>=4.0.0->ipykernel>=4.0.0->Nikola[extras])
  Downloading jedi-0.10.2-py2.py3-none-any.whl (190kB): 190kB downloaded
Downloading/unpacking typing (from ipython>=4.0.0->ipykernel>=4.0.0->Nikola[extras])
  Downloading typing-3.6.1.tar.gz (66kB): 66kB downloaded
  Running setup.py (path:/home/josh/Codes/nikola2/build/typing/setup.py) egg_info for package typing
    
Downloading/unpacking simplegeneric>0.8 (from ipython>=4.0.0->ipykernel>=4.0.0->Nikola[extras])
  Downloading simplegeneric-0.8.1.zip
  Running setup.py (path:/home/josh/Codes/nikola2/build/simplegeneric/setup.py) egg_info for package simplegeneric
    
Downloading/unpacking pexpect (from ipython>=4.0.0->ipykernel>=4.0.0->Nikola[extras])
  Downloading pexpect-4.2.1-py2.py3-none-any.whl (55kB): 55kB downloaded
Downloading/unpacking html5lib>=0.99999999 (from bleach->nbconvert->notebook>=4.0.0->Nikola[extras])
  Downloading html5lib-0.999999999-py2.py3-none-any.whl (112kB): 112kB downloaded
Downloading/unpacking wcwidth (from prompt-toolkit>=1.0.4,<2.0.0->ipython>=4.0.0->ipykernel>=4.0.0->Nikola[extras])
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Downloading/unpacking webencodings (from html5lib>=0.99999999->bleach->nbconvert->notebook>=4.0.0->Nikola[extras])
  Downloading webencodings-0.5.1-py2.py3-none-any.whl
Installing collected packages: Nikola, natsort, Yapsy, python-dateutil, blinker, setuptools, mako, unidecode, doit, PyRSS2Gen, Pillow, docutils, Pygments, piexif, requests, logbook, lxml, husl, ws4py, ghp-import2, Markdown, phpserialize, typogrify, notebook, micawber, Jinja2, ipykernel, watchdog, pygal, pyphen, webassets, six, packaging, appdirs, MarkupSafe, cloudpickle, pyinotify, olefile, smartypants, nbformat, traitlets, ipython-genutils, jupyter-core, tornado, nbconvert, jupyter-client, terminado, ipython, PyYAML, argh, pathtools, pyparsing, jsonschema, decorator, backports-abc, entrypoints, mistune, pandocfilters, bleach, testpath, pyzmq, ptyprocess, prompt-toolkit, pickleshare, jedi, typing, simplegeneric, pexpect, html5lib, wcwidth, webencodings
  Running setup.py install for Yapsy
    
    no previously-included directories found matching 'doc/_build'
  Running setup.py install for blinker
    
  Found existing installation: setuptools 2.2
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for mako
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/josh/Codes/nikola2/lib/python3.4/site-packages/setuptools/__init__.py", line 10, in <module>
        from six.moves import filter, map
    ImportError: No module named 'six'
    Complete output from command /home/josh/Codes/nikola2/bin/python3 -c "import setuptools, tokenize;__file__='/home/josh/Codes/nikola2/build/mako/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2_t_wclk-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/josh/Codes/nikola2/include/site/python3.4:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/josh/Codes/nikola2/lib/python3.4/site-packages/setuptools/__init__.py", line 10, in <module>

    from six.moves import filter, map

ImportError: No module named 'six'

----------------------------------------
Cleaning up...
Command /home/josh/Codes/nikola2/bin/python3 -c "import setuptools, tokenize;__file__='/home/josh/Codes/nikola2/build/mako/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2_t_wclk-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/josh/Codes/nikola2/include/site/python3.4 failed with error code 1 in /home/josh/Codes/nikola2/build/mako
Storing debug log for failure in /tmp/tmpo4azxph4
```

**Comment by cheshirekow** [comment]
debug log:
[tmpo4azxph4.txt](https://github.com/getnikola/nikola/files/993713/tmpo4azxph4.txt)

**Comment by Kwpolska** [comment]
Before you install, `pip install -U pip setuptools wheel`. I’ll add it to the Getting Started guide (which also needs some updates), but note that `pip install -U` would work as well (though you’d need to compile lxml and PIllow. You don’t if you have an up-to-date copy of pip/setuptools/wheel).

**Comment by cheshirekow** [comment]
Thanks for taking a look and updating the docs. I'm glad to know the "right" way to resolve the problem (upgrade pip)
