### ISSUE TITLE
lxml.etree.ParserError: Document is empty

### ISSUE THREAD

**Issue by barrachri** [getnikola/nikola#2851]
### Environment (if reporting a bug)

**Python Version:**
3.6
**Nikola Version:**
7.8.8 and 7.8.9
**Operating System:**
OS X
### Description:
Till Nikola 7.8.7 everything works fine, but with the last 2 versions I get this error:
```
Scanning posts.......[2017-06-21T23:15:16Z] ERROR: scan_posts: Error reading post pages/index.html
[2017-06-21T23:15:16Z] ERROR: Nikola: Error reading timeline
[2017-06-21T23:15:16Z] ERROR: Nikola: Error loading tasks. An unhandled exception occurred.
Traceback (most recent call last):
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/doit/doit_cmd.py", line 167, in run
    return command.parse_execute(args)
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/doit/cmd_base.py", line 120, in parse_execute
    return self.execute(params, args)
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/doit/cmd_base.py", line 378, in execute
    self, params, args)
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/nikola/__main__.py", line 286, in load_tasks
    self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/doit/loader.py", line 313, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/doit/loader.py", line 26, in flat_generator
    for item in gen:
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/nikola/nikola.py", line 2059, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/nikola/nikola.py", line 2053, in flatten
    for t in task:
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/nikola/plugins/task/sources.py", line 49, in gen_tasks
    self.site.scan_posts()
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/nikola/nikola.py", line 2178, in scan_posts
    timeline = p.plugin_object.scan()
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/nikola/plugins/misc/scan_posts.py", line 101, in scan
    destination_base=destination_translatable
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/nikola/post.py", line 162, in __init__
    default_metadata, self.newstylemeta = get_meta(self, self.config['FILE_METADATA_REGEXP'], self.config['UNSLUGIFY_TITLES'])
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/nikola/post.py", line 1155, in get_meta
    compiler_meta = post.compiler.read_metadata(post, file_metadata_regexp, unslugify_titles, lang)
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/nikola/plugins/compile/html.py", line 100, in read_metadata
    doc = lxml.html.document_fromstring(data)
  File "/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/lxml/html/__init__.py", line 765, in document_fromstring
    "Document is empty")
lxml.etree.ParserError: Document is empty
```

This is the page/index.html

```
<!--
.. title: Jupyter Notebooks made easy
.. slug: index
.. date: 2017-01-03 19:45:49 UTC+01:00
.. tags:
.. template: index-cassiny.tmpl
.. category:
.. link:
.. description: Cassiny.io is a galaxy level platform to launch Jupyter Notebooks
.. type: text
.. text_title:
.. sub_title:
.. image:
-->
```

**Comment by Kwpolska** [comment]
To fix this, you can manually apply dd5e8a72 to
`/Users/christianbarra/miniconda3/envs/www.cassiny.io/lib/python3.6/site-packages/nikola/plugins/compile/html.py`. (Or you can just avoid empty posts)
