### ISSUE TITLE
Struggling with github_deploy on windows cmd

### ISSUE THREAD

**Issue by gtopba** [getnikola/nikola#2855]
### Environment
Python Version: 3.6 64 bit

Nikola Version: 7.8.9

Operating System: Windows 7

### Description:
I cannot deploy the demo site onto Github Pages. It is pretty fast generating the static site, but I'm struggling to deploy it more than 24 hours. I have successfully tested with `nikola serve --browser`. After installing the Git and follow these instructions [https://getnikola.com/handbook.html#deployment](url), below is the result.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

F:\Users\Gtopba>workon nikola3
(nikola3) F:\Users\Gtopba>cd my_first_site3

(nikola3) F:\Users\Gtopba\my_first_site3>git init .
Initialized empty Git repository in F:/Users/Gtopba/my_first_site3/.git/

(nikola3) F:\Users\Gtopba\my_first_site3>git remote add origin git@github.com:gtopba/gtopba.github.io

(nikola3) F:\Users\Gtopba\my_first_site3>nikola github_deploy
Scanning posts........done!
Scanning posts........done!
[2017-07-01T07:29:56Z] INFO: github_deploy: ==> ['git', 'checkout', 'src']
error: pathspec 'src' did not match any file(s) known to git.
[2017-07-01T07:29:56Z] INFO: github_deploy: ==> ['git', 'checkout', '-b', 'src']
Switched to a new branch 'src'
[2017-07-01T07:29:56Z] INFO: github_deploy: ==> ['git', 'add', '.']
warning: LF will be replaced by CRLF in README.txt.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in galleries/demo/exclude.meta.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in galleries/demo/index.txt.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in listings/hello.py.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/1.rst.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/bootstrap-demo.rst.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/charts.txt.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/creating-a-theme.rst.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/extending.txt.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/internals.txt.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/listings-demo.rst.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/manual.rst.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/path_handlers.txt.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/quickref.rst.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/quickstart.rst.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/slides-demo.rst.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/social_buttons.txt.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in pages/theming.rst.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in posts/1.rst.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in templates/book.tmpl.
The file will have its original line endings in your working directory.
[2017-07-01T07:29:56Z] INFO: github_deploy: ==> ['git', 'diff-index', '--quiet', 'HEAD']
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
[2017-07-01T07:29:56Z] INFO: github_deploy: ==> ['git', 'commit', '-am', 'Nikola auto commit.\n\nNikola version: 7.8.9']
[src (root-commit) 5ff36e2] Nikola auto commit.
 37 files changed, 10817 insertions(+)
 create mode 100644 .doit.db.bak
 create mode 100644 .doit.db.dat
 create mode 100644 .doit.db.dir
 create mode 100644 .gitignore
 create mode 100644 README.txt
 create mode 100644 conf.py
 create mode 100644 files/favicon.ico
 create mode 100644 files/images/nikola.png
 create mode 100644 galleries/demo/exclude.meta
 create mode 100644 galleries/demo/index.txt
 create mode 100644 galleries/demo/tesla2_lg.jpg
 create mode 100644 galleries/demo/tesla4_lg.jpg
 create mode 100644 galleries/demo/tesla_conducts_lg.jpg
 create mode 100644 galleries/demo/tesla_lightning1_lg.jpg
 create mode 100644 galleries/demo/tesla_lightning2_lg.jpg
 create mode 100644 galleries/demo/tesla_tower1_lg.jpg
 create mode 100644 images/frontispiece.jpg
 create mode 100644 images/illus_001.jpg
 create mode 100644 listings/hello.py
 create mode 100644 pages/1.rst
 create mode 100644 pages/bootstrap-demo.rst
 create mode 100644 pages/charts.txt
 create mode 100644 pages/creating-a-theme.rst
 create mode 100644 pages/dr-nikolas-vendetta.rst
 create mode 100644 pages/extending.txt
 create mode 100644 pages/internals.txt
 create mode 100644 pages/listings-demo.rst
 create mode 100644 pages/manual.rst
 create mode 100644 pages/path_handlers.txt
 create mode 100644 pages/quickref.rst
 create mode 100644 pages/quickstart.rst
 create mode 100644 pages/slides-demo.rst
 create mode 100644 pages/social_buttons.txt
 create mode 100644 pages/theming.rst
 create mode 100644 posts/1.rst
 create mode 100644 posts/my-first-post.rst
 create mode 100644 templates/book.tmpl
[2017-07-01T07:29:57Z] INFO: github_deploy: ==> ['ghp-import', '-n', '-m', 'Nikola auto commit.\n\nSource commit: 5ff36e2af90
aea44254a61750cb451687a632959\nNikola version: 7.8.9', '-p', '-r', 'origin', '-b', 'master', 'output']
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Traceback (most recent call last):
  File "f:\users\gtopba\appdata\local\programs\python\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "f:\users\gtopba\appdata\local\programs\python\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "f:\users\gtopba\envs\nikola3\scripts\ghp-import.exe\__main__.py", line 9, in <module>
  File "f:\users\gtopba\envs\nikola3\lib\site-packages\ghp_import\cli.py", line 198, in main
    sp.check_call(['git', 'push', opts.remote, opts.branch])
  File "f:\users\gtopba\appdata\local\programs\python\python36\Lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'master']' returned non-zero exit status 128.
[2017-07-01T07:30:00Z] ERROR: github_deploy: Failed GitHub deployment -- command ['ghp-import', '-n', '-m', 'Nikola auto comm
it.\n\nSource commit: 5ff36e2af90aea44254a61750cb451687a632959\nNikola version: 7.8.9', '-p', '-r', 'origin', '-b', 'master',
 'output'] returned 1

(nikola3) F:\Users\Gtopba\my_first_site3>
```

**Comment by Kwpolska** [comment]
You need to configure git so that you can push to the repository. You don’t have public keys that are accessible to git, so it can’t authenticate. Use a `https` remote URL or set up public keys.

Also, all those warnings:

```
warning: LF will be replaced by CRLF in README.txt.
The file will have its original line endings in your working directory.
```

can be fixed by [configuring git to always use LF](https://help.github.com/articles/dealing-with-line-endings/).

**Comment by gtopba** [comment]
Thank you for your fast response. I have deploy it successfully. These are what I did : 

1. run this command to solve the line ending problem on Windows machine
`git config --global core.autocrlf true`

2.  Use
`git remote add origin https://github.com/gtopba/gtopba.github.io.git`
Instead of
`git remote add origin git@github.com:gtopba/gtopba.github.io`

It is just me don't know how to use Git. Now I can sleep peacefully. Thank you very much.
