### ISSUE TITLE
tags plugin not updated

### ISSUE THREAD

**Issue by mandarvaze** [getnikola/nikola#2862]
### Environment (if reporting a bug)

**Python Version:**

python 3.4

**Nikola Version:**
Nikola v7.8.8

**Operating System:**
macOS Sierra

### Description:

`tags` plugin seems to be using `ipy_modern` variable, which no longer exists

Installing the `tags` plugin worked well

    $ nikola plugin -i tags
    [2017-06-26T14:13:40Z] WARNING: Nikola: To use the pelican metadata format you need to add "markdown.extensions.meta" to your MARKDOWN_EXTENSIONS setting.
    [2017-06-26T14:13:49Z] INFO: plugin: Downloading 'https://plugins.getnikola.com/v7/tags.zip'
    [2017-06-26T14:13:50Z] INFO: plugin: Extracting: tags into plugins/

After this, I get the following error for **every** nikola command 

    Traceback (most recent call last):
      File "/Users/mandar/.venvs/py3nikola/lib/python3.4/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
        candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
      File "/Users/mandar/.venvs/py3nikola/lib/python3.4/imp.py", line 235, in load_module
        return load_source(name, filename, file)
      File "/Users/mandar/.venvs/py3nikola/lib/python3.4/imp.py", line 171, in load_source
        module = methods.load()
      File "<frozen importlib._bootstrap>", line 1220, in load
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/projects/my_bitbucket_blog/wiltw/plugins/tags/tags.py", line 40, in <module>
        from nikola.plugins.compile.ipynb import current_nbformat, ipy_modern, nbformat
    ImportError: cannot import name 'ipy_modern'

Removing `tags` plugin does not work

    $ nikola plugin -r tags
    [2017-07-05T14:15:18Z] WARNING: Nikola: To use the pelican metadata format you need to add "markdown.extensions.meta" to your MARKDOWN_EXTENSIONS setting.
    [2017-07-05T14:15:24Z] ERROR: yapsy: Unable to import plugin:<... path to blog dir>/plugins/tags/tags
    Traceback (most recent call last):
      File "/Users/mandar/.venvs/py3nikola/lib/python3.4/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
        candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
      File "/Users/mandar/.venvs/py3nikola/lib/python3.4/imp.py", line 235, in load_module
        return load_source(name, filename, file)
      File "/Users/mandar/.venvs/py3nikola/lib/python3.4/imp.py", line 171, in load_source
        module = methods.load()
      File "<frozen importlib._bootstrap>", line 1220, in load
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/projects/my_bitbucket_blog/wiltw/plugins/tags/tags.py", line 40, in <module>
        from nikola.plugins.compile.ipynb import current_nbformat, ipy_modern, nbformat
    ImportError: cannot import name 'ipy_modern'
    [2017-07-05T14:15:24Z] ERROR: plugin: Unknown plugin: tags

I then removed it manually as follows 

    $ cd plugins
    $ rm -rf tags

Everything is "back to normal" after this.

**Comment by Kwpolska** [comment]
I fixed the plugin, try installing it again.

On a side note, Nikola v7.8.9 was released recently. May I recommend updating to Python 3.6 as well? (note we do not plan to drop 3.4 support in the foreseeable future)
