### ISSUE TITLE
no themes detected, cannot install new themes

### ISSUE THREAD

**Issue by mandarup** [getnikola/nikola#2864]
### Environment (if reporting a bug)

**Python Version:**
2.7 and 3.5

**Nikola Version:**
Nikola==7.8.9

**Operating System:**
ubuntu 16.04 

### Description:

No themes detected

    $nikola theme -l
    Available Themes:
    -----------------

 cannot install (any) new themes 

    $ nikola theme -i canterville
    [2017-07-10T01:37:05Z] ERROR: theme: Can't find theme canterville
    Traceback (most recent call last):
     File "/home/<user>/.virtualenvs/nikola27/local/lib/python2.7/site-packages/doit/doit_cmd.py", line 168, in run
       return command.parse_execute(args)
     File "/home/<user>/.virtualenvs/nikola27/local/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
       return self.execute(params, args)
     File "/home/<user>/.virtualenvs/nikola27/local/lib/python2.7/site-packages/nikola/plugin_categories.py", line 134, in execute
       return self._execute(options, args)
     File "/home/<user>/.virtualenvs/nikola27/local/lib/python2.7/site-packages/nikola/plugins/command/theme.py", line 176, in _execute
       return self.do_install_deps(url, install)
     File "/home/<user>/.virtualenvs/nikola27/local/lib/python2.7/site-packages/nikola/plugins/command/theme.py", line 194, in do_install_deps
       parent_name = utils.get_parent_theme_name(utils.get_theme_path_real(name, self.site.themes_dirs))
     File "/home/<user>/.virtualenvs/nikola27/local/lib/python2.7/site-packages/nikola/utils.py", line 623, in get_theme_path_real
       raise Exception("Can't find theme '{0}'".format(theme))
    Exception: Can't find theme 'canterville'

I do have themes installed (themes were working fine until now), blog currently uses zen-ipython

     $nikola theme -i zen-ipython
     [2017-07-10T01:52:03Z] ERROR: theme: Theme 'zen-ipython' is already installed in themes/zen-ipython

**Comment by Kwpolska** [comment]
Should be fixed now.

**Comment by mandarup** [comment]
@Kwpolska : now i get this error, new theme does not show up

    Traceback (most recent call last):
      File "/home/mandar/.virtualenvs/nikola35/lib/python3.5/site-packages/doit/doit_cmd.py", line 167, in run
        return command.parse_execute(args)
      File "/home/mandar/.virtualenvs/nikola35/lib/python3.5/site-packages/doit/cmd_base.py", line 120, in parse_execute
        return self.execute(params, args)
      File "/home/mandar/.virtualenvs/nikola35/lib/python3.5/site-packages/doit/cmd_base.py", line 403, in execute
        return self._execute(**exec_params)
      File "/home/mandar/.virtualenvs/nikola35/lib/python3.5/site-packages/doit/cmd_run.py", line 252, in _execute
        return runner.run_all(self.control.task_dispatcher())
      File "/home/mandar/.virtualenvs/nikola35/lib/python3.5/site-packages/doit/runner.py", line 246, in run_all
        self.run_tasks(task_dispatcher)
      File "/home/mandar/.virtualenvs/nikola35/lib/python3.5/site-packages/doit/runner.py", line 209, in run_tasks
        if not self.select_task(node, task_dispatcher.tasks):
      File "/home/mandar/.virtualenvs/nikola35/lib/python3.5/site-packages/doit/runner.py", line 116, in select_task
        if node.ignored_deps or self.dep_manager.status_is_ignore(task):
      File "/home/mandar/.virtualenvs/nikola35/lib/python3.5/site-packages/doit/dependency.py", line 556, in status_is_ignore
        return self._get(task.name, "ignore:")
      File "/home/mandar/.virtualenvs/nikola35/lib/python3.5/site-packages/doit/dependency.py", line 197, in get
        self._db[task_id] = json.loads(task_data.decode('utf-8'))
      File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Kwpolska** [comment]
This is unrelated. It looks like your `.doit.db` file is damaged — remove it and try again.
