### ISSUE TITLE
Error for broken metadata is cryptic

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2889]
As reported by @mgaitan 

```
(blog) tin@morochita:~/lab/blog$ nikola new_post -f ipynb
Creating New Post
-----------------
Title: Relevamiento de mesas con posibles irregularidades en Provincia de Buenos Aires
Scanning posts..Traceback (most recent call last):
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/nikola/utils.py", line 871, in to_datetime
    value = dateutil.parser.parse(value)
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/dateutil/parser.py", line 1182, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/dateutil/parser.py", line 562, in parse
    raise ValueError("String does not contain a date.")
ValueError: String does not contain a date.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/nikola/plugin_categories.py", line 129, in execute
    return self._execute(options, args)
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/nikola/plugins/command/new_post.py", line 315, in _execute
    self.site.scan_posts()
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/nikola/nikola.py", line 1894, in scan_posts
    timeline = p.plugin_object.scan()
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/nikola/plugins/misc/scan_posts.py", line 97, in scan
    self.site.get_compiler(base_path)
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/nikola/post.py", line 179, in __init__
    self.date = to_datetime(self.meta[self.default_lang]['date'], tzinfo)
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/nikola/utils.py", line 876, in to_datetime
    raise ValueError('Unrecognized date/time: {0!r}'.format(value))
ValueError: Unrecognized date/time: ''
```

**Comment by mgaitan** [comment]
That was installing nikola (from pypi) in a fresh virtualenv.  trying current master (84b0c623) I get a clearer output.

```
(blog) tin@morochita:~/lab/blog$ nikola new_post -f ipynb
[2017-08-19T03:31:12Z] WARNING: Nikola: The UNSLUGIFY_TITLES setting was renamed to FILE_METADATA_UNSLUGIFY_TITLES.
Creating New Post
-----------------

Title: prueba
Scanning posts..[2017-08-19T03:31:16Z] ERROR: Nikola: Missing date in file posts/scrapping-de-pdf-con-ipython-y-pdftotext-2.ipynb
[2017-08-19T03:31:16Z] ERROR: scan_posts: Error reading post posts/scrapping-de-pdf-con-ipython-y-pdftotext-2.ipynb
[2017-08-19T03:31:16Z] ERROR: Nikola: Error reading timeline
Traceback (most recent call last):
  File "/home/tin/lab/nikola/nikola/utils.py", line 909, in to_datetime
    value = dateutil.parser.parse(value)
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/dateutil/parser.py", line 1182, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/dateutil/parser.py", line 562, in parse
    raise ValueError("String does not contain a date.")
ValueError: String does not contain a date.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tin/lab/nikola/nikola/post.py", line 214, in __init__
    self.date = to_datetime(self.meta[self.default_lang]['date'], tzinfo)
  File "/home/tin/lab/nikola/nikola/utils.py", line 914, in to_datetime
    raise ValueError('Unrecognized date/time: {0!r}'.format(value))
ValueError: Unrecognized date/time: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/doit/doit_cmd.py", line 167, in run
    return command.parse_execute(args)
  File "/home/tin/.virtualenvs/blog/lib/python3.5/site-packages/doit/cmd_base.py", line 120, in parse_execute
    return self.execute(params, args)
  File "/home/tin/lab/nikola/nikola/plugin_categories.py", line 133, in execute
    return self._execute(options, args)
  File "/home/tin/lab/nikola/nikola/plugins/command/new_post.py", line 354, in _execute
    self.site.scan_posts()
  File "/home/tin/lab/nikola/nikola/nikola.py", line 2046, in scan_posts
    timeline = p.plugin_object.scan()
  File "/home/tin/lab/nikola/nikola/plugins/misc/scan_posts.py", line 101, in scan
    metadata_extractors_by=self.site.metadata_extractors_by
  File "/home/tin/lab/nikola/nikola/post.py", line 221, in __init__
    raise ValueError(msg)
ValueError: Missing date in file posts/scrapping-de-pdf-con-ipython-y-pdftotext-2.ipynb
```

**Comment by ralsina** [comment]
Ok then, marking as fixed.
