### ISSUE TITLE
Nikola auto fails with TypeError 

### ISSUE THREAD

**Issue by ChillarAnand** [getnikola/nikola#2890]
### Environment (if reporting a bug)

```
python -V
Python 3.5.2

pf | grep -i niko
Nikola==7.8.9

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

### Description:

While starting site with nikola auto, it fails with 

```
Traceback (most recent call last):
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/doit/doit_cmd.py", line 167, in run
    return command.parse_execute(args)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/doit/cmd_base.py", line 120, in parse_execute
    return self.execute(params, args)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/doit/cmd_base.py", line 378, in execute
    self, params, args)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/__main__.py", line 286, in load_tasks
    self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/doit/loader.py", line 313, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/doit/loader.py", line 26, in flat_generator
    for item in gen:
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/nikola.py", line 2059, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/nikola.py", line 2053, in flatten
    for t in task:
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/plugins/task/sources.py", line 49, in gen_tasks
    self.site.scan_posts()
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/nikola.py", line 2258, in scan_posts
    signal('scanned').send(self)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/plugins/misc/taxonomies_classifier.py", line 103, in _do_classificatio
n
    posts = self.site.sort_posts_chronologically(posts, lang)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/nikola.py", line 2146, in sort_posts_chronologically
    posts = natsort.natsorted(posts, key=lambda p: p.title(lang), alg=natsort.ns.F | natsort.ns.IC)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/natsort/natsort.py", line 286, in natsorted
    return sorted(seq, reverse=reverse, key=natsort_key)
TypeError: unorderable types: NoneType() < float()

```

**Comment by Kwpolska** [comment]
This doesn’t seem to be caused by `nikola auto` itself. Can you reproduce with `nikola build`? What version of `natsort` are you using? Can you reproduce in a clean demo site?

**Comment by ChillarAnand** [comment]
> Can you reproduce with nikola build?

Yes. 
```
Scanning posts.......done!
[2017-08-24T14:04:57Z] ERROR: Nikola: Error loading tasks. An unhandled exception occurred.
Traceback (most recent call last):
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/doit/doit_cmd.py", line 167, in run
    return command.parse_execute(args)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/doit/cmd_base.py", line 120, in parse_execute
    return self.execute(params, args)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/doit/cmd_base.py", line 378, in execute
    self, params, args)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/__main__.py", line 286, in load_tasks
    self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/doit/loader.py", line 313, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/doit/loader.py", line 26, in flat_generator
    for item in gen:
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/nikola.py", line 2059, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/nikola.py", line 2053, in flatten
    for t in task:
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/plugins/task/pages.py", line 48, in gen_tasks
    self.site.scan_posts()
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/nikola.py", line 2258, in scan_posts
    signal('scanned').send(self)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/plugins/misc/taxonomies_classifier.py", line 103, in _do_classification
    posts = self.site.sort_posts_chronologically(posts, lang)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/nikola/nikola.py", line 2146, in sort_posts_chronologically
    posts = natsort.natsorted(posts, key=lambda p: p.title(lang), alg=natsort.ns.F | natsort.ns.IC)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/natsort/natsort.py", line 286, in natsorted
    return sorted(seq, reverse=reverse, key=natsort_key)
TypeError: unorderable types: NoneType() < float()
```

> What version of natsort are you using? 
```
pf | grep -i nats
natsort==5.1.0
```

> Can you reproduce in a clean demo site?

Unfortunately,  no. https://github.com/ChillarAnand/avilpage.com is the project which is causing the issue. 

I also noticed some titles are missing from posts and there is just `None`, even though there is metadata.

**Comment by Kwpolska** [comment]
The following files on your blog have their title detected as `None`:

```
<Post: 'posts/2014/01/chalam-i-know.html' eb5f25712e13fdaaa769429564abf10d> None
<Post: 'posts/2014/02/best-way-to-restore-usb-drive-back-to.html' 1dd46c07fea788ba7250f49e5058df72> None
<Post: 'posts/2014/04/my-favorite-stories-essays-of-chalam.html' 53670a2561874f15117913baa8c883d1> None
<Post: 'posts/2014/04/useful-custom-key-maps-for-vimium-to.html' 48cf060dced21bfde5108fec0022e84e> None
<Post: 'posts/2016/01/let-it-be-zen-story-by-buddha.html' b5afabffad25d08490e08ee773a5e577> None
<Post: 'posts/2016/06/auto-completion-for-custom-search.html' aa054165438c01ae4857be4307237fbc> None
```

It seems to be caused by the HTML metadata reader, which notices the empty `<title></title>` tag and takes it as the post title. To fix this, you can install from GitHub (`v7-maintenance` or `master` if you feel like living on the bleeding edge), or alternatively just remove those tags from your code.

I patched this by ignoring empty tags, which I don’t think anyone depending on the HTML metadata thing cares about.

**Comment by ChillarAnand** [comment]
Excellent. Thank you @Kwpolska
