### ISSUE TITLE
ImportError: No module named 'BeautifulSoup'

### ISSUE THREAD

**Issue by davidak** [getnikola/nikola#2899]
### Environment

**Python Version:** Python 3.5.1

**Nikola Version:** Nikola v7.8.9

**Operating System:** OS X 10.10.5

### Description:

I updated nikola and tried to build site again.

```
imac:~ davidak$ nikola --version
[2017-09-10T14:10:58Z] ERROR: yapsy: Unable to import plugin: /usr/local/lib/python3.5/site-packages/nikola/plugins/compile/rest/media
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/micawber/parsers.py", line 8, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named 'BeautifulSoup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/site-packages/nikola/plugins/compile/rest/media.py", line 33, in <module>
    import micawber
  File "/usr/local/lib/python3.5/site-packages/micawber/__init__.py", line 5, in <module>
    from micawber.parsers import extract
  File "/usr/local/lib/python3.5/site-packages/micawber/parsers.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python3.5/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python3.5/site-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python3.5/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
Nikola v7.8.9
```

I tried to install it, bit it is not compatible with python3.

```
imac:Webseite davidak$ sudo pip install BeautifulSoup --upgrade
The directory '/Users/davidak/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/davidak/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting BeautifulSoup
  Downloading BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-209b38pm/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-209b38pm/BeautifulSoup/
```

But there is another package with a newer version:

`sudo pip install BeautifulSoup4 --upgrade`

Now i don't get the error:

```
imac:~ davidak$ nikola --version
Nikola v7.8.9
```

Please add `beautifulsoup4` as dependency to nikola, so it will be automatically installed.

**Comment by Kwpolska** [comment]
1. You need `pip install bs4`
2. BeautifulSoup is not a dependency of Nikola proper, it’s used only by the `micawber` module (which is the `media` reST directive, optional feature) Please report a bug with them instead.
