### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'parent' is undefined

### ISSUE THREAD

**Issue by davidak** [getnikola/nikola#2900]
### Environment

**Python Version:** Python 3.5.1

**Nikola Version:** Nikola v7.8.9

**Operating System:** OS X 10.10.5

**Site source:** https://github.com/davidak/davidak.de

**Versions after update:**

```
Successfully installed Jinja2-2.9.6 Markdown-2.6.9 MarkupSafe-1.0 Nikola-7.8.9 Pillow-4.2.1 PyYAML-3.12 Pygments-2.2.0 argh-0.26.2 bleach-2.0.0 certifi-2017.7.27.1 chardet-3.0.4 cloudpickle-0.4.0 decorator-4.1.2 docutils-0.14 doit-0.30.3 entrypoints-0.2.3 html5lib-0.999999999 idna-2.6 ipykernel-4.6.1 ipython-6.1.0 ipython-genutils-0.2.0 jedi-0.10.2 jsonschema-2.6.0 jupyter-client-5.1.0 jupyter-core-4.3.0 logbook-1.1.0 lxml-3.8.0 mako-1.0.7 micawber-0.3.4 mistune-0.7.4 natsort-5.1.0 nbconvert-5.3.1 nbformat-4.4.0 notebook-5.0.0 olefile-0.44 pandocfilters-1.4.2 pexpect-4.2.1 pickleshare-0.7.4 piexif-1.0.12 prompt-toolkit-1.0.15 ptyprocess-0.5.2 pygal-2.4.0 python-dateutil-2.6.1 pyzmq-16.0.2 requests-2.18.4 setuptools-36.4.0 smartypants-2.0.0 testpath-0.3.1 toml-0.9.2 tornado-4.5.2 traitlets-4.3.2 unidecode-0.4.21 urllib3-1.22 wcwidth-0.1.7 webassets-0.12.1 webencodings-0.5.1 ws4py-0.4.2
```

### Description:

Site build fails with this error after nikola update.

```
imac:Webseite davidak$ nikola build
Scanning posts........done!
.  render_taxonomies:output/thema/webhosting/index.html
########################################
TaskError - taskid:render_taxonomies:output/thema/webhosting/index.html
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/doit/action.py", line 403, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/nikola/nikola.py", line 1484, in render_template
    template_name, None, local_context)
  File "/usr/local/lib/python3.5/site-packages/nikola/plugins/template/jinja.py", line 96, in render_template
    data = template.render(**context)
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/nikola/data/themes/base-jinja/templates/tagindex.tmpl", line 3, in top-level template code
    {% import 'feeds_translations_helper.tmpl' as feeds_translations with context %}
  File "/usr/local/lib/python3.5/site-packages/nikola/data/themes/base-jinja/templates/index.tmpl", line 7, in top-level template code
    {% extends 'base.tmpl' %}
  File "/usr/local/lib/python3.5/site-packages/nikola/data/themes/bootstrap3-jinja/templates/base.tmpl", line 66, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/lib/python3.5/site-packages/nikola/data/themes/base-jinja/templates/index.tmpl", line 18, in block "content"
    {% block content_header %}
  File "/usr/local/lib/python3.5/site-packages/nikola/data/themes/base-jinja/templates/tagindex.tmpl", line 6, in block "content_header"
    {{ parent.content_header() }}
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'parent' is undefined
```

**Comment by Kwpolska** [comment]
That’s an embarassing bug. I’m releasing v7.8.10 with a fix.

**Comment by davidak** [comment]
Problem is solved. Thank you very much for the fast fix! \o/
