### ISSUE TITLE
Unicode exception while compiling template-based shortcode

### ISSUE THREAD

**Issue by max-arnold** [getnikola/nikola#2930]
**Python Version:**
 3.6

**Nikola Version:**
7.8.9

**Operating System:**
Mac OS

### Description:

Default config - just hit enter after every question. Created simple shortcode with non-ascii text and a page which uses it. Then `nikola build` results in the following traceback:

```
nikola build
Scanning posts........done!
.  render_sources:output/pages/index.rst
.  render_posts:timeline_changes
.  render_posts:cache/pages/index.html
########################################
TaskError - taskid:render_posts:cache/pages/index.html
PythonAction Error
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/testenv/lib/python3.6/site-packages/mako/lexer.py", line 209, in decode_raw_stream
    text = text.decode(parsed_encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/.virtualenvs/testenv/lib/python3.6/site-packages/doit/action.py", line 403, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/user/.virtualenvs/testenv/lib/python3.6/site-packages/nikola/post.py", line 579, in compile
    lang)
  File "/Users/user/.virtualenvs/testenv/lib/python3.6/site-packages/nikola/plugins/compile/rest/__init__.py", line 151, in compile
    output, error_level, deps, shortcode_deps = self.compile_string(data, source, is_two_file, post, lang)
  File "/Users/user/.virtualenvs/testenv/lib/python3.6/site-packages/nikola/plugins/compile/rest/__init__.py", line 136, in compile_string
    output, shortcode_deps = self.site.apply_shortcodes_uuid(output, shortcodes, filename=source_path, with_dependencies=True, extra_context=dict(post=post))
  File "/Users/user/.virtualenvs/testenv/lib/python3.6/site-packages/nikola/nikola.py", line 1750, in apply_shortcodes_uuid
    replacement, _deps = shortcodes.apply_shortcodes(v, self.shortcode_registry, self, filename, lang=lang, with_dependencies=with_dependencies, extra_context=extra_context)
  File "/Users/user/.virtualenvs/testenv/lib/python3.6/site-packages/nikola/shortcodes.py", line 371, in apply_shortcodes
    res = f(*args, **kw)
  File "/Users/user/.virtualenvs/testenv/lib/python3.6/site-packages/nikola/nikola.py", line 1682, in render_shortcode
    dependencies = [fname] + self.template_system.get_deps(fname)
  File "/Users/user/.virtualenvs/testenv/lib/python3.6/site-packages/nikola/plugins/template/mako.py", line 77, in get_deps
    return self.get_string_deps(text, filename)
  File "/Users/user/.virtualenvs/testenv/lib/python3.6/site-packages/nikola/plugins/template/mako.py", line 61, in get_string_deps
    lex.parse()
  File "/Users/user/.virtualenvs/testenv/lib/python3.6/site-packages/mako/lexer.py", line 224, in parse
    self.filename)
  File "/Users/user/.virtualenvs/testenv/lib/python3.6/site-packages/mako/lexer.py", line 215, in decode_raw_stream
    0, 0, filename)
mako.exceptions.CompileException: Unicode decode operation of encoding 'ascii' failed in file 'shortcodes/scode.tmpl' at line: 0 char: 0
```

Basically, there are two problems:

1. It is not obvious which template engine is used for shortcodes. In this case it is Mako, but it looks like Jinja also could be used if I change the theme to `boostrap3-jinja`. Probably this should be explicit or at least documented.

2. It looks like there are duplicate code paths to render the templates. One is for themes (which seems to handle unicode just fine), other is for shortcodes.

I'm not familiar with Mako, but after some googling was able to solve this problem by adding `## -*- coding: utf-8 -*-` to shortcode template. Maybe proper fix is something like this: https://stackoverflow.com/questions/4497515/unicodeencodeerror-in-mako-template

**Comment by Kwpolska** [comment]
1. Yes, we should document that. Done on `master`.
2. Our themes have the `coding: utf-8` comment all over the place. The code path should be the same.
3. Fixed on `master` by setting the input encoding to `utf-8` as it should be.
