### ISSUE TITLE
build code error new post

### ISSUE THREAD

**Issue by githubgnulinux** [getnikola/nikola#2949]
Creating New Post
-----------------

Title: test
Scanning posts...Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/doit/doit_cmd.py", line 120, in run
    return command.parse_execute(args)
  File "/usr/lib/python2.7/dist-packages/doit/cmd_base.py", line 78, in parse_execute
    return self.execute(params, args)
  File "/usr/lib/python2.7/dist-packages/nikola/plugin_categories.py", line 102, in execute
    self._execute(options, args)
  File "/usr/lib/python2.7/dist-packages/nikola/plugins/command/new_post.py", line 291, in _execute
    self.site.scan_posts()
  File "/usr/lib/python2.7/dist-packages/nikola/nikola.py", line 1208, in scan_posts
    self.get_compiler(base_path)
  File "/usr/lib/python2.7/dist-packages/nikola/post.py", line 167, in __init__
    source_path))
OSError: You must set a title (found 'test'), a slug (found 'test') and a date (found 'None')! [in file posts/test.html]

posts/test.html
`<!DOCTYPE` html>
<html>
<head>
<meta charset="UTF-8" />
</head>
<title>
</title>
<body>
	<h1>Test</h1>
	<p>text</p>
</body>
</html>
`

**Comment by ralsina** [comment]
Looks like you don't have a date in your post, like the error message says.

**Comment by githubgnulinux** [comment]
When using html files, please where and how should date be entered?

**Comment by Kwpolska** [comment]
`nikola new_post -f html` will generate a file with the correct format for you. Here’s an example:

```html
<!--
.. title: Foo Bar
.. slug: foo-bar
.. date: 2017-01-13 14:55:00
-->
```

Also, you don’t want `<!DOCTYPE>`, `<head>` and such — only the post content itself.

PS. Using Python 2.7 and Debian packages for Nikola is heavily discouraged.
