### ISSUE TITLE
Posts not translated to DEFAULT_LANG cause Nikola to sometimes crash when the entire site is rebuilt

### ISSUE THREAD

**Issue by sukiletxe** [getnikola/nikola#2956]
### Environment (if reporting a bug)

**Python Version:** 3.6

**Nikola Version:** 7.8.11

**Operating System:** Windows / Linux

### Description:

**Steps to reproduce**:
* `nikola init demo` (answer `en,es` to the language question, leave everything else as default)
* `cd demo`
* `nikola new_post -t test`
* Rename `test.rst` to `test.es.rst`
* `nikola build -a` (repeat preceded by `nikola clean` until it fails). Also works if using a CI to build (and if the `cache`, `output and `.doit*` are ignored or removed, as in my case).

**Comment by sukiletxe** [comment]
Oops, the output. Sorry.

```
.  render_taxonomies:output\index.html
########################################
TaskError - taskid:render_taxonomies:output\index.html
PythonAction Error
Traceback (most recent call last):
  File "c:\users\sukil etxenike\appdata\local\programs\python\python36\lib\site-packages\doit\action.py", line 403, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "c:\users\sukil etxenike\appdata\local\programs\python\python36\lib\site-packages\nikola\nikola.py", line 1484, in render_template
    template_name, None, local_context)
  File "c:\users\sukil etxenike\appdata\local\programs\python\python36\lib\site-packages\nikola\plugins\template\mako.py", line 117, in render_template
    data = template.render_unicode(**context)
  File "c:\users\sukil etxenike\appdata\local\programs\python\python36\lib\site-packages\mako\template.py", line 471, in render_unicode
    as_unicode=True)
  File "c:\users\sukil etxenike\appdata\local\programs\python\python36\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "c:\users\sukil etxenike\appdata\local\programs\python\python36\lib\site-packages\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "c:\users\sukil etxenike\appdata\local\programs\python\python36\lib\site-packages\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "C:\Users\sukil etxenike\demo\cache\.mako.tmp\base.tmpl.py", line 127, in render_body
    context['self'].content(**pageargs)
  File "C:\Users\sukil etxenike\demo\cache\.mako.tmp\index.tmpl.py", line 205, in render_content
    __M_writer(str(post.text(teaser_only=False)))
  File "c:\users\sukil etxenike\appdata\local\programs\python\python36\lib\site-packages\nikola\post.py", line 676, in text
    with io.open(file_name, "r", encoding="utf8") as post_file:
FileNotFoundError: [Errno 2] No such file or directory: 'cache\\posts\\test.es.html'
```

**Comment by felixfontein** [comment]
Looks to me like `Post.deps(lang)` (called by `Nikola.generic_post_list_renderer()`) didn't include all necessary dependencies. I guess the problem is here: https://github.com/getnikola/nikola/blob/v7.8.11/nikola/post.py#L543-L545 `cand_2` (where the post cache `.html` will be written to) is only added to the dependencies if `cand_1` exists -- but that should be `test.es.rst`? But maybe the problem isn't here, but during post scanning?

**Comment by felixfontein** [comment]
You can reproduce this more consistently by runnig `nikola build output/index.html` (after `nikola clean` / `rm -rf .doit.db output cache` in case you already ran nikola successfully).

**Comment by felixfontein** [comment]
Sorry, got interrupted. The problem is `Post.deps()`: it returns an empty list when called for an `es`-only article when `lang == 'en'` (for default language being `'en'`).
The correct behavior would be to act as in `Post._translated_file_path()`, which falls back to language `sorted(self.translated_to)[0]` if it cannot find a `lang` or `self.default_lang` version of the post.

**Comment by felixfontein** [comment]
Hmm, that also doesn't look right. Maybe better, the `if self.default_lang in self.translated_to:` at the beginning of `deps()` must be made unconditional? @ralsina, @Kwpolska: opinions?

**Comment by ralsina** [comment]
@felixfontein oh, boy that code is **complicated**.

**Comment by felixfontein** [comment]
@Kwpolska @ralsina  I think we should also fix this one for v8.

**Comment by ralsina** [comment]
I agree.
