### ISSUE TITLE
Starting Nikola throws errors related to galleries and Image

### ISSUE THREAD

**Issue by paregorios** [getnikola/nikola#3009]
### Environment (if reporting a bug)

**Python Version:** 3.6.4

**Nikola Version:** 7.8.14

**Operating System:** OSX El Capitan 10.11.6 (15G20015)

### Description:

Starting Nikola throws errors related to galleries and Image.

Steps to reproduce:

 - create fresh virtual environment and activate
 - ``` pip install Nikola[extras] ```
 - ```nikola init --demo horothesia```
 - observe the following

```
[2018-04-05T21:17:39Z] ERROR: yapsy: Unable to import plugin: /Users/paregorios/Envs/paregorios.2018/lib/python3.6/site-packages/nikola/plugins/task/galleries
Traceback (most recent call last):
  File "/Users/paregorios/Envs/paregorios.2018/lib/python3.6/site-packages/nikola/plugins/task/galleries.py", line 43, in <module>
    from PIL import Image  # NOQA
  File "/Users/paregorios/Envs/paregorios.2018/lib/python3.6/site-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/paregorios/Envs/paregorios.2018/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Users/paregorios/Envs/paregorios.2018/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/paregorios/Envs/paregorios.2018/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/paregorios/Envs/paregorios.2018/lib/python3.6/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/Users/paregorios/Envs/paregorios.2018/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/paregorios/Envs/paregorios.2018/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/paregorios/Envs/paregorios.2018/lib/python3.6/site-packages/nikola/plugins/task/galleries.py", line 45, in <module>
    import Image as _Image
ModuleNotFoundError: No module named 'Image'
Creating Nikola Site
====================

This is Nikola v7.8.14.  We will now ask you a few easy questions about your new site.
If you do not want to answer and want to go with the defaults instead, simply restart with the `-q` parameter.
--- Questions about the site ---
```

**Comment by Kwpolska** [comment]
This is not a problem with Nikola. This happens because you’re on an outdated version of macOS, and attempting to use packages compiled for 10.12.

If you installed Pillow using the wheels provided by the Pillow project (`pip install` does that by default): report a bug to them. You should be able to reproduce with `python -c "from PIL import Image"` instead of calling Nikola. Those packages claim 10.6+ compatibility, but apparently have some problems? — Try reinstalling `Pillow` first.

**Comment by paregorios** [comment]
Thank you

**Comment by paregorios** [comment]
@Kwpolska I hope you'll forgive me for posting here a link to the relevant open issue on the Pillow tracker in case anyone else stumbles across this thread in future: https://github.com/python-pillow/Pillow/issues/3068

**Comment by Kwpolska** [comment]
Posting a link is completely fine, as was your original query — while this
is not a Nikola bug, it was encountered while running it and could have
been an issue on our part as well.

-- 
Chris Warrick <https://chriswarrick.com/>
