### ISSUE TITLE
error: raise TypeError('too many positional arguments') from None

### ISSUE THREAD

**Issue by tbm** [getnikola/nikola#3052]
**Python Version:** 3.5

**Nikola Version:** current git

**Operating System:** Debian

### Description:

With Nikola from current Git, I'm getting:

```
  File "/usr/lib/python3.5/inspect.py", line 2841, in _bind
    raise TypeError('too many positional arguments') from None
```
after doing:

```
nikola init
cd new-site
nikola build
```

Full log:

```
nikola build
Scanning posts........done!
.  render_listings:output/listings/index.html
.  render_taxonomies:output/index.html
.  render_taxonomies:output/archive.html
.  render_taxonomies:output/categories/index.html
.  copy_assets:output/assets/css/bootblog.css
.  copy_assets:output/assets/js/jquery.min.js
.  copy_assets:output/assets/js/bootstrap.min.js
.  copy_assets:output/assets/js/popper.min.js
.  copy_assets:output/assets/css/bootstrap.min.css
.  copy_assets:output/assets/css/theme.css
.  copy_assets:output/assets/js/html5.js
.  copy_assets:output/assets/js/html5shiv-printshiv.min.js
.  copy_assets:output/assets/js/moment-with-locales.min.js
.  copy_assets:output/assets/js/baguetteBox.min.js
.  copy_assets:output/assets/js/fancydates.js
.  copy_assets:output/assets/js/justified-layout.min.js
.  copy_assets:output/assets/css/ipython.min.css
.  copy_assets:output/assets/css/baguetteBox.min.css
.  copy_assets:output/assets/css/html4css1.css
.  copy_assets:output/assets/css/nikola_ipython.css
.  copy_assets:output/assets/css/rst_base.css
.  copy_assets:output/assets/css/nikola_rst.css
.  copy_assets:output/assets/css/rst.css
.  copy_assets:output/assets/xml/rss.xsl
.  copy_assets:output/assets/xml/atom.xsl
.  copy_assets:output/assets/css/code.css
.  render_posts:timeline_changes
.  render_galleries:output/galleries
.  render_galleries:output/galleries/index.html
Traceback (most recent call last):
  File "/home/tbm/.local/lib/python3.5/site-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/home/tbm/.local/lib/python3.5/site-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/home/tbm/.local/lib/python3.5/site-packages/doit/cmd_base.py", line 420, in execute
    return self._execute(**exec_params)
  File "/home/tbm/.local/lib/python3.5/site-packages/doit/cmd_run.py", line 260, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "/home/tbm/.local/lib/python3.5/site-packages/doit/runner.py", line 256, in run_all
    self.run_tasks(task_dispatcher)
  File "/home/tbm/.local/lib/python3.5/site-packages/doit/runner.py", line 222, in run_tasks
    catched_excp = self.execute_task(node.task)
  File "/home/tbm/.local/lib/python3.5/site-packages/doit/runner.py", line 177, in execute_task
    return task.execute(self.stream)
  File "/home/tbm/.local/lib/python3.5/site-packages/doit/task.py", line 449, in execute
    action_return = action.execute(task_stdout, task_stderr)
  File "/home/tbm/.local/lib/python3.5/site-packages/doit/action.py", line 420, in execute
    kwargs = self._prepare_kwargs()
  File "/home/tbm/.local/lib/python3.5/site-packages/doit/action.py", line 389, in _prepare_kwargs
    self.args, self.kwargs)
  File "/home/tbm/.local/lib/python3.5/site-packages/doit/action.py", line 58, in _prepare_kwargs
    bound_args = func_sig.bind_partial(*args)
  File "/usr/lib/python3.5/inspect.py", line 2927, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/lib/python3.5/inspect.py", line 2841, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
```

**Comment by Kwpolska** [comment]
Sorry for that, should be fixed now.
