### ISSUE TITLE
Can't use built in theme

### ISSUE THREAD

**Issue by MortalCatalyst** [getnikola/nikola#3132]
Python Version: Python 3.6.6

Nikola Version: 7.8.15

Operating System: Windows 10

### Description:
When I attempt to use base themes such as bootblog4 or bootstrap4 the theme cannot be found or loaded.

If I list available themes they do not show.
```bash
(Learn-TX5ZszSr) C:\Users\Sayth\Learn\firstnik>nikola theme -l
Available Themes:
-----------------
blogtxt
bnw
bootstrap
bootstrap-jinja
cadair
canterville
carpet
detox
foundation6
```

Cannot install theme as same error they cannot be found.
```bash
(Learn-TX5ZszSr) C:\Users\Sayth\Learn\firstnik>nikola theme -i boostrap4
[2018-08-07T11:25:53Z] ERROR: theme: Can't find theme boostrap4
Traceback (most recent call last):
  File "c:\users\sayth\.virtualenvs\learn-tx5zszsr\lib\site-packages\doit\doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "c:\users\sayth\.virtualenvs\learn-tx5zszsr\lib\site-packages\doit\cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "c:\users\sayth\.virtualenvs\learn-tx5zszsr\lib\site-packages\nikola\plugin_categories.py", line 134, in execute
    return self._execute(options, args)
  File "c:\users\sayth\.virtualenvs\learn-tx5zszsr\lib\site-packages\nikola\plugins\command\theme.py", line 176, in _execute
    return self.do_install_deps(url, install)
  File "c:\users\sayth\.virtualenvs\learn-tx5zszsr\lib\site-packages\nikola\plugins\command\theme.py", line 194, in do_install_deps
    parent_name = utils.get_parent_theme_name(utils.get_theme_path_real(name, self.site.themes_dirs))
  File "c:\users\sayth\.virtualenvs\learn-tx5zszsr\lib\site-packages\nikola\utils.py", line 623, in get_theme_path_real
    raise Exception("Can't find theme '{0}'".format(theme))
Exception: Can't find theme 'boostrap4'
```

If I change conf.py to THEME='boostrap4" it also fails to build as cannot locate theme.

Unsure how to change theme.

**Comment by Kwpolska** [comment]
The Bootstrap 4 themes are available only for Nikola v8, currently in beta. (`pip install Nikola==8.0.0b2`)
