### ISSUE TITLE
Cannot start nikola after upgrading to 8.0 outside a Nikola site directory without errors

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#3164]
### Environment (if reporting a bug)

**Python Version:** 3.5.3

**Nikola Version:** 8.0.0

**Operating System:** Debian Stretch

### Description:

After upgrading to 8.0.0 from 7.x, I cannot start nikola outside a nikola site directory without errors. For example:

```
$ # cd to a directory that is not a Nikola site.
$ nikola --version   # or nikola init
Traceback (most recent call last):
  File "/home/hong/.local/bin/nikola", line 11, in <module>
    sys.exit(main())
  File "/home/hong/.local/lib/python3.5/site-packages/nikola/__main__.py", line 166, in main
    _ = DN.run(oargs)
  File "/home/hong/.local/lib/python3.5/site-packages/nikola/__main__.py", line 342, in run
    self.nikola.init_plugins()
  File "/home/hong/.local/lib/python3.5/site-packages/nikola/nikola.py", line 1031, in init_plugins
    self._activate_plugins_of_category("Taxonomy")
  File "/home/hong/.local/lib/python3.5/site-packages/nikola/nikola.py", line 1212, in _activate_plugins_of_category
    plugin_info.plugin_object.set_site(self)
  File "/home/hong/.local/lib/python3.5/site-packages/nikola/plugins/task/sections.py", line 73, in set_site
    self.show_list_as_index = site.config["POSTS_SECTIONS_ARE_INDEXES"]
KeyError: 'POSTS_SECTIONS_ARE_INDEXES'
```

**Comment by Kwpolska** [comment]
You apparently have a leftover file from the previous version — run this:

    rm /home/hong/.local/lib/python3.5/site-packages/nikola/plugins/task/sections.py

**Comment by xuhdev** [comment]
@Kwpolska Thanks! Would it be possible to deal with it during upgrade?

**Comment by Kwpolska** [comment]
Pip is supposed to remove the old version, and that should have taken care of `sections.py`. I managed to install v7 and then v8 in a clean environment and the file was gone.
