### ISSUE TITLE
When using the Pandoc compiler: TypeError: apply_shortcodes() got an unexpected keyword argument 'with_dependencies'

### ISSUE THREAD

**Issue by Neurrone** [getnikola/nikola#3171]
### Environment (if reporting a bug)

**Python Version:**
3.7

**Nikola Version:**
8.0

**Operating System:**
Windows 10 1803 x64

### Description:

When attempting to build a site with a single markdown post with the Pandoc v2.3.1 compiler, I get the following error:

```
.  render_sources:output\posts\hello-world\index.md
.  render_posts:timeline_changes
.  render_posts:cache\posts\hello-world.html
TaskError - taskid:render_posts:cache\posts\hello-world.html
PythonAction Error
Traceback (most recent call last):
  File "d:\source\neurrone.github.io\nikola\lib\site-packages\doit\action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "d:\source\neurrone.github.io\nikola\lib\site-packages\nikola\post.py", line 652, in compile
    lang)
  File "d:\source\neurrone.github.io\nikola\lib\site-packages\nikola\plugins\compile\pandoc.py", line 58, in compile
    output, shortcode_deps = self.site.apply_shortcodes(inf.read(), with_dependencies=True)
TypeError: apply_shortcodes() got an unexpected keyword argument 'with_dependencies'
```

The corresponding post:

```
<!--
.. title: Hello World!
.. slug: hello-world
.. date: 2018-09-30 13:27:00 UTC+08:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
-->

Testing post
```

This is the compilers configuration:

```
COMPILERS = {
    #"rest": ('.rst', '.txt'),
    #"markdown": ('.md', '.mdown', '.markdown'),
    "textile": ('.textile',),
    "txt2tags": ('.t2t',),
    "bbcode": ('.bb',),
    "wiki": ('.wiki',),
    "ipynb": ('.ipynb',),
    "html": ('.html', '.htm'),
    # PHP files are rendered the usual way (i.e. with the full templates).
    # The resulting files have .php extensions, making it possible to run
    # them without reconfiguring your server to recognize them.
    "php": ('.php',),
    # Pandoc detects the input from the source filename
    # but is disabled by default as it would conflict
    # with many of the others.
    "pandoc": ('.rst', '.md', '.txt'),
}
```

**Comment by Kwpolska** [comment]
Should be fixed in `master` now.
