### ISSUE TITLE
Cannot upgrade meta data in V7 anymore while migrating to V8

### ISSUE THREAD

**Issue by kayhayen** [getnikola/nikola#3174]
### Environment (if reporting a bug)

**Python Version:**

Python 3.5.3 (Debian stable)

**Nikola Version:**

python3 -m pip install nikola==7.8.15

**Operating System:**
Debian

### Description:

When using V7, I cannot upgrade the metadata, because the plugin fails to load:

```
nikola upgrade_metadata
[2018-10-03T17:04:28Z] WARNING: Nikola: Locale en_US.UTF-8 for language en not accepted by python locale.
[2018-10-03T17:04:28Z] ERROR: yapsy: Unable to import plugin: /home/hayen/repos/nikola-site/plugins/upgrade_metadata/upgrade_metadata
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/yapsy/PluginManager.py", line 510, in loadPlugins
    candidate_module = PluginManager._importModule(plugin_module_name, candidate_filepath)
  File "/usr/local/lib/python3.5/dist-packages/yapsy/PluginManager.py", line 576, in _importModule
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 774, in get_code
  File "/usr/lib/python3.5/imp.py", line 156, in get_data
    return file.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 37: ordinal not in range(128)
[2018-10-03T17:04:29Z] ERROR: Nikola: Unknown command upgrade_metadata

```

In V8 the attempt to plugin fails to do anything, because it chokes over .rst files that have their meta data in separate files, which is probably the majority of my posts. 

This is 8.0.1 as per `python3 -m pip install -U nikola` and results in:

[2018-10-03T17:09:23Z] WARNING: Nikola: Cannot load theme "bootstrap3", using 'bootblog4' instead.
Scanning posts.[2018-10-03T17:09:24Z] ERROR: Nikola: Missing date in file posts/award-winning-cat.rst
[2018-10-03T17:09:24Z] ERROR: scan_posts: Error reading post posts/award-winning-cat.rst
[2018-10-03T17:09:24Z] ERROR: Nikola: Error reading timeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nikola/utils.py", line 922, in to_datetime
    value = dateutil.parser.parse(value)
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 1356, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 651, in parse
    raise ValueError("String does not contain a date:", timestr)
ValueError: ('String does not contain a date:', '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nikola/post.py", line 214, in __init__
    self.date = to_datetime(self.meta[self.default_lang]['date'], tzinfo)
  File "/usr/local/lib/python3.5/dist-packages/nikola/utils.py", line 927, in to_datetime
    raise ValueError('Unrecognized date/time: {0!r}'.format(value))
ValueError: Unrecognized date/time: ''

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/usr/local/lib/python3.5/dist-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/usr/local/lib/python3.5/dist-packages/nikola/plugin_categories.py", line 148, in execute
    return self._execute(options, args)
  File "/home/hayen/repos/nikola-site/plugins/upgrade_metadata/upgrade_metadata.py", line 57, in _execute
    self.site.scan_posts()
  File "/usr/local/lib/python3.5/dist-packages/nikola/nikola.py", line 2065, in scan_posts
    timeline = p.plugin_object.scan()
  File "/usr/local/lib/python3.5/dist-packages/nikola/plugins/misc/scan_posts.py", line 99, in scan
    metadata_extractors_by=self.site.metadata_extractors_by
  File "/usr/local/lib/python3.5/dist-packages/nikola/post.py", line 221, in __init__
    raise ValueError(msg)
ValueError: Missing date in file posts/award-winning-cat.rst

```

My guess is the plugin no longer works for V7 and for V8 doesn't support migrating that anymore?

**Comment by kayhayen** [comment]
If it helps, I could also try self compiled 3.6 and 3.7, if that is part of the issue. Please advise.

**Comment by Kwpolska** [comment]
Try removing the © character in upgrade_metadata.py.  It should work, but it seems something goes wrong with Unicode support on your system. (see also: https://chriswarrick.com/blog/2017/06/18/unix-locales-vs-unicode/ )

**Comment by kayhayen** [comment]
You are right, this helps:

```
-LOCALES={"en":"en_US.UTF-8"}
+LOCALES={"en":"de_DE.UTF-8"}
```

Not sure if I like this, but otherwise no plugin will work it seems. I also tried tx3 tag could plugin.

The V7 handbook has no hit on "LOCALES", yet I was forced to provide it, while guessing the contents. But for V8 that is a gonner anyway, right? But thanks, seems I can go V8 then.

Yours,
Kay

**Comment by Kwpolska** [comment]
Yeah, version 7’s locale support was a bit of a mess, and for no good reason.
