### ISSUE TITLE
NotImplementedError building my blog

### ISSUE THREAD

**Issue by asmeurer** [getnikola/nikola#3185]
### Environment (if reporting a bug)

**Python Version:**

3.6

**Nikola Version:**

8.0.1

**Operating System:**
Happens on both Mac and Linux (Travis)

### Description:

See https://travis-ci.org/asmeurer/blog/builds/452092591. The sources are at https://github.com/asmeurer/blog.

I get 

```pytb
.  render_posts:cache/posts/automatically-deploying-this-blog-to-github-pages-with-travis-ci.html
TaskError - taskid:render_posts:cache/posts/automatically-deploying-this-blog-to-github-pages-with-travis-ci.html
PythonAction Error
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/doit/action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nikola/post.py", line 652, in compile
    lang)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nikola/plugin_categories.py", line 323, in compile
    raise NotImplementedError()
```

This same blog built just fine with an older version of Nikola (see the Travis history).

**Comment by Kwpolska** [comment]
Try upgrading the commonmark plugin.

**Comment by asmeurer** [comment]
I did that. Now I get

```
$ nikola build
Scanning posts............done!
.  render_galleries:output/galleries
.  render_galleries:output/galleries/swift-game-2.thumbnail.png
.  render_galleries:output/galleries/swift-game-2.png
.  render_galleries:output/galleries/conda_scipy2014_slide.thumbnail.png
.  render_galleries:output/galleries/conda_scipy2014_slide.png
.  render_galleries:output/galleries/SpriteKit-Example.thumbnail.gif
.  render_galleries:output/galleries/SpriteKit-Example.gif
.  render_galleries:output/galleries/SpriteKit-Example-2.thumbnail.gif
.  render_galleries:output/galleries/SpriteKit-Example-2.gif
.  render_galleries:output/galleries/swift-game-1.thumbnail.png
.  render_galleries:output/galleries/swift-game-1.png
.  render_galleries:output/galleries/index.html
.  render_galleries:output/galleries/rss.xml
.  render_posts:cache/posts/automatically-deploying-this-blog-to-github-pages-with-travis-ci.html
[2018-11-07T21:15:50Z] ERROR: Nikola: In order to build this site (compile with CommonMark), you must install the "commonmark" Python package.
[2018-11-07T21:15:50Z] ERROR: Nikola: Exiting due to missing dependencies.
$ pip freeze | grep commonmark
commonmark==0.8.1
```
