### ISSUE TITLE
jupyter notebook with extension

### ISSUE THREAD

**Issue by geohadab** [getnikola/nikola#3192]
I get the following error when I build the website. I use ipynb notebook format for my posts. 
I suspect that the extensions I installed for jupyter notebook is the problem 

TaskError - taskid:render_posts:cache\posts\jupyter.html
PythonAction Error
Traceback (most recent call last):
  File "c:\users\abdull~1\docume~1\github\myblog2\nikola\lib\site-packages\doit\action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "c:\users\abdull~1\docume~1\github\myblog2\nikola\lib\site-packages\nikola\post.py", line 652, in compile
    lang)
  File "c:\users\abdull~1\docume~1\github\myblog2\nikola\lib\site-packages\nikola\plugins\compile\ipynb.py", line 88, in compile
    output, shortcode_deps = self.compile_string(nb_str, is_two_file, post, lang)
  File "c:\users\abdull~1\docume~1\github\myblog2\nikola\lib\site-packages\nikola\plugins\compile\ipynb.py", line 79, in compile_string
    output = self._compile_string(nbformat.reads(new_data, current_nbformat))
  File "c:\users\abdull~1\docume~1\github\myblog2\nikola\lib\site-packages\nikola\plugins\compile\ipynb.py", line 64, in _compile_string
    exportHtml = HTMLExporter(config=c)
  File "c:\users\abdull~1\docume~1\github\myblog2\nikola\lib\site-packages\nbconvert\exporters\templateexporter.py", line 256, in __init__
    super(TemplateExporter, self).__init__(config=config, **kw)
  File "c:\users\abdull~1\docume~1\github\myblog2\nikola\lib\site-packages\nbconvert\exporters\exporter.py", line 109, in __init__
    self._init_preprocessors()
  File "c:\users\abdull~1\docume~1\github\myblog2\nikola\lib\site-packages\nbconvert\exporters\exporter.py", line 263, in _init_preprocessors    self.register_preprocessor(preprocessor, enabled=True)
  File "c:\users\abdull~1\docume~1\github\myblog2\nikola\lib\site-packages\nbconvert\exporters\exporter.py", line 224, in register_preprocessor    preprocessor_cls = import_item(preprocessor)  File "c:\users\abdull~1\docume~1\github\myblog2\nikola\lib\site-packages\traitlets\utils\importstring.py", line 34, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'jupyter_contrib_nbextensions'

### Environment (if reporting a bug)

**Python Version:**  python3.7

**Nikola Version:**  Nikola v8.0.1

**Operating System:** Windows10

**Comment by geohadab** [comment]
I just solved this issue ... I just installed nbextensions in my environment

pip install jupyter_contrib_nbextensions

and It worked
