### ISSUE TITLE
KeyError: 'feeds_translations_helper.tmpl'  on Nikola v7.8.15

### ISSUE THREAD

**Issue by orsenthil** [getnikola/nikola#3200]
### Environment (if reporting a bug)

**Python Version:** 3.8  

**Nikola Version:** v7.8.15

**Operating System:** Ubuntu 18.10

### Description:

I have an active Nikola site, https://github.com/orsenthil/xtoinfinity.com, hosted at xtoinfinity.com
I changed my computer, and since I had the source of my site, I thought, I could rebuild it. However, I am not successful as I encounter issues with dependencies while building my site using Nikola.

---- 

This is the traceback (final relevant section) that I see when trying to build my site.

```
[2019-01-04T13:16:13Z] DEBUG: yapsy: correct subclass tests failed for: write_metadata in /home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/plugins/compile/html
Traceback (most recent call last):                                                                                                                                                           
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/yapsy/PluginManager.py", line 527, in loadPlugins                                                                   
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])                                                                                                     
TypeError: issubclass() arg 1 must be a class                                                                                                                                                
[2019-01-04T13:16:13Z] DEBUG: yapsy: correct subclass tests failed for: write_metadata in /home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/plugins/compile/html
Traceback (most recent call last):                                                                                                                                                           
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/yapsy/PluginManager.py", line 527, in loadPlugins                                                                   
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])                                                                                                     
TypeError: issubclass() arg 1 must be a class  
[2019-01-04T13:16:13Z] DEBUG: yapsy: correct subclass tests failed for: write_metadata in /home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/plugins/compile/html
Traceback (most recent call last):                                                                                                                                                           
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/yapsy/PluginManager.py", line 527, in loadPlugins                                                                   
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])                                                                                                     
TypeError: issubclass() arg 1 must be a class                                                                                                                                                
[2019-01-04T13:16:13Z] DEBUG: MARKDOWN: Successfully loaded extension "yapsy_loaded_plugin_mdx_podcast_0.PodcastExtension".
[2019-01-04T13:16:13Z] DEBUG: MARKDOWN: Successfully loaded extension "yapsy_loaded_plugin_mdx_gist_0.GistExtension".
[2019-01-04T13:16:13Z] DEBUG: MARKDOWN: Successfully loaded extension "yapsy_loaded_plugin_mdx_nikola_0.NikolaExtension".
[2019-01-04T13:16:13Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
[2019-01-04T13:16:13Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
[2019-01-04T13:16:13Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
[2019-01-04T13:16:13Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.footnotes.FootnoteExtension".
[2019-01-04T13:16:13Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.attr_list.AttrListExtension".
[2019-01-04T13:16:13Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.def_list.DefListExtension".
[2019-01-04T13:16:13Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.tables.TableExtension".
[2019-01-04T13:16:13Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.abbr.AbbrExtension".
[2019-01-04T13:16:13Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.extra.ExtraExtension".
Scanning posts.........done!
[2019-01-04T13:16:14Z] ERROR: Nikola: Error loading tasks. An unhandled exception occurred.
Traceback (most recent call last):
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/mako/lookup.py", line 247, in get_template
    return self._check(uri, self._collection[uri])
KeyError: 'feeds_translations_helper.tmpl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/doit/cmd_base.py", line 388, in execute
    self.task_list, dodo_config = self.loader.load_tasks(
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/__main__.py", line 285, in load_tasks
    tasks = generate_tasks(
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/doit/loader.py", line 313, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/doit/loader.py", line 26, in flat_generator
    for item in gen:
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/nikola.py", line 2063, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/nikola.py", line 2058, in flatten
    for ft in flatten(t):
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/nikola.py", line 2057, in flatten
    for t in task:
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/plugins/task/taxonomies.py", line 262, in _generate_classification_page_as_list
    task = self.site.generic_post_list_renderer(lang, filtered_posts, output_name, template_name, kw['filters'], context)
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/nikola.py", line 2390, in generic_post_list_renderer
    return self.generic_renderer(lang, output_name, template_name, filters,
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/nikola.py", line 2282, in generic_renderer
    file_deps += self.template_system.template_deps(template_name)
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/plugins/template/mako.py", line 135, in template_deps
    dep_filenames = self.get_deps(template.filename)
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/plugins/template/mako.py", line 77, in get_deps
    return self.get_string_deps(text, filename)
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/plugins/template/mako.py", line 71, in get_string_deps
    deps[i] = self.get_template_path(d)
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/plugins/template/mako.py", line 145, in get_template_path
    t = self.lookup.get_template(template_name)
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/mako/lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/mako/lookup.py", line 318, in _load
    self._collection[uri] = template = Template(
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/mako/template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/mako/template.py", line 396, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/mako/compat.py", line 83, in load_module
    return machinery.SourceFileLoader(module_id, path).load_module()
  File "<frozen importlib._bootstrap_external>", line 456, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 956, in load_module
  File "<frozen importlib._bootstrap_external>", line 781, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 773, in exec_module
  File "<frozen importlib._bootstrap_external>", line 910, in get_code
  File "<frozen importlib._bootstrap_external>", line 840, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/skumaran/github/orsenthil/xtoinfinity.com/cache/.mako.tmp/feeds_translations_helper.tmpl.py", line 30
    def render_head(context,classification=):
                                           ^
SyntaxError: invalid syntax
```

I am not sure if this is an issue with the dependencies or with the version of Nikola that I am using.

* I tried the latest version, but since my blog was based off 1.7, I started with 1.7 to start with the migration.
* I do have the old setup, so I cannot determine the successful versions of packages.

**Comment by orsenthil** [comment]
If it helps, this is the requirements.txt of the environment created using (pip freeze)

```
argh==0.26.2
backcall==0.1.0
bleach==3.0.2
blinker==1.4
certifi==2018.11.29
chardet==3.0.4
cloudpickle==0.6.1
decorator==4.3.0
defusedxml==0.5.0
docutils==0.14
doit==0.31.1
entrypoints==0.2.3
ghp-import2==1.0.1
husl==4.0.3
idna==2.8
ipykernel==5.1.0
ipython==7.2.0
ipython-genutils==0.2.0
jedi==0.13.2
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.4
jupyter-core==4.4.0
Logbook==1.4.1
lxml==4.2.6
Mako==1.0.7
Markdown==3.0.1
MarkupSafe==1.1.0
micawber==0.3.8
mistune==0.8.4
natsort==5.5.0
nbconvert==5.4.0
nbformat==4.4.0
Nikola==7.8.15
notebook==5.7.4
pandocfilters==1.4.2
parso==0.3.1
pathtools==0.1.2
pexpect==4.6.0
phpserialize==1.3
pickleshare==0.7.5
piexif==1.1.2
Pillow==5.4.0
prometheus-client==0.5.0
prompt-toolkit==2.0.7
ptyprocess==0.6.0
pygal==2.4.0
Pygments==2.3.1
pyinotify==0.9.6
Pyphen==0.9.5
PyRSS2Gen==1.1
python-dateutil==2.7.5
PyYAML==3.12
pyzmq==17.1.2
requests==2.21.0
Send2Trash==1.5.0
six==1.12.0
smartypants==2.0.1
terminado==0.8.1
testpath==0.4.2
toml==0.9.2
tornado==5.1.1
traitlets==4.3.2
typogrify==2.0.7
Unidecode==1.0.23
urllib3==1.24.1
watchdog==0.8.3
wcwidth==0.1.7
webassets==0.12.1
webencodings==0.5.1
ws4py==0.4.2
Yapsy==1.12.0
```

**Comment by Kwpolska** [comment]
Try removing `/home/skumaran/github/orsenthil/xtoinfinity.com/cache/.mako.tmp/feeds_translations_helper.tmpl.py` first. If it does not fix the issue, figure out where `feeds_translations_helper.tmpl` is located and show us its contents.

**Comment by orsenthil** [comment]
I resolved this by using a old version Nikola  `Nikola==7.8.1` with `Markdown<3.0.0`

--- 

> Try removing /home/skumaran/github/orsenthil/xtoinfinity.com/cache/.mako.tmp/feeds_translations_helper.tmpl.py first. If it does not fix the issue

It does not. It re-creates the file.

Here is the contents of that file.

<details>
<summary>.py file</summary>

```
# -*- coding:utf-8 -*-
from mako import runtime, filters, cache
UNDEFINED = runtime.UNDEFINED
STOP_RENDERING = runtime.STOP_RENDERING
__M_dict_builtin = dict
__M_locals_builtin = locals
_magic_number = 10
_modified_time = 1546610699.713456
_enable_loop = True
_template_filename = '/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/data/themes/base/templates/feeds_translations_helper.tmpl'
_template_uri = 'feeds_translations_helper.tmpl'
_source_encoding = 'utf-8'
_exports = ['head', 'feed_link', 'translation_link']


def render_body(context,**pageargs):
    __M_caller = context.caller_stack._push_frame()
    try:
        __M_locals = __M_dict_builtin(pageargs=pageargs)
        __M_writer = context.writer()
        __M_writer('\n')
        __M_writer('\n\n')
        __M_writer('\n\n')
        __M_writer('\n')
        return ''
    finally:
        context.caller_stack._pop_frame()


def render_head(context,classification=):
    __M_caller = context.caller_stack._push_frame()
    try:
        has_other_languages = context.get('has_other_languages', UNDEFINED)
        kind = context.get('kind', UNDEFINED)
        translations = context.get('translations', UNDEFINED)
        _link = context.get('_link', UNDEFINED)
        generate_atom = context.get('generate_atom', UNDEFINED)
        len = context.get('len', UNDEFINED)
        generate_rss = context.get('generate_rss', UNDEFINED)
        rss_link = context.get('rss_link', UNDEFINED)
        sorted = context.get('sorted', UNDEFINED)
        other_languages = context.get('other_languages', UNDEFINED)
        __M_writer = context.writer()
        __M_writer('\n')
        if rss_link:
            __M_writer('        ')
            __M_writer(str(rss_link))
            __M_writer('\n')
        if len(translations) > 1:
            for language in sorted(translations):
                if classification:
                    if generate_atom:
                        __M_writer('                    <link rel="alternate" type="application/atom+xml" title="Atom for ')
                        __M_writer(str(kind))
                        __M_writer(' ')
                        __M_writer(filters.html_escape(str(classification)))
                        __M_writer(' (')
                        __M_writer(str(language))
                        __M_writer(')" href="')
                        __M_writer(str(_link(kind + "_atom", classification, language)))
                        __M_writer('">\n')
                    if generate_rss and not rss_link:
                        __M_writer('                    <link rel="alternate" type="application/rss+xml" title="RSS for ')
                        __M_writer(str(kind))
                        __M_writer(' ')
                        __M_writer(filters.html_escape(str(classification)))
                        __M_writer(' (')
                        __M_writer(str(language))
                        __M_writer(')" href="')
                        __M_writer(str(_link(kind + "_rss", classification, language)))
                        __M_writer('">\n')
                else:
                    if generate_atom:
                        __M_writer('                    <link rel="alternate" type="application/atom+xml" title="Atom (')
                        __M_writer(str(language))
                        __M_writer(')" href="')
                        __M_writer(str(_link("index_atom", None, language)))
                        __M_writer('">\n')
                    if generate_rss and not rss_link:
                        __M_writer('                    <link rel="alternate" type="application/rss+xml" title="RSS (')
                        __M_writer(str(language))
                        __M_writer(')" href="')
                        __M_writer(str(_link("rss", None, language)))
                        __M_writer('">\n')
        else:
            if classification:
                if generate_atom:
                    __M_writer('                <link rel="alternate" type="application/atom+xml" title="Atom for ')
                    __M_writer(str(kind))
                    __M_writer(' ')
                    __M_writer(filters.html_escape(str(classification)))
                    __M_writer('" href="')
                    __M_writer(str(_link(kind + "_atom", classification)))
                    __M_writer('">\n')
                if generate_rss and not rss_link:
                    __M_writer('                <link rel="alternate" type="application/rss+xml" title="RSS for ')
                    __M_writer(str(kind))
                    __M_writer(' ')
                    __M_writer(filters.html_escape(str(classification)))
                    __M_writer('" href="')
                    __M_writer(str(_link(kind + "_rss", classification)))
                    __M_writer('">\n')
            else:
                if generate_atom:
                    __M_writer('                <link rel="alternate" type="application/atom+xml" title="Atom" href="')
                    __M_writer(str(_link("index_atom", None)))
                    __M_writer('">\n')
                if generate_rss and not rss_link:
                    __M_writer('                <link rel="alternate" type="application/rss+xml" title="RSS" href="')
                    __M_writer(str(_link("rss", None)))
                    __M_writer('">\n')
        if has_other_languages and other_languages:
            for language, classification, _ in other_languages:
                __M_writer('            <link rel="alternate" hreflang="')
                __M_writer(str(language))
                __M_writer('" href="')
                __M_writer(str(_link(kind, classification, language)))
                __M_writer('">\n')
        return ''
    finally:
        context.caller_stack._pop_frame()


def render_feed_link(context,classification):
    __M_caller = context.caller_stack._push_frame()
    try:
        kind = context.get('kind', UNDEFINED)
        translations = context.get('translations', UNDEFINED)
        _link = context.get('_link', UNDEFINED)
        generate_atom = context.get('generate_atom', UNDEFINED)
        len = context.get('len', UNDEFINED)
        generate_rss = context.get('generate_rss', UNDEFINED)
        messages = context.get('messages', UNDEFINED)
        sorted = context.get('sorted', UNDEFINED)
        __M_writer = context.writer()
        __M_writer('\n')
        if len(translations) > 1:
            for language in sorted(translations):
                if generate_atom or generate_rss:
                    __M_writer('                <p class="feedlink">\n')
                    if generate_atom:
                        __M_writer('                        <a href="')
                        __M_writer(str(_link(kind + "_atom", classification, language)))
                        __M_writer('" hreflang="')
                        __M_writer(str(language))
                        __M_writer('" type="application/atom+xml">')
                        __M_writer(str(messages('Atom feed', language)))
                        __M_writer(' (')
                        __M_writer(str(language))
                        __M_writer(')</a>\n')
                    if generate_rss:
                        __M_writer('                        <a href="')
                        __M_writer(str(_link(kind + "_rss", classification, language)))
                        __M_writer('" hreflang="')
                        __M_writer(str(language))
                        __M_writer('" type="application/rss+xml">')
                        __M_writer(str(messages('RSS feed', language)))
                        __M_writer(' (')
                        __M_writer(str(language))
                        __M_writer(')</a>\n')
                    __M_writer('                </p>\n')
        else:
            if generate_atom or generate_rss:
                __M_writer('            <p class="feedlink">\n')
                if generate_atom:
                    __M_writer('                    <a href="')
                    __M_writer(str(_link(kind + "_atom", classification)))
                    __M_writer('" type="application/atom+xml">')
                    __M_writer(str(messages('Atom feed')))
                    __M_writer('</a>\n')
                if generate_rss:
                    __M_writer('                    <a href="')
                    __M_writer(str(_link(kind + "_rss", classification)))
                    __M_writer('" type="application/rss+xml">')
                    __M_writer(str(messages('RSS feed')))
                    __M_writer('</a>\n')
                __M_writer('            </p>\n')
        return ''
    finally:
        context.caller_stack._pop_frame()


def render_translation_link(context):
    __M_caller = context.caller_stack._push_frame()
    try:
        has_other_languages = context.get('has_other_languages', UNDEFINED)
        kind = context.get('kind', UNDEFINED)
        _link = context.get('_link', UNDEFINED)
        messages = context.get('messages', UNDEFINED)
        other_languages = context.get('other_languages', UNDEFINED)
        __M_writer = context.writer()
        __M_writer('\n')
        if has_other_languages and other_languages:
            __M_writer('        <div class="translationslist translations">\n            <h3 class="translationslist-intro">')
            __M_writer(str(messages("Also available in:")))
            __M_writer('</h3>\n')
            for language, classification, name in other_languages:
                __M_writer('            <p><a href="')
                __M_writer(str(_link(kind, classification, language)))
                __M_writer('" rel="alternate">')
                __M_writer(str(messages("LANGUAGE", language)))
                __M_writer('\n')
                if kind != 'archive':
                    __M_writer('                (')
                    __M_writer(filters.html_escape(str(name)))
                    __M_writer(')\n')
                __M_writer('            </a></p>\n')
            __M_writer('        </div>\n')
        return ''
    finally:
        context.caller_stack._pop_frame()


"""
__M_BEGIN_METADATA
{"filename": "/home/skumaran/.py/virtualenv/nikola/lib/python3.8/site-packages/nikola/data/themes/base/templates/feeds_translations_helper.tmpl", "uri": "feeds_translations_helper.tmpl", "source_encoding": "utf-8", "line_map": {"16": 0, "21": 2, "22": 48, "23": 76, "24": 91, "30": 4, "44": 4, "45": 5, "46": 6, "47": 6, "48": 6, "49": 8, "50": 9, "51": 10, "52": 11, "53": 12, "54": 12, "55": 12, "56": 12, "57": 12, "58": 12, "59": 12, "60": 12, "61": 12, "62": 14, "63": 15, "64": 15, "65": 15, "66": 15, "67": 15, "68": 15, "69": 15, "70": 15, "71": 15, "72": 17, "73": 18, "74": 19, "75": 19, "76": 19, "77": 19, "78": 19, "79": 21, "80": 22, "81": 22, "82": 22, "83": 22, "84": 22, "85": 26, "86": 27, "87": 28, "88": 29, "89": 29, "90": 29, "91": 29, "92": 29, "93": 29, "94": 29, "95": 31, "96": 32, "97": 32, "98": 32, "99": 32, "100": 32, "101": 32, "102": 32, "103": 34, "104": 35, "105": 36, "106": 36, "107": 36, "108": 38, "109": 39, "110": 39, "111": 39, "112": 43, "113": 44, "114": 45, "115": 45, "116": 45, "117": 45, "118": 45, "124": 50, "136": 50, "137": 51, "138": 52, "139": 53, "140": 54, "141": 55, "142": 56, "143": 56, "144": 56, "145": 56, "146": 56, "147": 56, "148": 56, "149": 56, "150": 56, "151": 58, "152": 59, "153": 59, "154": 59, "155": 59, "156": 59, "157": 59, "158": 59, "159": 59, "160": 59, "161": 61, "162": 64, "163": 65, "164": 66, "165": 67, "166": 68, "167": 68, "168": 68, "169": 68, "170": 68, "171": 70, "172": 71, "173": 71, "174": 71, "175": 71, "176": 71, "177": 73, "183": 78, "192": 78, "193": 79, "194": 80, "195": 81, "196": 81, "197": 82, "198": 83, "199": 83, "200": 83, "201": 83, "202": 83, "203": 84, "204": 85, "205": 85, "206": 85, "207": 87, "208": 89, "214": 208}}
__M_END_METADATA
"""

```
</details>

And the template https://gist.github.com/orsenthil/6a851be3d0a4a631a94a7c5feb20a1b0

**Comment by Kwpolska** [comment]
I can’t reproduce this issue with Mako==1.0.7 and Python 3.7. Please test with an older Python version, and if necessary, report this bug to Mako’s developers.

**Comment by orsenthil** [comment]
> I can’t reproduce this issue 

@Kwpolska - With which version of Nikola (master or the released version)?

**Comment by Kwpolska** [comment]
It shouldn’t matter, but I tested with an older commit (v8.0.1+)
