### ISSUE TITLE
Something off with requirements for building from .ipynb notebooks

### ISSUE THREAD

**Issue by StanczakDominik** [getnikola/nikola#3237]
### Environment

**Python Version: 3.6.3**

**Nikola Version: 8.0.2**

**Operating System:** Travis CI on Ubuntu 14.04.5 LTS

### Description:

Please take a look at the following build logs from Travis CI, with automated nikola rebuilds set up [as seen in this Travis CI config](https://travis-ci.org/StanczakDominik/stanczakdominik.github.io/jobs/497842715/config):

1. [Commit 660937c builds without issues on Nikola 8.0.1](https://travis-ci.org/StanczakDominik/stanczakdominik.github.io/builds/495857251)
2. [I try to add an ipynb blog post today, with 8.0.2 out - this fails](https://travis-ci.org/StanczakDominik/stanczakdominik.github.io/builds/497839797)
3. [I revert to 660937c, which fails again with the failure part of the traceback attached below.](https://travis-ci.org/StanczakDominik/stanczakdominik.github.io/builds/497842714)
4. [I add `pip install jupyter` before running `pip install nikola[extras]`](https://github.com/StanczakDominik/stanczakdominik.github.io/commit/fe3a0bdf95c0b7c3919f508b47cb7e7fc8861b06), and...
5. [The build succeeds!](https://travis-ci.org/StanczakDominik/stanczakdominik.github.io/builds/497845167)

The relevant traceback:
```
$ nikola build && nikola github_deploy -m 'Nikola auto deploy [ci skip]'
[2019-02-24T18:38:38Z] WARNING: Nikola: The sections feature has been removed and its functionality has been merged into categories.
[2019-02-24T18:38:38Z] WARNING: Nikola: For more information on how to migrate, please read: https://getnikola.com/blog/upgrading-to-nikola-v8.html#sections-were-replaced-by-categories
[2019-02-24T18:38:38Z] INFO: Nikola: Setting CATEGORY_DESTPATH_AS_DEFAULT = True
[2019-02-24T18:38:39Z] ERROR: yapsy: Unable to import plugin: /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nikola/plugins/compile/ipynb
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/yapsy/PluginManager.py", line 510, in loadPlugins
    candidate_module = PluginManager._importModule(plugin_module_name, candidate_filepath)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/yapsy/PluginManager.py", line 576, in _importModule
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nikola/plugins/compile/ipynb.py", line 34, in <module>
    from nbconvert.exporters import HTMLExporter
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
    from .base import (export, get_exporter,
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nbconvert/exporters/base.py", line 13, in <module>
    from nbformat import NotebookNode
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nbformat/__init__.py", line 33, in <module>
    from .validator import validate, ValidationError
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nbformat/validator.py", line 12, in <module>
    from jsonschema import ValidationError
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/jsonschema/__init__.py", line 22, in <module>
    from jsonschema._types import TypeChecker
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/jsonschema/_types.py", line 49, in <module>
    class TypeChecker(object):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/jsonschema/_types.py", line 64, in TypeChecker
    _type_checkers = attr.ib(default=pmap(), converter=pmap)
TypeError: attrib() got an unexpected keyword argument 'converter'
Scanning posts.....Cannot find 'ipynb' compiler; it might require an extra plugin -- do you have it installed?
The command "nikola build && nikola github_deploy -m 'Nikola auto deploy [ci skip]'" exited with 1.
```
Thus, I'm not quite sure what, but something seems to have broken with the optional requirements for building Jupyter notebook posts in 8.0.2.

**Comment by Kwpolska** [comment]
The issue is with `attr`, which is not listed as a Nikola dependency (other packages pull it in).

> jsonschema 3.0.0 has requirement attrs>=17.4.0, but you'll have attrs 17.3.0 which is incompatible.

`attr` is probably included by default by Travis, they sometimes do that. `pip install -U --upgrade-strategy=eager 'Nikola[extras]'` would be enough. (I updated the [blog post](https://getnikola.com/blog/automating-nikola-rebuilds-with-travis-ci.html), and also removed language pack installs, which are unnecessary in v8.)

**Comment by StanczakDominik** [comment]
Oh. Okay then! Sorry for the false alarm!

**Comment by Kwpolska** [comment]
It’s fine, and the example was outdated and slightly incorrect, so thanks for reporting.
