### ISSUE TITLE
Nikola's template-loading breaks editable development installs

### ISSUE THREAD

**Issue by jean** [getnikola/nikola#3238]
An [editable](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs) install fails to run, because Nikola tries to lookup template files relative to the egg-link file, instead of in the referenced repo. 

Request: lookup files relative to the final location. 

```bash
~/git/nikola $ pip3 install --user -e .
$ nikola -V
Nikola v8.0.1
~/git/www/site $ nikola build
Scanning posts........done!
[...]
DependencyError - taskid:render_posts:cache/pages/2018/page.th.html
ERROR: Task 'render_posts:cache/pages/2018/page.th.html' saving success: Dependent file '/mnt/c/Users/John/.local/lib/python3.6/site-packages/nikola/data/themes/base/templates/post_list_directive.tmpl' does not exist
########################################
[...]
$ cat /mnt/c/Users/John/.local/lib/python3.6/site-packages/Nikola.egg-link
/mnt/c/Users/John/git/nikola
```

**Comment by Kwpolska** [comment]
Editable installs work for me on macOS and Linux. The issue is *probably*
caused by Windows and its lack of support for symlinks. Could you test if
an editable install works if your clone is on the WSL filesystem instead of
a NTFS mountpoint?

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by jean** [comment]
This is on Linux Mint (based on ):

```
12:43 john@john:~/git/nikola(master)$ pip install --user -e .
Obtaining file:///home/john/repos/git/nikola
Requirement already satisfied: doit>=0.30.1 in /home/john/.local/lib/python3.5/site-packages (from Nikola==8.0.2) (0.30.3)
[...]
Requirement already satisfied: pytz>=0a in /home/john/.local/lib/python3.5/site-packages (from Babel>=2.6.0->Nikola==8.0.2) (2018.7)
Installing collected packages: Nikola
  Found existing installation: Nikola 8.0.1
    Uninstalling Nikola-8.0.1:
      Successfully uninstalled Nikola-8.0.1
  Running setup.py develop for Nikola
Successfully installed Nikola

12:45 john@john:~/git/www/site(master)$ nikola build
Scanning posts........done!
.  render_posts:timeline_changes
.  render_posts:cache/pages/2018/pycon-thailand.th.html
Traceback (most recent call last):
  File "/home/john/.local/lib/python3.5/site-packages/doit/doit_cmd.py", line 167, in run
    return command.parse_execute(args)
  File "/home/john/.local/lib/python3.5/site-packages/doit/cmd_base.py", line 120, in parse_execute
    return self.execute(params, args)
  File "/home/john/.local/lib/python3.5/site-packages/doit/cmd_base.py", line 403, in execute
    return self._execute(**exec_params)
  File "/home/john/.local/lib/python3.5/site-packages/doit/cmd_run.py", line 252, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "/home/john/.local/lib/python3.5/site-packages/doit/runner.py", line 246, in run_all
    self.run_tasks(task_dispatcher)
  File "/home/john/.local/lib/python3.5/site-packages/doit/runner.py", line 213, in run_tasks
    self.process_task_result(node, catched_excp)
  File "/home/john/.local/lib/python3.5/site-packages/doit/runner.py", line 184, in process_task_result
    self.dep_manager.save_success(task)
  File "/home/john/.local/lib/python3.5/site-packages/doit/dependency.py", line 512, in save_success
    state = self.checker.get_state(dep, self._get(task.name, dep))
  File "/home/john/.local/lib/python3.5/site-packages/doit/dependency.py", line 394, in get_state
    timestamp = os.path.getmtime(dep)
  File "/usr/lib/python3.5/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/john/.local/lib/python3.5/site-packages/nikola/data/themes/base/templates/post_list_directive.tmpl'

12:46 john@john:~/git/www/site(master)$ nikola -V
Nikola v8.0.2

12:46 john@john:~/git/www/site(master)$ inxi -F
System:    Host: john Kernel: 4.15.0-45-generic x86_64 (64 bit) Desktop: Cinnamon 3.6.7
           Distro: Linux Mint 18.3 Sylvia
```

Linux Mint 18.3 is based on Ubuntu 16.04.

**Comment by Kwpolska** [comment]
Cannot reproduce on Ubuntu bionic (18.04).

```
vagrant@ubuntu-bionic:~/nsite$ python3 --version
Python 3.6.7
vagrant@ubuntu-bionic:~$ mount
/dev/sda1 on / type ext4 (rw,relatime,data=ordered)
vagrant@ubuntu-bionic:~$ git --version
git version 2.17.1
vagrant@ubuntu-bionic:~$ git clone https://github.com/getnikola/nikola
vagrant@ubuntu-bionic:~$ cd nikola
vagrant@ubuntu-bionic:~/nikola$ pip3 install -e .
  Running setup.py develop for Nikola
Successfully installed Babel-2.6.0 Markdown-2.6.11 MarkupSafe-1.1.1 Nikola Pillow-5.4.1 PyRSS2Gen-1.1 Pygments-2.3.1 Yapsy-1.12.0 blinker-1.4 certifi-2018.11.29 chardet-3.0.4 cloudpickle-0.8.0 docutils-0.14 doit-0.31.1 idna-2.8 logbook-1.4.3 lxml-4.3.1 mako-1.0.7 natsort-6.0.0 piexif-1.1.2 pyinotify-0.9.6 python-dateutil-2.8.0 pytz-2018.9 requests-2.21.0 setuptools-40.8.0 six-1.12.0 unidecode-1.0.23 urllib3-1.24.1
vagrant@ubuntu-bionic:~/nikola$ cd ..
vagrant@ubuntu-bionic:~$ .local/bin/nikola init -qd nsite
[2019-02-27T17:24:04Z] INFO: init: A new site with example data has been created at nsite.
[2019-02-27T17:24:04Z] INFO: init: See README.txt in that folder for more information.
vagrant@ubuntu-bionic:~$ cd nsite
vagrant@ubuntu-bionic:~/nsite$ ~/.local/bin/nikola build
[build succeeds]
vagrant@ubuntu-bionic:~/nsite$ cat >> posts/1.rst


Here are my 5 latest and greatest blog posts:

.. post-list::
   :stop: 5
vagrant@ubuntu-bionic:~/nsite$ ~/.local/bin/nikola build
Scanning posts........done!
.  render_sources:output/posts/welcome-to-nikola/index.rst
.  render_posts:timeline_changes
.  render_posts:cache/posts/1.html
.  render_taxonomies:output/categories/cat_nikola/index.html
.  render_taxonomies:output/2012/index.html
.  render_taxonomies:output/categories/blog/index.html
.  render_taxonomies:output/categories/demo/index.html
.  render_taxonomies:output/categories/nikola/index.html
.  render_taxonomies:output/categories/python/index.html
.  render_taxonomies:output/index.html
.  render_pages:output/posts/welcome-to-nikola/index.html
.  render_taxonomies:output/categories/cat_nikola.xml
.  render_taxonomies:output/categories/blog.xml
.  render_taxonomies:output/categories/demo.xml
.  render_taxonomies:output/categories/python.xml
.  render_taxonomies:output/rss.xml
.  render_taxonomies:output/categories/nikola.xml
.  sitemap:output/sitemap.xml
```

1. Did you have Nikola ever installed as a non-editable package?
2. Could you try deleting `.doit.db` and trying again?
3. Please don’t delete parts of tracebacks, it might contain useful debugging information.

**Comment by jean** [comment]
I'm failing to reproduce this on current master.
