### ISSUE TITLE
Error loading tasks (exception). AttributeError: 'NoneType' object has no attribute 'split'.

### ISSUE THREAD

**Issue by Xeverous** [getnikola/nikola#3279]
**Python Version:** 3.6.8

**Nikola Version:** 8.0.2

**Operating System:** 64-bit GNU/Linux 4.15.0-20-generic; distro: Mint 19.1 (a fork of Ubuntu)

### Description:

Tried to build an empty site (no posts/pages), just some Jinja2 templates.

```
$ nikola build
Scanning posts........done!
[2019-08-04T13:06:35Z] ERROR: Nikola: Error loading tasks. An unhandled exception occurred.
[2019-08-04T13:06:35Z] ERROR: Nikola: AttributeError: 'NoneType' object has no attribute 'split'
[2019-08-04T13:06:35Z] NOTICE: Nikola: To see more details, run Nikola in debug mode (set environment variable NIKOLA_DEBUG=1) or use NIKOLA_SHOW_TRACEBACKS=1
```

With debug on:

First, I get a huge spam of errors (hundreds/thousands of entries) looking like this. Seems like yapsy has something wrong with `venv` directory but ... the venv directory is 1 level higher than the directory where the website is and Nikola is run.

```
[2019-08-04T13:11:17Z] DEBUG: yapsy: correct subclass tests failed for: sc in /home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/nikola/plugins/compile/html
Traceback (most recent call last):
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
[2019-08-04T13:11:17Z] DEBUG: yapsy: correct subclass tests failed for: write_metadata in /home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/nikola/plugins/compile/html
Traceback (most recent call last):
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
``` 

Then this at the end:

```
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfully loaded extension "yapsy_loaded_plugin_mdx_nikola_0.NikolaExtension".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfully loaded extension "yapsy_loaded_plugin_mdx_podcast_0.PodcastExtension".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfully loaded extension "yapsy_loaded_plugin_mdx_gist_0.GistExtension".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfuly imported extension module "markdown.extensions.fenced_code".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfuly imported extension module "markdown.extensions.codehilite".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfuly imported extension module "markdown.extensions.extra".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfuly imported extension module "markdown.extensions.smart_strong".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.smart_strong.SmartEmphasisExtension".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfuly imported extension module "markdown.extensions.fenced_code".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfuly imported extension module "markdown.extensions.footnotes".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.footnotes.FootnoteExtension".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfuly imported extension module "markdown.extensions.attr_list".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.attr_list.AttrListExtension".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfuly imported extension module "markdown.extensions.def_list".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.def_list.DefListExtension".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfuly imported extension module "markdown.extensions.tables".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.tables.TableExtension".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfuly imported extension module "markdown.extensions.abbr".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.abbr.AbbrExtension".
[2019-08-04T13:11:17Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.extra.ExtraExtension".
Scanning posts........done!
[2019-08-04T13:11:17Z] ERROR: Nikola: Error loading tasks. An unhandled exception occurred.
Traceback (most recent call last):
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/doit/cmd_base.py", line 389, in execute
    self, params, args)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/nikola/__main__.py", line 277, in load_tasks
    self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/doit/loader.py", line 313, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/doit/loader.py", line 26, in flat_generator
    for item in gen:
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/nikola/nikola.py", line 1956, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/nikola/nikola.py", line 1950, in flatten
    for t in task:
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/nikola/plugins/task/pages.py", line 66, in gen_tasks
    for task in self.site.generic_page_renderer(lang, post, kw["filters"], context):
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/nikola/nikola.py", line 2262, in generic_page_renderer
    url_type=post.url_type)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/nikola/nikola.py", line 2166, in generic_renderer
    file_deps += self.template_system.template_deps(template_name)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/nikola/plugins/template/jinja.py", line 129, in template_deps
    self.dependency_cache[template_name] = [filename] + self.get_deps(filename)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/nikola/plugins/template/jinja.py", line 123, in get_deps
    return self.get_string_deps(text)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/nikola/plugins/template/jinja.py", line 113, in get_string_deps
    filename = self.lookup.loader.get_source(self.lookup, dep_name)[1]
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 168, in get_source
    pieces = split_template_path(template)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 27, in split_template_path
    for piece in template.split('/'):
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by Xeverous** [comment]
Yapsy error spam shows up when running any Nikola command, even `--help`.

**Comment by ralsina** [comment]
I can't reproduce with the given data. Could you make a zip file with the site showing the problem?

Also: version of nikola?

**Comment by Xeverous** [comment]
to reproduce: `git clone https://github.com/Xeverous/the_website.git && git checkout test-nikola-error-loading-task`

> Also: version of nikola?

specified at the top

**Comment by ralsina** [comment]
Checked out your repo, checked out the branch, installed nikola 8.0.2 via pip, no error.

Could you cleanup your virtual environment and reinstall? Maybe it's some old pyc file or something.

**Comment by Xeverous** [comment]
deactivated, then `rm -rf venv` and ... I needed to install `virtualenv` in order to use it again (perhaps that was some self-managed installation or something from pipenv)

Did `sudo apt install virtualenv` and `virtualenv -p python3.7 venv`, entered directory and still the same thing:

```
$ nikola build
Scanning posts........done!
[2019-08-04T14:35:22Z] ERROR: Nikola: Error loading tasks. An unhandled exception occurred.
Traceback (most recent call last):
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/doit/cmd_base.py", line 389, in execute
    self, params, args)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/__main__.py", line 277, in load_tasks
    self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/doit/loader.py", line 313, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/doit/loader.py", line 26, in flat_generator
    for item in gen:
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/nikola.py", line 1956, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/nikola.py", line 1950, in flatten
    for t in task:
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/plugins/task/pages.py", line 66, in gen_tasks
    for task in self.site.generic_page_renderer(lang, post, kw["filters"], context):
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/nikola.py", line 2262, in generic_page_renderer
    url_type=post.url_type)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/nikola.py", line 2166, in generic_renderer
    file_deps += self.template_system.template_deps(template_name)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/plugins/template/jinja.py", line 129, in template_deps
    self.dependency_cache[template_name] = [filename] + self.get_deps(filename)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/plugins/template/jinja.py", line 123, in get_deps
    return self.get_string_deps(text)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/nikola/plugins/template/jinja.py", line 113, in get_string_deps
    filename = self.lookup.loader.get_source(self.lookup, dep_name)[1]
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 168, in get_source
    pieces = split_template_path(template)
  File "/home/xeverous/workspace/the_website/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 27, in split_template_path
    for piece in template.split('/'):
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by ralsina** [comment]
Reproduced! Give me a few minutes to figure it out.

**Comment by ralsina** [comment]
I have narrowed this to your theme.

Looks like something in our jinja dependency detector is not capable of
understanding it.
Should be easy-ish to fix, hopefully I can give you a patch today, life
permitting.

**Comment by ralsina** [comment]
When Nikola tries to find the dependencies of a template in your theme,
it's getting a list of Nones.

That is normal according to the docs, it just seems nobody ever tried to do
that in a Nikola theme yet:

If dynamic inheritance or inclusion is used, `None` will be
yielded.

Patch coming up.

**Comment by ralsina** [comment]
Please check the PR and let me know if it works, I have to run!

**Comment by Xeverous** [comment]
> When Nikola tries to find the dependencies of a template in your theme,
it's getting a list of Nones.
>
> That is normal according to the docs, it just seems nobody ever tried to do
that in a Nikola theme yet:

Should this be an error instead? Failure to find a dependency should not be ignored.

> If dynamic inheritance or inclusion is used, `None` will be
yielded.

Does it mean that Nikola does not support `extends` or `include` in Jinja2 templates?

**Comment by Xeverous** [comment]
> Please check the PR and let me know if it works

Looks like it works, but I would prefer a clear error when anything is missing.

```
$ nikola build
Scanning posts........done!
.  copy_assets:output/assets/css/style.css
.  copy_assets:output/assets/js/baguetteBox.min.js
.  copy_assets:output/assets/js/html5shiv-printshiv.min.js
.  copy_assets:output/assets/js/fancydates.min.js
.  copy_assets:output/assets/js/gallery.js
.  copy_assets:output/assets/js/justified-layout.min.js
.  copy_assets:output/assets/js/gallery.min.js
.  copy_assets:output/assets/js/fancydates.js
.  copy_assets:output/assets/js/moment-with-locales.min.js
.  copy_assets:output/assets/js/html5.js
.  copy_assets:output/assets/xml/rss.xsl
.  copy_assets:output/assets/xml/atom.xsl
.  copy_assets:output/assets/css/ipython.min.css
.  copy_assets:output/assets/css/rst_base.css
.  copy_assets:output/assets/css/baguetteBox.min.css
.  copy_assets:output/assets/css/rst.css
.  copy_assets:output/assets/css/nikola_ipython.css
.  copy_assets:output/assets/css/html4css1.css
.  copy_assets:output/assets/css/theme.css
.  copy_assets:output/assets/css/nikola_rst.css
.  copy_assets:output/assets/css/code.css
.  render_listings:output/listings/index.html
.  render_posts:timeline_changes
.  render_posts:cache/pages/test_page.html
.  render_posts:cache/pages/hello_world.html
.  render_taxonomies:output/blog/index.html
.  render_taxonomies:output/archive.html
.  render_taxonomies:output/categories/index.html
.  render_galleries:output/galleries/index.html
.  render_galleries:output/galleries/rss.xml
.  render_sources:output/test_page/index.md
.  render_sources:output/hello_world/index.md
.  render_pages:output/hello_world/index.html
TaskError - taskid:render_pages:output/hello_world/index.html
PythonAction Error
Traceback (most recent call last):
  File "/home/xeverous/workspace/the_website/venv_nikola/lib/python3.7/site-packages/doit/action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/xeverous/workspace/the_website/venv_nikola/src/nikola/nikola/nikola.py", line 1373, in render_template
    template_name, None, local_context)
  File "/home/xeverous/workspace/the_website/venv_nikola/src/nikola/nikola/plugins/template/jinja.py", line 96, in render_template
    data = template.render(**context)
  File "/home/xeverous/workspace/the_website/venv_nikola/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/xeverous/workspace/the_website/venv_nikola/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/xeverous/workspace/the_website/venv_nikola/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/xeverous/workspace/the_website/venv_nikola/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "themes/dark/templates/page.tmpl", line 4, in top-level template code
    {% include includes/head.tmpl %}
  File "/home/xeverous/workspace/the_website/venv_nikola/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'head' is undefined

########################################
render_pages:output/hello_world/index.html <stdout>:
```

Right now the error is some Jinja2 error, which is OK because the templates are not complete (they may even have syntax errors).

**Comment by Kwpolska** [comment]
> Does it mean that Nikola does not support extends or include in Jinja2 templates?

We support `extends` (see [example built-in template](https://github.com/getnikola/nikola/blob/master/nikola/data/themes/bootstrap4-jinja/templates/post.tmpl)). For segments, we use `import` and macros. Apparently, `include` cannot be supported, because Jinja2 won’t tell us about the dependencies involved.

**Comment by ralsina** [comment]
So, what will happen is that sometimes if you change the includes Nikola
won't know what needs rebuilding and you will have to use build -a

**Comment by Xeverous** [comment]
> Apparently, `include` cannot be supported, because Jinja2 won’t tell us about the dependencies involved.

Good to know. From what I have read, `import` have a superset of features of `include` so I can just edit my templates. Am I right?

**Comment by Kwpolska** [comment]
You will need to modify it to use macros instead of just plain file includes, but yeah, it will work for your use-case just fine.

**Comment by Xeverous** [comment]
Can I somehow easily obtain which plugins require which files?

**Comment by Kwpolska** [comment]
No, we don't store the information in any parseable way; you could try text
matching .py files.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Xeverous** [comment]
> You will need to modify it to use macros instead of just plain file includes, but yeah, it will work for your use-case just fine.

Can macros import other macros? I used to nest some includes.

**Comment by Kwpolska** [comment]
Jinja2 files can import other files, and your macro can call other macros,
possibly from other files. See built-in Nikola templates for examples of
this.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Xeverous** [comment]
Ok, I have working macros, they just needed `with context` to use variables supplied by Nikola.

I have noticed that even though `css/code.css` is in `ignored_assets`, it is still copied to the output directory. What should I do to remove it? Disable `copy_assets` plugin and write my own that does actually copy only my files?

**Comment by ralsina** [comment]
File a separate ticket for that one please.

IIRC code.css has a ton of special handling so this is probably a corner
case we never tried.

**Comment by Xeverous** [comment]
Can I create an issue for the `copy_assets` plugin? I do not want any built-in files. Maybe split this plugin into `copy_builtin_assets` and `copy_user_assets` (and leave both on default)?

**Comment by ralsina** [comment]
We don't have per-plugin issues in the main project, just describe the
problem and how you would prefer it worked.
