### ISSUE TITLE
Upgrading 8.0.2 to 8.0.3: conf.py cannot be parsed

### ISSUE THREAD

**Issue by bashtage** [getnikola/nikola#3314]
### Environment

**Python Version:**
3.7.5

**Nikola Version:**
8.0.3

**Operating System:**
Windows 
### Description:
When I run
```
nikola clean
```

I get

```
[2019-11-03T15:45:30Z] ERROR: Nikola: "conf.py" cannot be parsed.
Traceback (most recent call last):
KeyError: 'markupsafe'
```

markupsafe is installed.  This is in fresh venv with only Python and Nikola[extra].

The tb is not very informative about the location of the error so I'm not sure where to start.

**Comment by Kwpolska** [comment]
NIKOLA_SHOW_TRACEBACKS=1 nikola build

Or

NIKOLA_DEBUG=1 nikola build

Or

Pastebin your config, in particular the part where you use markupsafe

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by bashtage** [comment]
Conf here: [https://pastebin.com/66yD85re](https://pastebin.com/66yD85re)

Not much help with either of the debugging variables.

Using Linux now, I see

```
(nikola803) ➜  kevinsheppard.com git:(master) ✗ cd site
(nikola803) ➜  site git:(master) ✗ NIKOLA_SHOW_TRACEBACKS=1 nikola build
[2019-11-03T16:08:37Z] ERROR: Nikola: "conf.py" cannot be parsed.
Traceback (most recent call last):
KeyError: 'markupsafe'

(nikola803) ➜  site git:(master) ✗ NIKOLA_DEBUG=1 nikola build
[2019-11-03T16:08:45Z] DEBUG: Nikola: Website root: '/mnt/c/git/kevinsheppard.com/site'
[2019-11-03T16:08:45Z] ERROR: Nikola: "conf.py" cannot be parsed.
Traceback (most recent call last):
KeyError: 'markupsafe'
```

**Comment by bashtage** [comment]
Strange thing is markupsafe isn't in my conf. It is also only in Nikola in one place which is a straight import.

**Comment by bashtage** [comment]
Also, sis a quick search of my entire site and "markupsafe" doesn't appear anywhere

**Comment by Kwpolska** [comment]
This is specific to [your site’s](https://github.com/bashtage/kevinsheppard.com) `generate_index.py`. There seems to be both an issue with lackluster tracebacks, and also with the new import mechanics. A possible fix for this issue is to remove `sys.modules = sys.modules.copy()` from `__main__.py`.

@manuth, this looks related to #3244, could you please take a look?

```pytb
Traceback (most recent call last):
  File "/Users/kwpolska/virtualenvs/nikola/bin/nikola", line 11, in <module>
    load_entry_point('Nikola', 'console_scripts', 'nikola')()
  File "/Users/kwpolska/git/nikola/nikola/__main__.py", line 130, in main
    config = imp.load_module(conf_filename, file, conf_filename, (None, "rb", imp.PY_SOURCE)).__dict__
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "conf.py", line 5, in <module>
    import generate_index
  File "/Volumes/RAMDisk/kevinsheppard.com-master/site/generate_index.py", line 7, in <module>
    from jinja2 import Template
  File "/Users/kwpolska/virtualenvs/nikola/lib/python3.7/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/Users/kwpolska/virtualenvs/nikola/lib/python3.7/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/Users/kwpolska/virtualenvs/nikola/lib/python3.7/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/Users/kwpolska/virtualenvs/nikola/lib/python3.7/site-packages/jinja2/utils.py", line 647, in <module>
    from markupsafe import Markup, escape, soft_unicode
  File "/Users/kwpolska/virtualenvs/nikola/lib/python3.7/site-packages/markupsafe/__init__.py", line 321, in <module>
    from ._speedups import escape, escape_silent, soft_unicode
KeyError: 'markupsafe'
```

**Comment by bashtage** [comment]
Thanks @Kwpolska.  Removing the `.copy()` seems to fix the error, although I'm not sure what the side effects of this are overall.

Would be great to show the full traceback when the right flags are set here as well.  I can probably do a PR for this one.

**Comment by Kwpolska** [comment]
I undid the `.copy()` thing, messing with the module system could have more unwanted side effects than benefits.

Considering that having a traceback is very useful for debugging import issues with user-provided `.py` files, I changed the implementation to *always* show full tracebacks for config files (even without `NIKOLA_DEBUG` or `NIKOLA_SHOW_TRACEBACKS`).

**Comment by bashtage** [comment]
Fixed my issue.  Thanks.
