### ISSUE TITLE
dbm.error: db type is dbm.gnu, but the module is not available

### ISSUE THREAD

**Issue by Djultypremierdunom** [getnikola/nikola#3403]
Hi,

I'm on OS 10.7.5, working on a website with Nikola 8 in a virtualenv.
Newly updated, I had to upgrade a bunch of things. But at the very moment of truth and delightful enjoyment, terminal returns this :

(nikola_env) julien:nikola annebitran$ nikola build
[2020-04-29T17:30:36Z] WARNING: Nikola: The UNSLUGIFY_TITLES setting was renamed to FILE_METADATA_UNSLUGIFY_TITLES.
[2020-04-29T17:30:36Z] WARNING: Nikola: The TAG_PAGES_DESCRIPTIONS setting was renamed to TAG_DESCRIPTIONS.
Scanning posts.done!
Traceback (most recent call last):
File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/dependency.py", line 156, in init
self._dbm = ddbm.open(self.name, 'c')
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dbm/init.py", line 91, in open
"available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/doit_cmd.py", line 190, in run
return command.parse_execute(args)
File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/cmd_base.py", line 150, in parse_execute
return self.execute(params, args)
File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/cmd_base.py", line 580, in execute
codec_cls=codec_cls)
File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/dependency.py", line 503, in init
self.backend = db_class(backend_name, codec=codec_cls())
File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/dependency.py", line 171, in init
raise DatabaseException(message)
doit.dependency.DatabaseException: db type is dbm.gnu, but the module is not available

Any idea ? Thanks !!

**Comment by ralsina** [comment]
Delete .doit.db and run the command again.

When changing versions of Python this happens sometimes.

**Comment by Djultypremierdunom** [comment]
Sorry for my ingenuity, but how do I proceed ?

**Comment by Djultypremierdunom** [comment]
Do I have to delete the entire doit folder ?

**Comment by Djultypremierdunom** [comment]
When I delete the doit folder, terminal returns me :

...Scanning posts.done!
Traceback (most recent call last):
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/dependency.py", line 156, in __init__
    self._dbm = ddbm.open(self.name, 'c')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/doit_cmd.py", line 190, in run
    return command.parse_execute(args)
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/cmd_base.py", line 150, in parse_execute
    return self.execute(params, args)
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/cmd_base.py", line 580, in execute
    codec_cls=codec_cls)
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/dependency.py", line 503, in __init__
    self.backend = db_class(backend_name, codec=codec_cls())
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/dependency.py", line 171, in __init__
    raise DatabaseException(message)
doit.dependency.DatabaseException: db type is dbm.gnu, but the module is not available
(nikola_env) julien:nikola annebitran$ nikola build
Traceback (most recent call last):
  File "/Users/annebitran/nikola_env/bin/nikola", line 5, in <module>
    from nikola.__main__ import main
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/nikola/__init__.py", line 39, in <module>
    from .nikola import Nikola  # NOQA
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/nikola/nikola.py", line 51, in <module>
    from . import DEBUG, SHOW_TRACEBACKS, filters, utils, hierarchy_utils, shortcodes
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/nikola/filters.py", line 45, in <module>
    from .utils import req_missing, LOGGER, slugify
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/nikola/utils.py", line 58, in <module>
    from doit import tools
ModuleNotFoundError: No module named 'doit'

**Comment by Djultypremierdunom** [comment]
In fact, I think I do not have a .doit.db file... Unless I just don't know where to find it

**Comment by Kwpolska** [comment]
1. reinstall doit with pip
2. `.doit.db` (sometimes `.doit.db.db`) is in the same directory as `conf.py`

**Comment by Djultypremierdunom** [comment]
After reinstalling doit and deleting doit.db, I still get this message about dbm.gnu : 

(nikola_env) julien:nikola annebitran$ nikola build
[2020-04-29T18:56:28Z] WARNING: Nikola: The UNSLUGIFY_TITLES setting was renamed to FILE_METADATA_UNSLUGIFY_TITLES.
[2020-04-29T18:56:28Z] WARNING: Nikola: The TAG_PAGES_DESCRIPTIONS setting was renamed to TAG_DESCRIPTIONS.
Scanning posts.done!
Traceback (most recent call last):
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/dependency.py", line 156, in __init__
    self._dbm = ddbm.open(self.name, 'c')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/doit_cmd.py", line 190, in run
    return command.parse_execute(args)
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/cmd_base.py", line 150, in parse_execute
    return self.execute(params, args)
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/cmd_base.py", line 580, in execute
    codec_cls=codec_cls)
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/dependency.py", line 503, in __init__
    self.backend = db_class(backend_name, codec=codec_cls())
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/dependency.py", line 171, in __init__
    raise DatabaseException(message)
doit.dependency.DatabaseException: db type is dbm.gnu, but the module is not available

I must have done something wrong somewhere.

**Comment by Kwpolska** [comment]
```
rm -v .doit.db
ls -la
nikola build
```

**Comment by Djultypremierdunom** [comment]
Yeah ! Many so much thanks !

**Comment by Kwpolska** [comment]
Please send further user support questions to the mailing list: https://groups.google.com/forum/#!forum/nikola-discuss

This forum is meant for bugs, not support/usage questions.
