### ISSUE TITLE
REDIRECTIONS don't work with folders

### ISSUE THREAD

**Issue by jozo** [getnikola/nikola#3421]
### Environment

**Python Version:** 3.8

**Nikola Version:** 8.0.4

**Operating System:** Mac OS

### Description:

I have specified this in `conf.py`:

```python
REDIRECTIONS = [
    ("/example/", "/blog/"),
]
```

I expect that Nikola would generate `output/example/index.html` with proper redirection. Instead of that an error is shown:
```
Scanning posts........done!
.  redirect:output/example/
TaskError - taskid:redirect:output/example/
PythonAction Error
Traceback (most recent call last):
  File "/Users/jozo/Library/Caches/pypoetry/virtualenvs/jozo.github.io-Hg4rP4EQ-py3.8/lib/python3.8/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/jozo/Library/Caches/pypoetry/virtualenvs/jozo.github.io-Hg4rP4EQ-py3.8/lib/python3.8/site-packages/nikola/utils.py", line 1715, in create_redirect
    with io.open(src, "w+", encoding="utf8") as fd:
IsADirectoryError: [Errno 21] Is a directory: 'output/example/'
```

**Comment by Kwpolska** [comment]
I changed it to create the `INDEX_FILE` in the directory if one is given (with a trailing slash).
