### ISSUE TITLE
compressing Luxon with YUI fails

### ISSUE THREAD

**Issue by evgeni** [getnikola/nikola#3425]
### Environment

**Python Version:**

3.7.7

**Nikola Version:**

8.1.0

**Operating System:**

Fedora 32

### Description:

My `conf.py` has the following stanza:

```python
 FILTERS = {
   ".css": [filters.yui_compressor],
   ".js": [filters.yui_compressor],
 }
```

After the upgrade to 8.1.0 (and thus to Luxon), `nikola build` fails:

```console
.  copy_assets:output/assets/js/luxon.min.js
[ERROR] in output/assets/js/luxon.min.js
  1:48516:invalid property id
[ERROR] in output/assets/js/luxon.min.js
  1:0:Compilation produced 1 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 1 syntax errors.
	at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
	at org.mozilla.javascript.Parser.parse(Parser.java:396)
	at org.mozilla.javascript.Parser.parse(Parser.java:340)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
TaskError - taskid:copy_assets:output/assets/js/luxon.min.js
PythonAction Error
Traceback (most recent call last):
  File "/home/evgeni/.local/share/virtualenvs/die-welt.net-bJg0F5B9/lib/python3.7/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/evgeni/.local/share/virtualenvs/die-welt.net-bJg0F5B9/lib/python3.7/site-packages/nikola/utils.py", line 966, in unlessLink
    action(target)
  File "/home/evgeni/.local/share/virtualenvs/die-welt.net-bJg0F5B9/lib/python3.7/site-packages/nikola/filters.py", line 165, in yui_compressor
    return runinplace('{} --nomunge %1 -o %2'.format(yuicompressor), infile)
  File "/home/evgeni/.local/share/virtualenvs/die-welt.net-bJg0F5B9/lib/python3.7/site-packages/nikola/filters.py", line 138, in runinplace
    subprocess.check_call(command)
  File "/usr/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['yuicompressor', '--nomunge', 'output/assets/js/luxon.min.js', '-o', '/tmp/nikola_u0_atb5/luxon.min.js']' returned non-zero exit status 2.

########################################
copy_assets:output/assets/js/luxon.min.js <stdout>:

```

That is with:
```console
% yuicompressor --version
2.4.8
```

Removing the `js` line from the config fixes the issue.

**Comment by Kwpolska** [comment]
YUI Compressor hadn’t been updated since 2013. Luxon uses more modern JS constructs than the compressor knows of, so it can’t be minified by this.

We should probably offer a more modern minifier in our filters.

**Comment by evgeni** [comment]
Yeah, I'm only using YUI because that's what the handbook shows as first example. What would be some modern alternative?

**Comment by ralsina** [comment]
I use https://github.com/tdewolff/minify

All you have to put in the config is

import filters

def minify(infile):
    return filters.runinplace("minify %1 -o %2", infile)


FILTERS = {".css": [minify], ".js": [minify]}

**Comment by ralsina** [comment]
Closing, we should probably remove all the yui-related stuff since it's so old and broken.
