### ISSUE TITLE
Problem running tests with pytest 6.0

### ISSUE THREAD

**Issue by jose-matos** [getnikola/nikola#3441]
### Environment

**Python Version:** 3.8

**Nikola Version:** 8.1.1

**Operating System:** Fedora Linux 32

### Description:
Testing nikola on Fedora with pytest 6 turned out a problem

``
python-nikola has a logging problem uncovered by tests.

```
...
  File "/builddir/build/BUILD/nikola-8.1.1/nikola/shortcodes.py", line 374, in apply_shortcodes
    LOGGER.error('Unknown shortcode {0} (started at {1})', name, _format_position(data, current[2]))
Message: 'Unknown shortcode {0} (started at {1})'
Arguments: ('start', 'line 1, column 1')
```

The log template uses `%s` syntax, not `{0}` syntax:

```
>>> import logging
>>> logging.error('Unknown shortcode {0} (started at {1})', 'start', 'line 1, column 1') 
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<stdin>", line 1, in <module>
Message: 'Unknown shortcode {0} (started at {1})'
Arguments: ('start', 'line 1, column 1')
>>> logging.error('Unknown shortcode %s (started at %s)', 'start', 'line 1, column 1') 
ERROR:root:Unknown shortcode start (started at line 1, column 1)
```

**Comment by Kwpolska** [comment]
Fixed in commit 62c29c638, thanks for reporting.
