### ISSUE TITLE
Unable to customize gallery_shortcode template when installed as plugin

### ISSUE THREAD

**Issue by wohali** [getnikola/nikola#3476]
### Environment

**Python Version:** 3.7.3

**Nikola Version:** v8.1.1

**Operating System:** Linux x64

### Description:

[Install the plugin as directed](https://plugins.getnikola.com/v8/gallery_shortcode/) with `nikola plugin -i gallery_shortcode`. Then, try to create a `shortcodes/gallery.tmpl` or `themes/<whatever>/shortcodes/gallery.tmpl` or even as the readme wrongly says, `gallery_directive.tmpl`.

The customized template either does nothing, or at worst:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/home/joant/Projects/decromancer.ooo/.venv/lib/python3.7/site-packages/nikola/log.py", line 64, in format
    message = super().format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/joant/Projects/decromancer.ooo/.venv/bin/nikola", line 8, in <module>
    sys.exit(main())
  File "/home/joant/Projects/decromancer.ooo/.venv/lib/python3.7/site-packages/nikola/__main__.py", line 167, in main
    _ = DN.run(oargs)
  File "/home/joant/Projects/decromancer.ooo/.venv/lib/python3.7/site-packages/nikola/__main__.py", line 343, in run
    self.nikola.init_plugins()
  File "/home/joant/Projects/decromancer.ooo/.venv/lib/python3.7/site-packages/nikola/nikola.py", line 1163, in init_plugins
    self._register_templated_shortcodes()
  File "/home/joant/Projects/decromancer.ooo/.venv/lib/python3.7/site-packages/nikola/nikola.py", line 1689, in _register_templated_shortcodes
    fd.read(), os.path.join(sc_dir, fname)))
  File "/home/joant/Projects/decromancer.ooo/.venv/lib/python3.7/site-packages/nikola/nikola.py", line 1706, in register_shortcode
    utils.LOGGER.warning('Shortcode name conflict: {}', name)
Message: 'Shortcode name conflict: {}'
Arguments: ('gallery_shortcode',)
```

**Comment by Kwpolska** [comment]
The `shortcodes` directory is for simple (single-file, code-less) template-based shortcodes. For plugin-based shortcodes (which can have their own templates), you need to use the `templates` directory of your site or theme. I updated the docs of this plugin to mention this.

**Comment by wohali** [comment]
Hey @Kwpolska , thanks for this, but I'm confused - you edited the `gallery_directive` plugin for v7 but not the v8 `gallery_shortcode` README in https://github.com/getnikola/plugins/commit/68d5b1a121a967f35ae47753c083bdc62d9f0a1a .

I went to double check everything for myself again, and in the process solved my own problem - the issue is the docs still referring to `gallery_directive.tmpl` in the v8 shortcode implementation, where it should be `gallery_shortcode.tmpl`.

# Steps to reproduce

1. Install `"Nikola[extras]"` from pip
1. Create new site using `base` as a base, then `cd` into it
1. Install the v8 shortcode plugin: `nikola plugin -i gallery_shortcode`
1. `mkdir -p galleries/temp && curl -o galleries/temp/sample.jpg https://www.droid-life.com/wp-content/uploads/2016/10/google-pixel-samples-9.jpg`
1. Create a simple page with `nikola new_page` with the following contents:
```rst
.. title: Temp
.. slug: temp
.. date: 2020-11-17 17:26:04 UTC-05:00
.. type: text

{{% gallery temp %}}
```
1. `nikola build` and confirm the gallery is embedded in the file `output/test/index.html`.

So far, so good. Now:

1. `nikola theme -n temp --parent=base` & edit `conf.py` to use it
1. Create `themes/temp/templates/gallery_directive.tmpl` with the following content:
```
<p>THIS IS A TEST</p>
```
1. `nikola build -a` and look at the file `output/test/index.html`. There is no change to the page.

# The fix

Create the replacement template file as `themes/temp/templates/gallery_shortcode.tmpl` instead. Now, the rendered page includes "THIS IS A TEST" where the gallery used to be.

**Comment by Kwpolska** [comment]
I fixed the README for `gallery_shortcode` in getnikola/plugins@d269445 (including the template name).

**Comment by wohali** [comment]
Thank you, Chris!
