### ISSUE TITLE
Partial preserving of Exif does not work of the "Exif" object is not preserved

### ISSUE THREAD

**Issue by dtantsur** [getnikola/nikola#3491]
The [example in the docs](https://getnikola.com/handbook.html#preserve-some-exif-data) does not actually work:
```
[2020-12-29 17:52:26] ERROR: render_galleries: Can't process galleries/...., using original image! ('Exif')
Traceback (most recent call last):
  File "/home/dtantsur/.local/lib/python3.8/site-packages/nikola/image_processing.py", line 163, in resize_image
    save_args['exif'] = piexif.dump(exif)
  File "/home/dtantsur/.local/lib/python3.8/site-packages/piexif/_dump.py", line 38, in dump
    exif_ifd = exif_dict["Exif"]
KeyError: 'Exif'
```
(I've modified the code to output the traceback).

The fix is very simple: change
```python
                    if 'Exif' in exif:
                        exif["Exif"][piexif.ExifIFD.PixelXDimension] = w
                        exif["Exif"][piexif.ExifIFD.PixelYDimension] = h
```
to
```python
                    if 'Exif' in exif:
                        exif["Exif"][piexif.ExifIFD.PixelXDimension] = w
                        exif["Exif"][piexif.ExifIFD.PixelYDimension] = h
                    else:
                        exif["Exif"] = {}
```
(I guess the same should be done for `0th`).

**Comment by dtantsur** [comment]
It's more of a bug in piexif: https://github.com/hMatoba/Piexif/issues/114. Keeping this issue open for maintainers to decide if they want to land a workaround.

**Comment by Kwpolska** [comment]
I believe this should be fixed in `piexif`.
