### ISSUE TITLE
KeyError: 'Recent Posts' during nikola build

### ISSUE THREAD

**Issue by antocuni** [getnikola/nikola#3533]
### Environment

**Python Version:** 3.8.5

**Nikola Version:** 8.1.3

**Operating System:** Ubuntu 20.04

### Description:

I tried to follow the [official instructions](https://getnikola.com/getting-started.html) to get started:
```
homer tmp $ python3 --version
Python 3.8.5
homer tmp $ python3 -m venv trynikola
homer tmp $ . trynikola/bin/activate
(trynikola) homer tmp $ pip install nikola==8.1.3
[cut]
(trynikola) homer tmp $ nikola init --demo --quiet mydemo
(trynikola) homer tmp $ cd mydemo/
(trynikola) homer mydemo $ nikola build
[cut]
.  render_sidebar:output/sidebar-en.inc
TaskError - taskid:render_sidebar:output/sidebar-en.inc
PythonAction Error
Traceback (most recent call last):
  File "/tmp/trynikola/lib/python3.8/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/tmp/trynikola/lib/python3.8/site-packages/nikola/nikola.py", line 1472, in render_template
    data = self.template_system.render_template(
  File "/tmp/trynikola/lib/python3.8/site-packages/nikola/plugins/template/mako.py", line 113, in render_template
    data = template.render_unicode(**context)
  File "/tmp/trynikola/lib/python3.8/site-packages/mako/template.py", line 478, in render_unicode
    return runtime._render(
  File "/tmp/trynikola/lib/python3.8/site-packages/mako/runtime.py", line 878, in _render
    _render_context(
  File "/tmp/trynikola/lib/python3.8/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/tmp/trynikola/lib/python3.8/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/mydemo/cache/.mako.tmp/sidebar.tmpl.py", line 40, in render_body
    __M_writer(str( helper.list_posts(global_posts) ))
  File "/tmp/mydemo/cache/.mako.tmp/sidebar-helper.tmpl.py", line 37, in render_list_posts
    __M_writer(str( messages("Recent Posts", lang) ))
  File "/tmp/trynikola/lib/python3.8/site-packages/nikola/utils.py", line 216, in __call__
    return self[lang][key]
KeyError: 'Recent Posts'

########################################
render_sidebar:output/sidebar-en.inc <stdout>:
```

**Comment by Kwpolska** [comment]
It looks like you have the `sidebar` plugin installed user-wide (in `~/.nikola`). This plugin requires you to add some translations to `messages_en.py` in your theme. To fix this, you can either remove the `sidebar` plugin from `~/.nikola` (and install it only in sites that use it?), add the missing translations, or change the templates used by `sidebar` to not require those messages.

**Comment by antocuni** [comment]
Indeed, this was the case, thank you for the explanation. I didn't even know it was possible to have user-wide plugins and I have no idea how I installed one (maybe a previous attempt to install nikola weeks ago).

Ideally, it would be nice if nikola were able to detect that the error comes from a plugin and suggest a way to uninstall/disable it: this would make everything much more user friendly. But it's just a suggestion and I have no idea how hard it is to implement, so feel free to ignore me.

Thanks

**Comment by Kwpolska** [comment]
Implementing error source detection would be quite difficult in the general case. Right here, we could theoretically do that (since we could go from the `render_sidebar` task name to the plugin), but there are also other cases where we don’t know which plugin is at fault, or we might blame the wrong plugin. (It might also require extra bookkeeping, and I don’t think it would be useful enough for the extra work needed.)
