### ISSUE TITLE
Wordpress import: could not convert string to float

### ISSUE THREAD

**Issue by varna9000** [getnikola/nikola#3535]
### Environment

**Python Version:** 3.8

**Nikola Version:** Nikola v8.1.3

**Operating System:** Mac OS Big Sur

### Description:

I'm trying to import wordpress blog, but the following error occurs:

```
[2021-03-31 17:58:02] INFO: import_wordpress: Downloading https://xxxxxxxxxxxx/wp-content/uploads/2011/11/1.jpg => new_site/files/bg/wp-content/uploads/2011/11/1.jpg
Traceback (most recent call last):
  File "/Users/xxxxx/Library/Python/3.8/lib/python/site-packages/doit/doit_cmd.py", line 190, in run
    return command.parse_execute(args)
  File "/Users/xxxxx/Library/Python/3.8/lib/python/site-packages/doit/cmd_base.py", line 150, in parse_execute
    return self.execute(params, args)
  File "/Users/xxxxx/Library/Python/3.8/lib/python/site-packages/nikola/plugin_categories.py", line 148, in execute
    return self._execute(options, args)
  File "/Users/xxxxx/Library/Python/3.8/lib/python/site-packages/nikola/plugins/command/import_wordpress.py", line 387, in _execute
    self.import_posts(channel)
  File "/Users/xxxxx/Library/Python/3.8/lib/python/site-packages/nikola/plugins/command/import_wordpress.py", line 1138, in import_posts
    self.process_item_if_attachment(item)
  File "/Users/xxxxx/Library/Python/3.8/lib/python/site-packages/nikola/plugins/command/import_wordpress.py", line 1101, in process_item_if_attachment
    data = self.import_attachment(item, wordpress_namespace)
  File "/Users/xxxxx/Library/Python/3.8/lib/python/site-packages/nikola/plugins/command/import_wordpress.py", line 606, in import_attachment
    add('created_timestamp', b'created_timestamp', is_float=True, ignore_zero=True)
  File "/Users/xxxxx/Library/Python/3.8/lib/python/site-packages/nikola/plugins/command/import_wordpress.py", line 593, in add
    value = float(value)
ValueError: could not convert string to float: ''
```

**Comment by Kwpolska** [comment]
We'll need the export file from your blog to debug this. You can limit it to a snippet (only things related to the file mentioned in the error, plus a few more lines of context just in case.

**Comment by varna9000** [comment]
Here is the relevant snippet [snippet.txt](https://github.com/getnikola/nikola/files/6237793/snippet.txt)

**Comment by varna9000** [comment]
I tried fix [#3541 ](https://github.com/getnikola/nikola/commit/ef974e7158f22535f0214881ab40a05b405e8e6f) but it still outputs the same error.

**Comment by Kwpolska** [comment]
You’ll need to show us the full export file so we can debug this further.

**Comment by varna9000** [comment]
@Kwpolska sure, here it is. It's zipped since apparently GitHub doesn't support xml attachment.
[WordPress.2021-03-31.xml.zip](https://github.com/getnikola/nikola/files/6399827/WordPress.2021-03-31.xml.zip)

**Comment by Kwpolska** [comment]
@varna9000 I tested your export and it works on the `fix-3535-wordpress-blank-field` branch (commit 11c47d12af3f18d79b2853af299d7a7a4992088a). Based on that, I merged the change into `master`. If you encounter issues after updating to `master`, please report them.

**Comment by varna9000** [comment]
Yes, it works! My Nikola install was messed up. Thank you.
