### ISSUE TITLE
json.decoder.JSONDecodeError after nikola build

### ISSUE THREAD

**Issue by jhorneman** [getnikola/nikola#3602]
### Environment

**Python Version:** 3.9.6

**Nikola Version:** 8.2.0

**Operating System:** macOS 11.6.2

### Description:

`nikola build` worked fine for me for a few weeks. I would get spurious crashes but those would go away when I rebuilt. But recently I made a small change to a post, and since then I have been getting a consistent crash and can no longer build my site. Reverting the small change did not make the crash go away.

The output is:

```Bash
Traceback (most recent call last):
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/doit_cmd.py", line 295, in run
    return command.parse_execute(args)
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/cmd_base.py", line 151, in parse_execute
    return self.execute(params, args)
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/cmd_base.py", line 605, in execute
    return self._execute(**exec_params)
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/cmd_run.py", line 265, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/runner.py", line 255, in run_all
    self.run_tasks(task_dispatcher)
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/runner.py", line 218, in run_tasks
    if not self.select_task(node, task_dispatcher.tasks):
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/runner.py", line 118, in select_task
    if node.ignored_deps or self.dep_manager.status_is_ignore(task):
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/dependency.py", line 595, in status_is_ignore
    return self._get(task.name, "ignore:")
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/dependency.py", line 214, in get
    self._db[task_id] = self.codec.decode(task_data.decode('utf-8'))
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/dependency.py", line 60, in decode
    return self.decoder.decode(data)
  File "/Users/jhorneman/.pyenv/versions/3.9.6/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/jhorneman/.pyenv/versions/3.9.6/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 12195 (char 12194)
```

When I use `nikola build -a -c` the output is:

```Bash
HASH: Out of overflow pages.  Increase page size
Traceback (most recent call last):
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/runner.py", line 255, in run_all
    self.run_tasks(task_dispatcher)
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/runner.py", line 218, in run_tasks
    if not self.select_task(node, task_dispatcher.tasks):
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/runner.py", line 118, in select_task
    if node.ignored_deps or self.dep_manager.status_is_ignore(task):
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/dependency.py", line 595, in status_is_ignore
    return self._get(task.name, "ignore:")
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/dependency.py", line 214, in get
    self._db[task_id] = self.codec.decode(task_data.decode('utf-8'))
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/dependency.py", line 60, in decode
    return self.decoder.decode(data)
  File "/Users/jhorneman/.pyenv/versions/3.9.6/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/jhorneman/.pyenv/versions/3.9.6/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 12195 (char 12194)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/doit_cmd.py", line 295, in run
    return command.parse_execute(args)
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/cmd_base.py", line 151, in parse_execute
    return self.execute(params, args)
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/cmd_base.py", line 605, in execute
    return self._execute(**exec_params)
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/cmd_run.py", line 265, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/runner.py", line 260, in run_all
    self.finish()
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/runner.py", line 239, in finish
    self.dep_manager.close()
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/dependency.py", line 522, in close
    self.backend.dump()
  File "/Users/jhorneman/dev/intelligent-artifice/.direnv/python-3.9.6/lib/python3.9/site-packages/doit/dependency.py", line 179, in dump
    self._dbm[task_id] = self.codec.encode(self._db[task_id])
_dbm.error: cannot add item to database
```

`HASH: Out of overflow pages.  Increase page size` and `_dbm.error: cannot add item to database` are the spurious crashes that will go away when I rebuild.

My gut feeling is that the `JSONDecodeError` is still happening, but the `-c` means the build process doesn't stop.

But in the end I am still stuck with a site I can no longer build. I would be grateful for any pointers on how I can track down and solve this issue.

**Comment by Kwpolska** [comment]
Perhaps your `.doit.db` file is damaged, try removing it (or any files with similar names — some systems might end up with `.doit.db.db`, for example).

**Comment by jhorneman** [comment]
That worked, thanks!
