### ISSUE TITLE
nikola init --demo fails with a permission error

### ISSUE THREAD

**Issue by nbraud** [getnikola/nikola#3606]
### Environment

**Python Version:** 3.9.10

**Nikola Version:** 8.2.0

**Operating System:** NixOS “unstable” 22.05pre-git

### Description:

`nikola init --demo` fails, even when run in a clean environment and empty directory:
```
$ cd $(mktemp -d)  # Make a fresh, temporary directory, switch to it
$ nikola init --demo -q demo/
[2022-03-20 11:49:04] INFO: init: A new site with example data has been created at demo/.
[2022-03-20 11:49:04] INFO: init: See README.txt in that folder for more information.
Traceback (most recent call last):
  File "/nix/store/nbnxhr8lmw862z51xwm1kbbbkwyv77hp-python3-3.9.10-env/lib/python3.9/site-packages/doit/doit_cmd.py", line 295, in run
    return command.parse_execute(args)
  File "/nix/store/nbnxhr8lmw862z51xwm1kbbbkwyv77hp-python3-3.9.10-env/lib/python3.9/site-packages/doit/cmd_base.py", line 151, in parse_execute
    return self.execute(params, args)
  File "/nix/store/nbnxhr8lmw862z51xwm1kbbbkwyv77hp-python3-3.9.10-env/lib/python3.9/site-packages/nikola/plugin_categories.py", line 148, in execute
    return self._execute(options, args)
  File "/nix/store/nbnxhr8lmw862z51xwm1kbbbkwyv77hp-python3-3.9.10-env/lib/python3.9/site-packages/nikola/plugins/command/init.py", line 525, in _execute
    self.create_configuration(target)
  File "/nix/store/nbnxhr8lmw862z51xwm1kbbbkwyv77hp-python3-3.9.10-env/lib/python3.9/site-packages/nikola/plugins/command/init.py", line 285, in create_configuration
    with io.open(conf_path, 'w+', encoding='utf8') as fd:
PermissionError: [Errno 13] Permission denied: 'demo/conf.py'
```

### Diagnosis:

I believe this is due to the newly-created folder (here `./demo`) not being writeable by the user, as `nikola init` preserves the file mode from the `data/samplesite` resource, which is stored as read-only (even for its owner, `root`) by NixOS (like all other packages) :

```
$ ls -ld demo/
dr-xr-xr-x 9 nicoo users 200 janv.  1  1970 demo/

$ ls -ld /nix/store/nbnxhr8lmw862z51xwm1kbbbkwyv77hp-python3-3.9.10-env/lib/python3.9/site-packages/nikola/data/samplesite
dr-xr-xr-x 9 root root 10 janv.  1  1970 /nix/store/nbnxhr8lmw862z51xwm1kbbbkwyv77hp-python3-3.9.10-env/lib/python3.9/site-packages/nikola/data/samplesite
```

**Comment by nbraud** [comment]
This looks like a quick fix, I am now writing a patch.

**Comment by Kwpolska** [comment]
@nbraud Hi, what’s the status on your proposed patch? I can see you committed it to your repo, could you make a pull request with it?

**Comment by nbraud** [comment]
@Kwpolska Apologies for the lack of answer, I was quite ill and not working further on redoing my website (which is what I was trying `nikola` for)

I'll check out later today whether my patchset is ready to be submitted as a PR.

**Comment by davidak** [comment]
This is still an issue. It is similar to https://github.com/getnikola/nikola/issues/2962.

**Comment by Kwpolska** [comment]
We don't have the resources to figure out Nix. If anyone wants this fixed, patches are welcome.
