### ISSUE TITLE
doit==0.36.0 not compatible with Nikola

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#3612]
1. doit.cmd_auto was removed
2. Doit internals (TaskLoader) changed:

```
Traceback (most recent call last):
  File "C:\Users\Kwpolska\virtualenvs\nikola\Scripts\nikola-script.py", line 33, in <module>
    sys.exit(load_entry_point('Nikola', 'console_scripts', 'nikola')())
  File "c:\users\kwpolska\git\nikola\nikola\__main__.py", line 166, in main
    _ = DN.run(oargs)
  File "c:\users\kwpolska\git\nikola\nikola\__main__.py", line 376, in run
    return super().run(cmd_args)
  File "c:\users\kwpolska\virtualenvs\nikola\lib\site-packages\doit\doit_cmd.py", line 266, in run
    [CmdOption(opt) for opt in task_loader.cmd_options])
AttributeError: 'NikolaTaskLoader' object has no attribute 'cmd_options'
```

**Comment by Kwpolska** [comment]
Nikola v8.2.1 is out with a fix for this issue.
