### ISSUE TITLE
Runtime error with Python-Markdown 3.4.1

### ISSUE THREAD

**Issue by ulm** [getnikola/nikola#3636]
### Environment

**Python Version:**
3.10

**Nikola Version:**
8.2.2

**Operating System:**
Gentoo Linux

### Description:

Forwarding Gentoo Linux bug https://bugs.gentoo.org/860087.

With Nikola 8.2.2 and Python-Markdown version 3.4.1, I get the following error at runtime (when running for the site at https://github.com/gentoo-ev/www.gentoo-ev.org/tree/master/src):

```
$ nikola build -a
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/nikola", line 33, in <module>
    sys.exit(load_entry_point('Nikola==8.2.2', 'console_scripts', 'nikola')())
  File "/usr/lib/python3.10/site-packages/nikola/__main__.py", line 166, in main
    _ = DN.run(oargs)
  File "/usr/lib/python3.10/site-packages/nikola/__main__.py", line 354, in run
    self.nikola.init_plugins()
  File "/usr/lib/python3.10/site-packages/nikola/nikola.py", line 1173, in init_plugins
    plugin_info.plugin_object.set_site(self)
  File "/usr/lib/python3.10/site-packages/nikola/plugins/compile/markdown/__init__.py", line 105, in set_site
    self.converters[lang] = ThreadLocalMarkdown(extensions, lang_extension_configs)
  File "/usr/lib/python3.10/site-packages/nikola/plugins/compile/markdown/__init__.py", line 59, in __init__
    self.markdown = Markdown(extensions=extensions, extension_configs=extension_configs, output_format="html5")
  File "/usr/lib/python3.10/site-packages/markdown/core.py", line 96, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/usr/lib/python3.10/site-packages/markdown/core.py", line 131, in registerExtensions
    raise TypeError(
TypeError: Extension "yapsy_loaded_plugin_mdx_gist_0.GistExtension" must be of type: "markdown.extensions.Extension"
```

Downgrading Python-Markdown to version 3.3.7 works around the problem, but of course that's not a permanent solution.

**Comment by ulm** [comment]
Looks like this is a duplicate of #3635. Sorry for the noise.
