### ISSUE TITLE
nikola build fails with error registering extension

### ISSUE THREAD

**Issue by jni** [getnikola/nikola#3721]
### Environment

**Python Version:** 3.11.7

**Nikola Version:** 8.2.2 (installed from conda-forge)

**Operating System:** macOS 13.6.3

### Description:

When I try to run nikola build on my [blog](https://github.com/jni/ilovesymposia.com), using a fresh environment, I get the following error:

```pytb
Traceback (most recent call last):
  File "/Users/jni/micromamba/envs/blog/bin/nikola", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/jni/micromamba/envs/blog/lib/python3.11/site-packages/nikola/__main__.py", line 166, in main
    _ = DN.run(oargs)
        ^^^^^^^^^^^^^
  File "/Users/jni/micromamba/envs/blog/lib/python3.11/site-packages/nikola/__main__.py", line 354, in run
    self.nikola.init_plugins()
  File "/Users/jni/micromamba/envs/blog/lib/python3.11/site-packages/nikola/nikola.py", line 1173, in init_plugins
    plugin_info.plugin_object.set_site(self)
  File "/Users/jni/micromamba/envs/blog/lib/python3.11/site-packages/nikola/plugins/compile/markdown/__init__.py", line 105, in set_site
    self.converters[lang] = ThreadLocalMarkdown(extensions, lang_extension_configs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jni/micromamba/envs/blog/lib/python3.11/site-packages/nikola/plugins/compile/markdown/__init__.py", line 59, in __init__
    self.markdown = Markdown(extensions=extensions, extension_configs=extension_configs, output_format="html5")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jni/micromamba/envs/blog/lib/python3.11/site-packages/markdown/core.py", line 126, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/Users/jni/micromamba/envs/blog/lib/python3.11/site-packages/markdown/core.py", line 187, in registerExtensions
    raise TypeError(
TypeError: Extension "yapsy_loaded_plugin_mdx_podcast_0.PodcastExtension" must be of type: "markdown.extensions.Extension"
```

I can't find reports of similar errors online after a quick search, so any guidance would be appreciated! 🙏 

(I did just see that 8.2.4 is out on PyPI, so it would be good to update the conda-forge feedstock, too: https://github.com/conda-forge/nikola-feedstock/pull/12 Looks like that just needs a merge from @ickc.)

**Comment by jni** [comment]
Oops, just realised by looking through the release notes that this is a duplicate of #3635! Closing. But if someone could ping/take over maintenance of the conda-forge feedstock, that would be great. The documentation for adding maintainers is [here](https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list).
