### ISSUE TITLE
Blogger import doesn't seem to work

### ISSUE THREAD

**Issue by thomir** [getnikola/nikola#408]
I'm trying to migrate from a blogger blog to a nikola-powered site, but I'm running into problems. I'm trying the following:

$ nikola init foo
Created empty site at foo.

$ cd foo/

$ nikola import_blogger ~/Downloads/code/blog-03-21-2013.xml 
ERROR: Error parsing Command: option --empty not recognized (parsing options: ['--empty', 'new_site'])
Warning: Empty title in post with URL tag:blogger.com,1999:blog-128616657362436845.post-957950444561096945. Using NO_TITLE as placeholder, please fix.
Traceback (most recent call last):
  File "/home/thomi/Downloads/code/ve/local/lib/python2.7/site-packages/doit-0.20.0-py2.7.egg/doit/doit_cmd.py", line 102, in run
    return self.sub_cmds[command].parse_execute(args)
  File "/home/thomi/Downloads/code/ve/local/lib/python2.7/site-packages/doit-0.20.0-py2.7.egg/doit/cmd_base.py", line 58, in parse_execute
    return self.execute(params, args)
  File "/home/thomi/Downloads/code/nikola-5.4.2/scripts/../nikola/plugin_categories.py", line 68, in execute
    self._execute(options, args)
  File "/home/thomi/Downloads/code/nikola-5.4.2/nikola/plugins/command_import_blogger.py", line 100, in _execute
    self.import_posts(channel)
  File "/home/thomi/Downloads/code/nikola-5.4.2/nikola/plugins/command_import_blogger.py", line 274, in import_posts
    self.process_item(item)
  File "/home/thomi/Downloads/code/nikola-5.4.2/nikola/plugins/command_import_blogger.py", line 254, in process_item
    self.import_item(item, 'posts')
  File "/home/thomi/Downloads/code/nikola-5.4.2/nikola/plugins/command_import_blogger.py", line 242, in import_item
    title, slug, post_date, description, tags)
  File "/home/thomi/Downloads/code/nikola-5.4.2/nikola/plugins/command_import_blogger.py", line 179, in write_metadata
    with codecs.open(filename, "w+", "utf8") as fd:
  File "/home/thomi/Downloads/code/ve/lib/python2.7/codecs.py", line 881, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'new_site/posts/bloggercom1999blog-128616657362436845post-957950444561096945.meta'

It looks like nikola doesn't create the 'new_site/posts' directory, so I try and help it out:

$ mkdir -p new_site/posts

$ nikola import_blogger ~/Downloads/code/blog-03-21-2013.xml 
The folder new_site already exists - assuming that this is a already existing nikola site.
Warning: Empty title in post with URL tag:blogger.com,1999:blog-128616657362436845.post-957950444561096945. Using NO_TITLE as placeholder, please fix.
Traceback (most recent call last):
  File "/home/thomi/Downloads/code/ve/local/lib/python2.7/site-packages/doit-0.20.0-py2.7.egg/doit/doit_cmd.py", line 102, in run
    return self.sub_cmds[command].parse_execute(args)
  File "/home/thomi/Downloads/code/ve/local/lib/python2.7/site-packages/doit-0.20.0-py2.7.egg/doit/cmd_base.py", line 58, in parse_execute
    return self.execute(params, args)
  File "/home/thomi/Downloads/code/nikola-5.4.2/scripts/../nikola/plugin_categories.py", line 68, in execute
    self._execute(options, args)
  File "/home/thomi/Downloads/code/nikola-5.4.2/nikola/plugins/command_import_blogger.py", line 100, in _execute
    self.import_posts(channel)
  File "/home/thomi/Downloads/code/nikola-5.4.2/nikola/plugins/command_import_blogger.py", line 274, in import_posts
    self.process_item(item)
  File "/home/thomi/Downloads/code/nikola-5.4.2/nikola/plugins/command_import_blogger.py", line 254, in process_item
    self.import_item(item, 'posts')
  File "/home/thomi/Downloads/code/nikola-5.4.2/nikola/plugins/command_import_blogger.py", line 242, in import_item
    title, slug, post_date, description, tags)
  File "/home/thomi/Downloads/code/nikola-5.4.2/nikola/plugins/command_import_blogger.py", line 181, in write_metadata
    description)))
TypeError: sequence item 2: expected string or Unicode, datetime.datetime found

... but nikola breaks further down the line.

Any ideas?

**Comment by ChillarAnand** [comment]
Hi, 

import_blogger is generating only 46 posts out of 176 posts. 

Can you take a look? I have sent you xml file.

Thank you.

**Comment by punchagan** [comment]
@ChillarAnand I can take a look if you can share the xml.

**Comment by ChillarAnand** [comment]
@punchagan Thank you. Send you xml file.
