### ISSUE TITLE
zen them does not work

### ISSUE THREAD

**Issue by timmie** [getnikola/nikola#772]
in conf.py
`THEME = "zen"`

running the build

```

nikola build
Scanning posts......done!
.  render_site:output/categories/index.html
########################################
TaskError - taskid:render_site:output/categories/index.html
PythonAction Error
Traceback (most recent call last):
  File "/virtualenvs/nicola/local/lib/python2.7/site-packages/doit/action.py", line 343, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/virtualenvs/nicola/local/lib/python2.7/site-packages/nikola/nikola.py", line 561, in render_template
    template_name, None, local_context)
  File "/virtualenvs/nicola/local/lib/python2.7/site-packages/nikola/plugins/template/mako.py", line 74, in render_template
    data = template.render_unicode(**context)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 421, in render_unicode
    as_unicode=True)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 766, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 798, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 824, in _exec_template
    callable_(context, *args, **kwargs)
  File "/blog/cache/.mako.tmp/base.tmpl.py", line 95, in render_body
    __M_writer(unicode(arusahni.html_navigation_links()))
  File "/blog/cache/.mako.tmp/arusahni_helper.tmpl.py", line 46, in render_html_navigation_links
    for url, text, icon in navigation_links[lang]:
ValueError: need more than 2 values to unpack
```

**Comment by g1ra** [comment]
Navstories plugin also produce the exact same error with zen

**Comment by ralsina** [comment]
@g1ra the navstories plugin generates navigation links, and zen uses a different format for those.  So it's incompatible with that plugin.
